/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.Sl2.Straightening
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.Form
public import TauCeti.RingTheory.DividedPowers.Commutation
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.NoncommRing

/-!
# The ordered span of the rank-one Kostant form

Let `H`, `E`, and `F` satisfy the `sl₂` commutator relations in an associative algebra over `ℚ`.
The rank-one Kostant form is generated over `ℤ` by the divided powers of `E` and `F` and the
generalized binomial coefficients in `H`. This file proves the spanning half of its integral PBW
normal form: the subring generated by those elements is, as an additive group, spanned by

```text
F⁽ᵃ⁾ (H choose b) E⁽ᶜ⁾.
```

The substantive step is closure of the ordered span under multiplication. In a product of two
ordered monomials, `TauCeti.Sl2.dividedPower_e_mul_dividedPower_f` straightens the middle
`E⁽ᶜ⁾ F⁽ᵈ⁾`; the divided-power commutation formulas move the remaining Cartan coefficients back
to the middle; and integer translation preserves `TauCeti.ringChooseSpan H`. Thus every summand is
again an integral combination of ordered monomials.

This is the rank-one spanning step toward the integral PBW theorem for the Kostant form used in
the explicit Chevalley--Demazure construction of Layer 9 of the ReductiveGroups roadmap. Linear
independence of these monomials is not asserted here.

In the universal enveloping algebra `UniversalEnvelopingAlgebra ℚ L` of a Lie algebra `L` with an
`sl₂` triple `(h, e, f)`, the abstract rank-one generator set `TauCeti.Sl2.kostantGenerators`
identifies with `TauCeti.UniversalEnvelopingAlgebra.kostantGenerators ![e, f] ![h]`, and the
subring closure identifies with `TauCeti.UniversalEnvelopingAlgebra.kostantForm ![e, f] ![h]`.

## Main definitions and results

* `TauCeti.Sl2.orderedKostantMonomial` is `F⁽ᵃ⁾ (H choose b) E⁽ᶜ⁾`.
* `TauCeti.Sl2.orderedKostantSpan` is their additive `ℤ`-span.
* `TauCeti.Sl2.mul_mem_orderedKostantSpan` proves that span is closed under multiplication.
* `TauCeti.Sl2.kostantGenerators` is the set of rank-one divided-power and Cartan-binomial
  generators in an abstract associative `ℚ`-algebra.
* `TauCeti.Sl2.toAddSubgroup_subringClosure_kostantGenerators` identifies the additive group of the
  generated subring with the ordered span.
* `TauCeti.Sl2.kostantGenerators_eq_universalEnveloping` bridges the abstract rank-one generators to
  `TauCeti.UniversalEnvelopingAlgebra.kostantGenerators`.
* `TauCeti.Sl2.toAddSubgroup_kostantForm` identifies the additive group of the enveloping-algebra
  Kostant form `kostantForm ![e, f] ![h]` with the ordered span.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §26.2.
* J. C. Jantzen, *Representations of Algebraic Groups*, 2nd ed., II.1.
-/

public section

namespace TauCeti.Sl2

open Finset
open Associative

universe u

attribute [local instance] TauCeti.moduleNNRat

variable {A : Type u} [Ring A] [Algebra ℚ A]

/-- An ordered rank-one Kostant monomial `F⁽ᵃ⁾ (H choose b) E⁽ᶜ⁾`. -/
noncomputable def orderedKostantMonomial (H E F : A) (a b c : ℕ) : A :=
  dividedPower a F * Ring.choose H b * dividedPower c E

theorem orderedKostantMonomial_zero_zero_zero (H E F : A) :
    orderedKostantMonomial H E F 0 0 0 = 1 := by
  simp [orderedKostantMonomial]

@[simp]
theorem orderedKostantMonomial_left (H E F : A) (n : ℕ) :
    orderedKostantMonomial H E F n 0 0 = dividedPower n F := by
  simp [orderedKostantMonomial]

@[simp]
theorem orderedKostantMonomial_middle (H E F : A) (n : ℕ) :
    orderedKostantMonomial H E F 0 n 0 = Ring.choose H n := by
  simp [orderedKostantMonomial]

@[simp]
theorem orderedKostantMonomial_right (H E F : A) (n : ℕ) :
    orderedKostantMonomial H E F 0 0 n = dividedPower n E := by
  simp [orderedKostantMonomial]

/-- The set of ordered rank-one Kostant monomials. -/
noncomputable def orderedKostantMonomials (H E F : A) : Set A :=
  {x | ∃ a b c : ℕ, orderedKostantMonomial H E F a b c = x}

/-- Membership in the set of ordered rank-one Kostant monomials. -/
@[simp]
theorem mem_orderedKostantMonomials_iff {H E F x : A} :
    x ∈ orderedKostantMonomials H E F ↔
      ∃ a b c : ℕ, orderedKostantMonomial H E F a b c = x :=
  Iff.rfl

/-- The additive `ℤ`-span of the ordered rank-one Kostant monomials. -/
noncomputable def orderedKostantSpan (H E F : A) : AddSubgroup A :=
  AddSubgroup.closure (orderedKostantMonomials H E F)

/-- Every ordered Kostant monomial belongs to its additive span. -/
@[simp]
theorem orderedKostantMonomial_mem_orderedKostantSpan (H E F : A) (a b c : ℕ) :
    orderedKostantMonomial H E F a b c ∈ orderedKostantSpan H E F :=
  AddSubgroup.subset_closure ⟨a, b, c, rfl⟩

/-- The ordered Kostant span lies in an additive subgroup exactly when that subgroup contains
every ordered Kostant monomial. -/
@[simp]
theorem orderedKostantSpan_le_iff {S : AddSubgroup A} {H E F : A} :
    orderedKostantSpan H E F ≤ S ↔ ∀ a b c, orderedKostantMonomial H E F a b c ∈ S :=
  ⟨fun h a b c => h (orderedKostantMonomial_mem_orderedKostantSpan H E F a b c),
    fun h => (AddSubgroup.closure_le _).2 fun _ ⟨a, b, c, heq⟩ => heq ▸ h a b c⟩

/-- The ordered Kostant span contains one. -/
@[simp]
theorem one_mem_orderedKostantSpan (H E F : A) : (1 : A) ∈ orderedKostantSpan H E F := by
  simpa using orderedKostantMonomial_mem_orderedKostantSpan H E F 0 0 0

/-- An ordered product with any integral combination of Cartan binomial coefficients in the
middle belongs to the ordered Kostant span. -/
theorem dividedPower_mul_mul_dividedPower_mem_orderedKostantSpan (H E F : A) (a c : ℕ)
    {r : A} (hr : r ∈ ringChooseSpan H) :
    dividedPower a F * r * dividedPower c E ∈ orderedKostantSpan H E F := by
  rw [ringChooseSpan_def] at hr
  induction hr using AddSubgroup.closure_induction with
  | mem r hr =>
      obtain ⟨b, rfl⟩ := hr
      exact orderedKostantMonomial_mem_orderedKostantSpan H E F a b c
  | zero => simp
  | add x y _ _ hx hy => simpa [mul_add, add_mul] using add_mem hx hy
  | neg x _ hx => simpa using neg_mem hx

omit [Algebra ℚ A] in
/-- Commutation of `H` past `F` expressed as a right-translation by `-2`. -/
private theorem cartan_mul_f {H F : A} (hhf : H * F - F * H = -(2 • F)) :
    H * F = F * (H + (-2 : A)) := by
  have htwo : F * (2 : A) = 2 • F := by simpa using (nsmul_eq_mul' F 2).symm
  calc
    H * F = (H * F - F * H) + F * H := (sub_add_cancel _ _).symm
    _ = -(2 • F) + F * H := by rw [hhf]
    _ = F * H + -(2 • F) := add_comm _ _
    _ = F * (H + (-2 : A)) := by
      rw [mul_add, mul_neg, htwo]

omit [Algebra ℚ A] in
/-- Commutation of `H` past `E` expressed as a right-translation by `2`. -/
private theorem cartan_mul_e {H E : A} (hhe : H * E - E * H = 2 • E) :
    H * E = E * (H + (2 : A)) := by
  have htwo : E * (2 : A) = 2 • E := by simpa using (nsmul_eq_mul' E 2).symm
  calc
    H * E = (H * E - E * H) + E * H := (sub_add_cancel _ _).symm
    _ = 2 • E + E * H := by rw [hhe]
    _ = E * H + 2 • E := add_comm _ _
    _ = E * (H + (2 : A)) := by
      rw [mul_add, htwo]

private theorem orderedKostantMonomial_mul_mem_orderedKostantSpan {H E F : A}
    (hef : E * F - F * E = H) (hhe : H * E - E * H = 2 • E)
    (hhf : H * F - F * H = -(2 • F)) (a b c d e f : ℕ) :
    orderedKostantMonomial H E F a b c * orderedKostantMonomial H E F d e f ∈
      orderedKostantSpan H E F := by
  -- Unfold the product of two ordered monomials and straighten the middle E⁽ᶜ⁾ F⁽ᵈ⁾.
  have hfactor :
      orderedKostantMonomial H E F a b c * orderedKostantMonomial H E F d e f =
        dividedPower a F * Ring.choose H b *
          (dividedPower c E * dividedPower d F) * Ring.choose H e * dividedPower f E := by
    simp only [orderedKostantMonomial, mul_assoc]
  rw [hfactor, dividedPower_e_mul_dividedPower_f hef hhe hhf]
  rw [mul_sum, sum_mul, sum_mul]
  -- Show that each summand in the straightening formula is in the ordered span.
  have hhf' := cartan_mul_f hhf
  have hhe' := cartan_mul_e hhe
  have hmoveF (k : ℕ) := ringChoose_mul_dividedPower b hhf'
    ((Nat.cast_commute 2 F).neg_left) (d - k)
  have hmoveE (k : ℕ) := dividedPower_mul_ringChoose e hhe' (Nat.cast_commute 2 E) (c - k)
  exact sum_mem fun k _ => by
    -- Step 1: Establish span membership of the central Cartan factor.
    have hmid₁ : Ring.choose (H + (d - k) • (-2 : A)) b ∈ ringChooseSpan H := by
      have h := ringChoose_add_intCast_mem_ringChooseSpan H (((d - k : ℕ) : ℤ) * -2) b
      simpa [nsmul_eq_mul] using h
    have hmid₂ : Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k ∈ ringChooseSpan H := by
      have h := ringChoose_add_intCast_mem_ringChooseSpan H
        (((2 * k : ℕ) : ℤ) - ((c + d : ℕ) : ℤ)) k
      rw [Int.cast_sub] at h
      push_cast at h ⊢
      convert h using 2
      abel
    have hmid₃ : Ring.choose (H - (c - k) • (2 : A)) e ∈ ringChooseSpan H := by
      have h := ringChoose_sub_intCast_mem_ringChooseSpan H (((c - k : ℕ) : ℤ) * 2) e
      simpa [nsmul_eq_mul] using h
    have hmiddle :
        Ring.choose (H + (d - k) • (-2 : A)) b *
            Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k *
              Ring.choose (H - (c - k) • (2 : A)) e ∈ ringChooseSpan H :=
      mul_mem_ringChooseSpan H (mul_mem_ringChooseSpan H hmid₁ hmid₂) hmid₃
    have hordered := dividedPower_mul_mul_dividedPower_mem_orderedKostantSpan H E F
      (a + (d - k)) ((c - k) + f) hmiddle
    -- Step 2: Commute divided powers and reorder the product.
    have hreorder :
        dividedPower a F * Ring.choose H b *
            (dividedPower (d - k) F *
              Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k *
                dividedPower (c - k) E) * Ring.choose H e * dividedPower f E =
          (dividedPower a F * dividedPower (d - k) F) *
            (Ring.choose (H + (d - k) • (-2 : A)) b *
                Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k *
                  Ring.choose (H - (c - k) • (2 : A)) e) *
              (dividedPower (c - k) E * dividedPower f E) := by
      calc
        dividedPower a F * Ring.choose H b *
              (dividedPower (d - k) F *
                Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k *
                  dividedPower (c - k) E) * Ring.choose H e * dividedPower f E =
            dividedPower a F * (Ring.choose H b * dividedPower (d - k) F) *
              Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k *
                (dividedPower (c - k) E * Ring.choose H e) * dividedPower f E := by
          noncomm_ring
        _ = dividedPower a F *
              (dividedPower (d - k) F * Ring.choose (H + (d - k) • (-2 : A)) b) *
                Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k *
                  (Ring.choose (H - (c - k) • (2 : A)) e * dividedPower (c - k) E) *
                    dividedPower f E := by rw [hmoveF k, hmoveE k]
        _ = (dividedPower a F * dividedPower (d - k) F) *
              (Ring.choose (H + (d - k) • (-2 : A)) b *
                  Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k *
                    Ring.choose (H - (c - k) • (2 : A)) e) *
                (dividedPower (c - k) E * dividedPower f E) := by
          noncomm_ring
    -- Step 3: Combine divided powers and extract the integer binomial scalars.
    have hnormal :
        (dividedPower a F * dividedPower (d - k) F) *
            (Ring.choose (H + (d - k) • (-2 : A)) b *
                Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k *
                  Ring.choose (H - (c - k) • (2 : A)) e) *
              (dividedPower (c - k) E * dividedPower f E) =
          Nat.choose (a + (d - k)) a •
            (Nat.choose ((c - k) + f) (c - k) •
              (dividedPower (a + (d - k)) F *
                (Ring.choose (H + (d - k) • (-2 : A)) b *
                    Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k *
                      Ring.choose (H - (c - k) • (2 : A)) e) *
                  dividedPower ((c - k) + f) E)) := by
      rw [mul_dividedPower a (d - k) F, mul_dividedPower (c - k) f E]
      simp only [smul_mul_assoc, mul_smul_comm]
      rw [smul_comm]
    rw [hreorder, hnormal]
    exact AddSubgroup.nsmul_mem _ (AddSubgroup.nsmul_mem _ hordered _) _

/-- The ordered rank-one Kostant span is closed under multiplication when `H`, `E`, and `F`
satisfy the `sl₂` commutator relations. -/
theorem mul_mem_orderedKostantSpan {H E F x y : A}
    (hef : E * F - F * E = H) (hhe : H * E - E * H = 2 • E)
    (hhf : H * F - F * H = -(2 • F))
    (hx : x ∈ orderedKostantSpan H E F) (hy : y ∈ orderedKostantSpan H E F) :
    x * y ∈ orderedKostantSpan H E F := by
  rw [orderedKostantSpan] at hx hy ⊢
  refine AddSubgroup.mul_mem_closure_of_mul_mem ?_ hx hy
  rintro _ ⟨a, b, c, rfl⟩ _ ⟨d, e, f, rfl⟩
  exact orderedKostantMonomial_mul_mem_orderedKostantSpan hef hhe hhf a b c d e f

/-- The three families of generators of the rank-one Kostant form in an abstract `ℚ`-algebra:
lowering and raising divided powers and generalized binomial coefficients in the Cartan element.

This is the rank-one generator set attached to a single `sl₂` triple `(H, E, F)` in an arbitrary
`ℚ`-algebra, distinct from the indexed family
`TauCeti.UniversalEnvelopingAlgebra.kostantGenerators`.
In the universal enveloping algebra `U(L)`, it identifies with
`TauCeti.UniversalEnvelopingAlgebra.kostantGenerators ![e, f] ![h]`. -/
noncomputable def kostantGenerators (H E F : A) : Set A :=
  Set.range (fun n => dividedPower n F) ∪
    Set.range (Ring.choose H) ∪ Set.range (fun n => dividedPower n E)

/-- Membership in the rank-one Kostant generator set. -/
@[simp]
theorem mem_kostantGenerators_iff {H E F x : A} :
    x ∈ kostantGenerators H E F ↔
      (∃ n, dividedPower n F = x) ∨ (∃ n, Ring.choose H n = x) ∨
        ∃ n, dividedPower n E = x := by
  simp [kostantGenerators, or_assoc]

/-- The subring generated by the rank-one Kostant generators coincides with the subring generated
by the ordered Kostant monomials. -/
theorem subringClosure_kostantGenerators_eq_subringClosure_orderedKostantMonomials
    (H E F : A) :
    Subring.closure (kostantGenerators H E F) =
      Subring.closure (orderedKostantMonomials H E F) := by
  apply le_antisymm
  · rw [Subring.closure_le]
    rintro x hx
    rw [mem_kostantGenerators_iff] at hx
    rcases hx with ⟨n, rfl⟩ | ⟨n, rfl⟩ | ⟨n, rfl⟩
    · have hmem : orderedKostantMonomial H E F n 0 0 ∈ orderedKostantMonomials H E F :=
        mem_orderedKostantMonomials_iff.2 ⟨n, 0, 0, rfl⟩
      simpa using Subring.subset_closure hmem
    · have hmem : orderedKostantMonomial H E F 0 n 0 ∈ orderedKostantMonomials H E F :=
        mem_orderedKostantMonomials_iff.2 ⟨0, n, 0, rfl⟩
      simpa using Subring.subset_closure hmem
    · have hmem : orderedKostantMonomial H E F 0 0 n ∈ orderedKostantMonomials H E F :=
        mem_orderedKostantMonomials_iff.2 ⟨0, 0, n, rfl⟩
      simpa using Subring.subset_closure hmem
  · rw [Subring.closure_le]
    rintro x ⟨a, b, c, rfl⟩
    dsimp only [orderedKostantMonomial]
    exact Subring.mul_mem _ (Subring.mul_mem _
      (Subring.subset_closure (mem_kostantGenerators_iff.2 (Or.inl ⟨a, rfl⟩)))
      (Subring.subset_closure (mem_kostantGenerators_iff.2 (Or.inr (Or.inl ⟨b, rfl⟩)))))
      (Subring.subset_closure (mem_kostantGenerators_iff.2 (Or.inr (Or.inr ⟨c, rfl⟩))))

/-- The additive group of the subring generated by the rank-one Kostant generators is exactly the
span of ordered `F`--`H`--`E` monomials. -/
@[simp]
theorem toAddSubgroup_subringClosure_kostantGenerators {H E F : A}
    (hef : E * F - F * E = H) (hhe : H * E - E * H = 2 • E)
    (hhf : H * F - F * H = -(2 • F)) :
    (Subring.closure (kostantGenerators H E F)).toAddSubgroup = orderedKostantSpan H E F := by
  rw [subringClosure_kostantGenerators_eq_subringClosure_orderedKostantMonomials,
    orderedKostantSpan, Subring.toAddSubgroup_closure_of_one_mem_of_mul_mem]
  · exact one_mem_orderedKostantSpan H E F
  · rintro _ ⟨a, b, c, rfl⟩ _ ⟨d, e, f, rfl⟩
    exact orderedKostantMonomial_mul_mem_orderedKostantSpan hef hhe hhf a b c d e f

/-- Membership in the subring generated by the rank-one Kostant generators is membership in the
ordered Kostant span. -/
@[simp]
theorem mem_subringClosure_kostantGenerators_iff {H E F x : A}
    (hef : E * F - F * E = H) (hhe : H * E - E * H = 2 • E)
    (hhf : H * F - F * H = -(2 • F)) :
    x ∈ Subring.closure (kostantGenerators H E F) ↔ x ∈ orderedKostantSpan H E F := by
  rw [← Subring.mem_toAddSubgroup, toAddSubgroup_subringClosure_kostantGenerators hef hhe hhf]

section UniversalEnveloping

open _root_.UniversalEnvelopingAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing

variable {L : Type*} [LieRing L] [LieAlgebra ℚ L] {h e f : L}

/-- The abstract rank-one Kostant generators coincide with the enveloping-algebra Kostant generators
attached to the two-element root family `![e, f]` and the one-element Cartan family `![h]`. -/
theorem kostantGenerators_eq_universalEnveloping :
    kostantGenerators (ι ℚ h) (ι ℚ e) (ι ℚ f) =
      TauCeti.UniversalEnvelopingAlgebra.kostantGenerators ![e, f] ![h] := by
  ext x
  simp only [mem_kostantGenerators_iff,
    TauCeti.UniversalEnvelopingAlgebra.mem_kostantGenerators_iff,
    Fin.exists_fin_two, Matrix.cons_val_zero, Matrix.cons_val_one,
    Fin.exists_fin_one]
  tauto

/-- The enveloping-algebra Kostant form `kostantForm ![e, f] ![h]` is the subring closure of the
rank-one Kostant generators. -/
theorem kostantForm_eq_subringClosure_kostantGenerators :
    TauCeti.UniversalEnvelopingAlgebra.kostantForm ![e, f] ![h] =
      Subring.closure (kostantGenerators (ι ℚ h) (ι ℚ e) (ι ℚ f)) := by
  rw [kostantGenerators_eq_universalEnveloping]
  apply le_antisymm
  · rw [TauCeti.UniversalEnvelopingAlgebra.kostantForm_le_iff]
    exact ⟨fun i n => Subring.subset_closure
        (TauCeti.UniversalEnvelopingAlgebra.mem_kostantGenerators_iff.2 (Or.inl ⟨i, n, rfl⟩)),
      fun i n => Subring.subset_closure
        (TauCeti.UniversalEnvelopingAlgebra.mem_kostantGenerators_iff.2 (Or.inr ⟨i, n, rfl⟩))⟩
  · rw [Subring.closure_le]
    rintro x hx
    rw [TauCeti.UniversalEnvelopingAlgebra.mem_kostantGenerators_iff] at hx
    rcases hx with ⟨i, n, rfl⟩ | ⟨i, n, rfl⟩
    · exact TauCeti.UniversalEnvelopingAlgebra.dividedPower_mem_kostantForm ![e, f] ![h] i n
    · exact TauCeti.UniversalEnvelopingAlgebra.ringChoose_mem_kostantForm ![e, f] ![h] i n

/-- The additive group of the Kostant integral form `kostantForm ![e, f] ![h]` in the universal
enveloping algebra is spanned by ordered `F`--`H`--`E` monomials. -/
@[simp]
theorem toAddSubgroup_kostantForm (hef : ⁅e, f⁆ = h) (hhe : ⁅h, e⁆ = 2 • e)
    (hhf : ⁅h, f⁆ = -(2 • f)) :
    (TauCeti.UniversalEnvelopingAlgebra.kostantForm ![e, f] ![h]).toAddSubgroup =
      orderedKostantSpan (ι ℚ h) (ι ℚ e) (ι ℚ f) := by
  rw [kostantForm_eq_subringClosure_kostantGenerators,
    toAddSubgroup_subringClosure_kostantGenerators]
  · simpa only [LieRing.of_associative_ring_bracket, hef] using ((ι ℚ).map_lie e f).symm
  · simpa only [LieRing.of_associative_ring_bracket, hhe, map_nsmul] using
      ((ι ℚ).map_lie h e).symm
  · simpa only [LieRing.of_associative_ring_bracket, hhf, map_neg, map_nsmul] using
      ((ι ℚ).map_lie h f).symm

/-- Membership in the Kostant integral form `kostantForm ![e, f] ![h]` is membership in the
ordered Kostant span. -/
@[simp]
theorem mem_kostantForm_iff (hef : ⁅e, f⁆ = h) (hhe : ⁅h, e⁆ = 2 • e)
    (hhf : ⁅h, f⁆ = -(2 • f)) {x : _root_.UniversalEnvelopingAlgebra ℚ L} :
    x ∈ TauCeti.UniversalEnvelopingAlgebra.kostantForm ![e, f] ![h] ↔
      x ∈ orderedKostantSpan (ι ℚ h) (ι ℚ e) (ι ℚ f) := by
  rw [← Subring.mem_toAddSubgroup, toAddSubgroup_kostantForm hef hhe hhf]

end UniversalEnveloping

end TauCeti.Sl2
