/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.Homological.ContCohomology.CohomologicalDimension.ClassModule.PGroup.FirstCohomology
import Mathlib.GroupTheory.Nilpotent
import TauCeti.RepresentationTheory.Homological.ContCohomology.CohomologicalDimension.ClassModule.Cyclic.SecondCohomology
import TauCeti.RepresentationTheory.Homological.ContCohomology.CohomologicalDimension.ClassModule.Inflation
import TauCeti.RepresentationTheory.Homological.ContCohomology.CohomologicalDimension.ClosedSubgroup

/-!
# The pro-p class module for a `p`-group quotient

Let `G` be a profinite group with `scd_p G ≤ 2` and let `V` be an open normal subgroup such that
`G ⧸ V` is a `p`-group. Then `H¹(G ⧸ V, V^ab(p)) = 0`, and `H²(G ⧸ V, V^ab(p))` is cyclic of order
`#(G ⧸ V)`, generated by the class `u_{G/V}(p)` (`TauCeti.abelianizationProPClass`). This is
NSW (3.6.4), (ii) ⇒ (iii), for `p`-group quotients; the Sylow argument of (3.6.3) passes from
these to arbitrary finite quotients.

## Main results

* `TauCeti.subsingleton_h1_abelianizationProP_of_isPGroup`: `H¹(G ⧸ V, V^ab(p)) = 0` for a
  `p`-group quotient `G ⧸ V`.
* `TauCeti.abelianizationProPClass_generates_of_isPGroup`: for a `p`-group quotient `G ⧸ V`,
  `u_{G/V}(p)` generates `H²(G ⧸ V, V^ab(p))`, a group of order `#(G ⧸ V)`.

## References

* J. Neukirch, A. Schmidt and K. Wingberg, *Cohomology of Number Fields*, 2nd ed.,
  the proofs of (3.6.3) and of (3.6.4), (ii) ⇒ (iii).
-/

public section

namespace TauCeti

open ContCohomology

universe u

variable {p : ℕ} {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  [CompactSpace G] [TotallyDisconnectedSpace G]

section Step

variable {V W : Subgroup G} [V.Normal] [W.Normal]

/-- For open normal subgroups `V ≤ W` of `G` with `scd_p G ≤ 2` and `H¹(W ⧸ V, V^ab(p))`
trivial, if `u_{G/W}(p)` generates `H²(G ⧸ W, W^ab(p))` and `u_{W/V}(p)` generates
`H²(W ⧸ V, V^ab(p))`, then `u_{G/V}(p)` generates `H²(G ⧸ V, V^ab(p))`, and the order of the
latter is the product of the orders of the former two. -/
private theorem abelianizationProPClass_generates_of_le (hp : p.Prime)
    (h : strictCohomologicalDimensionAt.{u} p G ≤ 2) (hVW : V ≤ W) (hV : IsOpen (V : Set G))
    [Subsingleton
      (H1 (W ⧸ V.subgroupOf W) (Additive (abelianizationProP p W (V.subgroupOf W))))]
    (hW : AddSubgroup.zmultiples
      (abelianizationProPClass p G W (Subgroup.isOpen_mono hVW hV)) = ⊤)
    (hWV : AddSubgroup.zmultiples
      (abelianizationProPClass p W (V.subgroupOf W) (W.subgroupOf_isOpen V hV)) = ⊤) :
    AddSubgroup.zmultiples (abelianizationProPClass p G V hV) = ⊤ ∧
      Nat.card (H2 (G ⧸ V) (Additive (abelianizationProP p G V))) =
        Nat.card (H2 (G ⧸ W) (Additive (abelianizationProP p G W))) *
          Nat.card
            (H2 (W ⧸ V.subgroupOf W) (Additive (abelianizationProP p W (V.subgroupOf W)))) := by
  have : Finite (G ⧸ V) := V.quotient_finite_of_isOpen hV
  have : V.FiniteIndex := Subgroup.finiteIndex_of_finite_quotient
  have : Subsingleton (H1 (W.map (QuotientGroup.mk' V)) (Additive (abelianizationProP p G V))) :=
    (abelianizationProPSubgroupOfH1Equiv p hVW hV).surjective.subsingleton
  set u := abelianizationProPClass p G V hV
  set g := explicitRes2 (G ⧸ V) (Additive (abelianizationProP p G V))
    (W.map (QuotientGroup.mk' V))
  set e := abelianizationProPSubgroupOfH2Equiv p hVW hV
  -- The restriction of `u_{G/V}(p)` is the image of `u_{W/V}(p)`, so it generates the target.
  have hgu : AddSubgroup.zmultiples (g u) = ⊤ := by
    have := AddMonoidHom.map_zmultiples e.toAddMonoidHom
      (abelianizationProPClass p W (V.subgroupOf W) (W.subgroupOf_isOpen V hV))
    rw [hWV, AddSubgroup.map_top_of_surjective _ e.surjective, AddEquiv.coe_toAddMonoidHom,
      abelianizationProPSubgroupOfH2Equiv_class] at this
    exact this.symm
  have hg : Function.Surjective g := by
    rw [← AddMonoidHom.range_eq_top, eq_top_iff, ← hgu, AddSubgroup.zmultiples_le]
    exact AddMonoidHom.mem_range.mpr ⟨u, rfl⟩
  -- The kernel of restriction is the image of `i`, generated by `i (u_{G/W}(p)) = (W : V) • u`.
  have hker : g.ker ≤ AddSubgroup.zmultiples u := by
    rw [← abelianizationProPInfl2_exact p hVW hV hp h, AddMonoidHom.range_eq_map, ← hW,
      AddMonoidHom.map_zmultiples, abelianizationProPInfl2_class, AddSubgroup.zmultiples_le]
    exact AddSubgroup.nsmul_mem _ (AddSubgroup.mem_zmultiples u) _
  refine ⟨?_, ?_⟩
  · rw [← sup_eq_left.mpr hker, ← AddSubgroup.comap_map_eq, AddMonoidHom.map_zmultiples, hgu,
      AddSubgroup.comap_top]
  · rw [← AddSubgroup.card_ker_mul_card_of_surjective hg,
      ← abelianizationProPInfl2_exact p hVW hV hp h, Nat.card_congr e.toEquiv.symm,
      Nat.card_congr (AddMonoidHom.ofInjective
        (abelianizationProPInfl2_injective p hVW hV hp h)).toEquiv.symm]

end Step

variable {V : Subgroup G} [V.Normal]

/-- For a profinite group `G` with `scd_p G ≤ 2` and an open normal subgroup `V` whose quotient
`G ⧸ V` is a `p`-group, `u_{G/V}(p)` generates
`H²(G ⧸ V, V^ab(p))`, a group of order `#(G ⧸ V)`. -/
theorem abelianizationProPClass_generates_of_isPGroup (hp : p.Prime)
    (h : strictCohomologicalDimensionAt.{u} p G ≤ 2) (hV : IsOpen (V : Set G))
    (hpV : IsPGroup p (G ⧸ V)) :
    AddSubgroup.zmultiples (abelianizationProPClass p G V hV) = ⊤ ∧
      Nat.card (H2 (G ⧸ V) (Additive (abelianizationProP p G V))) = Nat.card (G ⧸ V) := by
  -- Induct on `#(G ⧸ V)`, using standalone H¹ vanishing for the smaller quotient.
  -- A nontrivial `p`-group `G ⧸ V` has a normal subgroup of index `p`; its preimage `W`
  -- satisfies `#(G ⧸ W) = p`. Apply the prime-order case to `W ◁ G`, the induction
  -- hypothesis to `V.subgroupOf W ◁ W`, and combine them using the step lemma.
  induction hn : Nat.card (G ⧸ V) using Nat.strong_induction_on generalizing G V with
  | h n ih =>
  have : Finite (G ⧸ V) := V.quotient_finite_of_isOpen hV
  rcases subsingleton_or_nontrivial (G ⧸ V) with _ | _
  · rw [← hn, Nat.card_of_subsingleton (1 : G ⧸ V), Nat.card_of_subsingleton (0 : H2 _ _)]
    exact ⟨Subsingleton.elim _ _, rfl⟩
  -- Pull a normal subgroup of index `p` of the nontrivial `p`-group `G ⧸ V` back to `W`.
  have : Fact p.Prime := ⟨hp⟩
  have : Group.IsNilpotent (G ⧸ V) := hpV.isNilpotent
  obtain ⟨C, hCindex, hC⟩ := Group.IsNilpotent.exists_normal_index_eq_of_dvd_card
    (hpV.card_eq_or_dvd.resolve_left Finite.one_lt_card.ne')
  set W := C.comap (QuotientGroup.mk' V)
  have : W.Normal := hC.comap _
  have hVW : V ≤ W := QuotientGroup.le_comap_mk' V C
  have hW : IsOpen (W : Set G) := Subgroup.isOpen_mono hVW hV
  have hWcard : Nat.card (G ⧸ W) = p := by
    rw [← Subgroup.index_eq_card, Subgroup.index_comap_of_surjective C
      (QuotientGroup.mk'_surjective V), hCindex]
  -- `W ⧸ V` is the `p`-group `C`, of order `n / p`.
  have eWV : W ⧸ V.subgroupOf W ≃* C :=
    (quotientSubgroupOfEquivMap V W hV).toMulEquiv.trans (MulEquiv.subgroupCongr
      (Subgroup.map_comap_eq_self_of_surjective (QuotientGroup.mk'_surjective V) C))
  have : Finite (W ⧸ V.subgroupOf W) := .of_equiv _ eWV.symm.toEquiv
  have hn' : n = p * Nat.card (W ⧸ V.subgroupOf W) := by
    rw [← hn, Subgroup.card_eq_card_quotient_mul_card_subgroup C, ← Subgroup.index_eq_card,
      hCindex, Nat.card_congr eWV.toEquiv]
  have : CompactSpace W := isCompact_iff_compactSpace.mp (W.isClosed_of_isOpen hW).isCompact
  obtain ⟨hWV2, hWVcard⟩ := ih _ (by rw [hn']; exact lt_mul_left Nat.card_pos hp.one_lt)
    ((strictCohomologicalDimensionAt_le_of_isClosed (W.isClosed_of_isOpen hW)).trans h)
    (W.subgroupOf_isOpen V hV) ((hpV.to_subgroup C).of_equiv eWV.symm) rfl
  have := subsingleton_h1_abelianizationProP_of_isPGroup hp
    ((strictCohomologicalDimensionAt_le_of_isClosed (W.isClosed_of_isOpen hW)).trans h)
    (W.subgroupOf_isOpen V hV) ((hpV.to_subgroup C).of_equiv eWV.symm)
  have hW2 := abelianizationProPClass_generates_of_card_eq_prime hp h hW hWcard
  have h2 := abelianizationProPClass_generates_of_le hp h hVW hV hW2.1 hWV2
  exact ⟨h2.1, by rw [h2.2, hW2.2, hWVcard, hn']⟩

end TauCeti
