/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.MonoidAlgebra.Lift
public import Mathlib.Algebra.MonoidAlgebra.MapDomain
public import Mathlib.GroupTheory.Coset.Defs
public import Mathlib.LinearAlgebra.Dimension.StrongRankCondition
public import Mathlib.LinearAlgebra.Isomorphisms
public import Mathlib.RingTheory.Ideal.Maps
import Mathlib.LinearAlgebra.Dimension.Constructions

/-!
# Exactness for monoid algebras

The coefficient-sum augmentation ideal of a monoid algebra is generated by the basis
differences `single k 1 - 1`. For a group algebra, the differences indexed by a generating set
already generate it as a left ideal, and over a nontrivial ring this characterises generating
sets: `single x 1 - 1` lies in the left ideal generated by the differences indexed by `s` exactly
when `x` lies in the subgroup generated by `s`. More generally, a homomorphism from a group to a
monoid induces a monoid-algebra map whose kernel is generated by the corresponding differences for
elements in the kernel of the homomorphism.

These descriptions give the ideal-theoretic exactness of monoid algebras associated to an exact
pair of monoid homomorphisms whose middle object is a group. They provide the algebraic input for
transporting exact character sequences contravariantly to coordinate rings of diagonalizable
groups. The description by generators is the surjectivity half of Lyndon's exact sequence for the
relation module of a generating family (`TauCeti.MonoidAlgebra.relationModule`).

## Main declarations

* `TauCeti.MonoidAlgebra.augmentation`: the coefficient-sum augmentation.
* `TauCeti.MonoidAlgebra.ker_augmentation_eq_span`: its kernel is generated by basis
  differences.
* `MonoidAlgebra.augmentationLinearMap`: the augmentation as an `R`-linear map, and
  `MonoidAlgebra.quotientKerAugmentationEquiv`: the quotient `R[K] ⧸ I_K` by the augmentation
  ideal is `R`, so it has rank one (`MonoidAlgebra.finrank_quotient_ker_augmentation`), and the
  model `R[K]^n × R[K] ⧸ I_K` of `n` regular and one trivial representation has rank `n · #K + 1`
  (`MonoidAlgebra.finrank_pi_prod_quotient_ker_augmentation`). These live in the root
  `MonoidAlgebra` namespace, where dot notation on the monoid algebra finds them.
* `TauCeti.MonoidAlgebra.single_sub_one_mem_span_iff`: the left ideal generated by the
  differences indexed by `s` contains `single x 1 - 1` exactly when `x ∈ Subgroup.closure s`.
* `TauCeti.MonoidAlgebra.ker_augmentation_eq_span_of_closure_eq_top`,
  `TauCeti.MonoidAlgebra.ker_augmentation_eq_span_iff`: the differences indexed by a set generate
  the augmentation ideal of a group algebra exactly when the set generates the group.
* `TauCeti.MonoidAlgebra.single_sub_one_mem_ker_mapDomainRingHom_iff`: over a nontrivial ring,
  a basis difference lies in the kernel of an induced monoid-algebra map exactly when its index
  lies in the kernel of the homomorphism.
* `TauCeti.MonoidAlgebra.ker_mapDomainRingHom_eq_span`: the analogous kernel description for a
  homomorphism out of a group.
* `TauCeti.MonoidAlgebra.map_ker_augmentation_eq_ker_mapDomainRingHom`: the resulting exactness
  statement for ideals.

## References

Milne, *Algebraic Groups*, Theorem 12.9(b), gives the corresponding augmentation and quotient
description for group algebras of finitely generated commutative groups over a field. The proofs
here use finite support directly and apply to arbitrary coefficient rings and the indicated
possibly noncommutative monoids.
-/

public section

namespace MonoidAlgebra

variable {R : Type*} [Ring R] {G : Type*} [Group G]

/-- The coefficients of an element of `R[G]`, summed over the left cosets of `H`. This additive
map is right `H`-invariant, so it kills the left ideal generated by the differences
`single h 1 - 1`, `h ∈ H`, while it detects `single x 1 - 1` for `x ∉ H`. -/
private noncomputable def cosetCoeff (H : Subgroup G) :
    MonoidAlgebra R G →+ (G ⧸ H →₀ R) :=
  (Finsupp.mapDomain.addMonoidHom (QuotientGroup.mk : G → G ⧸ H)).comp
    coeffAddEquiv.toAddMonoidHom

private theorem cosetCoeff_single (H : Subgroup G) (g : G) (r : R) :
    cosetCoeff H (single g r) = Finsupp.single (g : G ⧸ H) r := by
  simp [cosetCoeff, Finsupp.mapDomain.addMonoidHom]

private theorem cosetCoeff_mul_eq_zero_of_mem_span {H : Subgroup G}
    {z : MonoidAlgebra R G}
    (hz : z ∈ Ideal.span ((fun h : G ↦ single h (1 : R) - 1) '' H))
    (y : MonoidAlgebra R G) : cosetCoeff H (y * z) = 0 := by
  induction hz using Submodule.span_induction generalizing y with
  | mem z hz =>
      obtain ⟨h, hh, rfl⟩ := hz
      induction y using induction_linear with
      | zero => simp
      | add y y' hy hy' => rw [add_mul, map_add, hy, hy', add_zero]
      | single g r =>
          rw [mul_sub, mul_one, single_mul_single, mul_one, map_sub,
            cosetCoeff_single, cosetCoeff_single,
            QuotientGroup.mk_mul_of_mem g hh, sub_self]
  | zero => simp
  | add z z' _ _ hz hz' => rw [mul_add, map_add, hz, hz', add_zero]
  | smul a z _ hz => rw [smul_eq_mul, ← mul_assoc, hz]

end MonoidAlgebra

namespace TauCeti

universe u v w x

open MonoidAlgebra

namespace MonoidAlgebra

variable (R : Type u) [Ring R]

/-- The coefficient-sum augmentation of a monoid algebra. It sends every standard basis element
to `1` and acts identically on coefficients. -/
noncomputable def augmentation (K : Type v) [Monoid K] : MonoidAlgebra R K →+* R :=
  liftNCRingHom (.id R) 1 fun _ _ ↦ Commute.one_right _

/-- The coefficient-sum augmentation sends a singleton to its coefficient. -/
@[simp]
theorem augmentation_single {K : Type v} [Monoid K] (k : K) (r : R) :
    augmentation R K (single k r) = r := by
  simp [augmentation]

/-- The coefficient-sum augmentation is natural with respect to homomorphisms of monoids. -/
@[simp]
theorem augmentation_comp_mapDomainRingHom {M : Type v} {N : Type w} [Monoid M] [Monoid N]
    (f : M →* N) :
    (augmentation R N).comp (mapDomainRingHom R f) = augmentation R M := by
  apply ringHom_ext <;> intro <;> simp

/-- The coefficient-sum augmentation is invariant under an isomorphism of monoids. -/
@[simp]
theorem augmentation_mapDomainRingEquiv {M : Type v} {N : Type w} [Monoid M] [Monoid N]
    (e : M ≃* N) (x : MonoidAlgebra R M) :
    augmentation R N (mapDomainRingEquiv R e x) = augmentation R M x :=
  RingHom.congr_fun (augmentation_comp_mapDomainRingHom R (e : M →* N)) x

private theorem mapDomain_basisDifference {M : Type v} {N : Type w} [Monoid M] [Monoid N]
    (f : M →* N) (m : M) :
    (mapDomainRingHom R f) (single m (1 : R) - 1) = single (f m) (1 : R) - 1 := by
  calc
    mapDomain f (single m (1 : R) - 1) =
        mapDomain f (single m (1 : R)) - mapDomain f 1 :=
      (mapDomainRingHom R f).map_sub _ _
    _ = single (f m) (1 : R) - 1 := by simp

/-- Over a nontrivial ring, the basis difference `single m 1 - 1` lies in the kernel of the
monoid-algebra map induced by `f` exactly when `m` lies in the kernel of `f`. -/
theorem single_sub_one_mem_ker_mapDomainRingHom_iff [Nontrivial R] {M : Type v} {N : Type w}
    [Monoid M] [Monoid N] (f : M →* N) (m : M) :
    single m (1 : R) - 1 ∈
        RingHom.ker (mapDomainRingHom R f) ↔ f m = 1 := by
  rw [RingHom.mem_ker, mapDomain_basisDifference, sub_eq_zero, one_def]
  exact (single_left_injective one_ne_zero).eq_iff

/-- The kernel of the coefficient-sum augmentation is generated by the differences between
standard basis elements and the unit basis element. -/
theorem ker_augmentation_eq_span (K : Type v) [Monoid K] :
    RingHom.ker (augmentation R K) =
      Ideal.span (Set.range fun k : K ↦
        single k (1 : R) - 1) := by
  apply le_antisymm
  · intro x hx
    have hdiff :
        x - single 1 (augmentation R K x) ∈
          Ideal.span (Set.range fun k : K ↦
            single k (1 : R) - 1) := by
      clear hx
      induction x using induction_linear with
      | zero => simp
      | add x y hx hy =>
          simpa only [map_add, single_add, add_sub_add_comm] using
            Ideal.add_mem _ hx hy
      | single k r =>
          have hgen : single k (1 : R) - 1 ∈
              Ideal.span (Set.range fun k : K ↦
                single k (1 : R) - 1) :=
            Ideal.subset_span ⟨k, rfl⟩
          have hmul := Ideal.mul_mem_left _ (single 1 r) hgen
          simpa only [augmentation_single, mul_sub, single_mul_single,
            one_mul, mul_one, one_def] using hmul
    simpa [RingHom.mem_ker.mp hx] using hdiff
  · rw [Ideal.span_le]
    rintro _ ⟨k, rfl⟩
    apply RingHom.mem_ker.mpr
    simp

section Closure

variable {G : Type v} [Group G]

/-- The left ideal generated by the basis differences `single g 1 - 1`, `g ∈ s`, contains
`single x 1 - 1` for every `x` in the subgroup generated by `s`. -/
theorem single_sub_one_mem_span_of_mem_closure {s : Set G} {x : G}
    (hx : x ∈ Subgroup.closure s) :
    single x (1 : R) - 1 ∈
      Ideal.span ((fun g : G ↦ single g (1 : R) - 1) '' s) := by
  induction hx using Subgroup.closure_induction with
  | mem g hg => exact Ideal.subset_span ⟨g, hg, rfl⟩
  | one => simp [← one_def]
  | mul g h _ _ hg hh =>
      -- `gh - 1 = g (h - 1) + (g - 1)`
      have hmem := Ideal.add_mem _ (Ideal.mul_mem_left _ (single g 1) hh) hg
      simp only [mul_sub, single_mul_single, mul_one] at hmem
      rwa [sub_add_sub_cancel] at hmem
  | inv g _ hg =>
      -- `g⁻¹ - 1 = -g⁻¹ (g - 1)`
      have hmem := neg_mem (Ideal.mul_mem_left _ (single g⁻¹ 1) hg)
      simp only [mul_sub, single_mul_single, inv_mul_cancel, mul_one,
        neg_sub] at hmem
      rwa [← one_def] at hmem

/-- Over a nontrivial ring, `single x 1 - 1` lies in the left ideal generated by the basis
differences `single g 1 - 1`, `g ∈ s`, exactly when `x` lies in the subgroup generated by `s`. -/
theorem single_sub_one_mem_span_iff [Nontrivial R] {s : Set G} {x : G} :
    single x (1 : R) - 1 ∈
        Ideal.span ((fun g : G ↦ single g (1 : R) - 1) '' s) ↔
      x ∈ Subgroup.closure s := by
  refine ⟨fun hx ↦ ?_, single_sub_one_mem_span_of_mem_closure R⟩
  have hle : Ideal.span ((fun g : G ↦ single g (1 : R) - 1) '' s) ≤
      Ideal.span ((fun g : G ↦ single g (1 : R) - 1) ''
        (Subgroup.closure s : Set G)) :=
    Ideal.span_mono (Set.image_mono Subgroup.subset_closure)
  have h := cosetCoeff_mul_eq_zero_of_mem_span (hle hx) 1
  rw [one_mul, map_sub, cosetCoeff_single, one_def,
    cosetCoeff_single, sub_eq_zero, Finsupp.single_left_inj one_ne_zero,
    QuotientGroup.eq, mul_one] at h
  exact inv_mem_iff.mp h

/-- The kernel of the augmentation of a group algebra is generated, as a left ideal, by the basis
differences `single g 1 - 1` for `g` running over any generating set of the group. -/
theorem ker_augmentation_eq_span_of_closure_eq_top {s : Set G} (hs : Subgroup.closure s = ⊤) :
    RingHom.ker (augmentation R G) =
      Ideal.span ((fun g : G ↦ single g (1 : R) - 1) '' s) := by
  rw [ker_augmentation_eq_span]
  refine le_antisymm ?_ (Ideal.span_mono (Set.image_subset_range _ _))
  rw [Ideal.span_le]
  rintro _ ⟨x, rfl⟩
  exact single_sub_one_mem_span_of_mem_closure R (hs ▸ Subgroup.mem_top x)

/-- Over a nontrivial ring, the basis differences `single g 1 - 1`, `g ∈ s`, generate the kernel
of the augmentation of a group algebra as a left ideal exactly when `s` generates the group. -/
theorem ker_augmentation_eq_span_iff [Nontrivial R] {s : Set G} :
    RingHom.ker (augmentation R G) =
        Ideal.span ((fun g : G ↦ single g (1 : R) - 1) '' s) ↔
      Subgroup.closure s = ⊤ := by
  refine ⟨fun h ↦ ?_, ker_augmentation_eq_span_of_closure_eq_top R⟩
  rw [eq_top_iff]
  rintro x -
  rw [← single_sub_one_mem_span_iff R, ← h, ker_augmentation_eq_span]
  exact Ideal.subset_span ⟨x, rfl⟩

end Closure

/-- If `q : G → H` is a surjective homomorphism from a group to a monoid, the kernel of the
induced monoid-algebra map is generated by the basis differences indexed by `ker q`. -/
private theorem ker_mapDomainRingHom_eq_span_of_surjective
    {G : Type v} {H : Type w} [Group G] [Monoid H]
    (q : G →* H) (hq : Function.Surjective q) :
    RingHom.ker (mapDomainRingHom R q) =
      Ideal.span (Set.range fun k : q.ker ↦
        single (k : G) (1 : R) - 1) := by
  apply le_antisymm
  · intro x hx
    let s : H → G := Function.surjInv hq
    have hs : Function.RightInverse s q := Function.rightInverse_surjInv hq
    have hdiff :
        x - mapDomain s (mapDomain q x) ∈
          Ideal.span (Set.range fun k : q.ker ↦
            single (k : G) (1 : R) - 1) := by
      clear hx
      induction x using induction_linear with
      | zero => simp
      | add x y hx hy =>
          simpa only [mapDomain_add, add_sub_add_comm] using
            Ideal.add_mem _ hx hy
      | single g r =>
          let k : q.ker := ⟨(s (q g))⁻¹ * g, by
            rw [MonoidHom.mem_ker]
            calc
              q ((s (q g))⁻¹ * g) = q ((s (q g))⁻¹) * q g := map_mul q _ _
              _ = q ((s (q g))⁻¹) * q (s (q g)) :=
                congrArg (q ((s (q g))⁻¹) * ·) (hs (q g)).symm
              _ = q ((s (q g))⁻¹ * s (q g)) := (map_mul q _ _).symm
              _ = 1 := by simp⟩
          have hgen : single (k : G) (1 : R) - 1 ∈
              Ideal.span (Set.range fun k : q.ker ↦
                single (k : G) (1 : R) - 1) :=
            Ideal.subset_span ⟨k, rfl⟩
          have hmul := Ideal.mul_mem_left _ (single (s (q g)) r) hgen
          simpa only [mapDomain_single, mul_sub,
            single_mul_single, mul_one, one_mul,
            one_def, k, mul_inv_cancel_left] using hmul
    have hx' : mapDomain q x = 0 := RingHom.mem_ker.mp hx
    simpa [hx'] using hdiff
  · rw [Ideal.span_le]
    rintro _ ⟨k, rfl⟩
    apply RingHom.mem_ker.mpr
    rw [mapDomain_basisDifference R q, MonoidHom.mem_ker.mp k.property,
      ← one_def, sub_self]

/-- If `q : G → H` is a homomorphism from a group to a monoid, the kernel of the induced
monoid-algebra map is generated by the basis differences indexed by `ker q`. -/
theorem ker_mapDomainRingHom_eq_span {G : Type v} {H : Type w} [Group G] [Monoid H]
    (q : G →* H) :
    RingHom.ker (mapDomainRingHom R q) =
      Ideal.span (Set.range fun k : q.ker ↦
        single (k : G) (1 : R) - 1) := by
  let q' := q.mrangeRestrict
  let i : MonoidHom.mrange q →* H := (MonoidHom.mrange q).subtype
  have hker : q'.ker = q.ker := by
    apply Subgroup.toSubmonoid_injective
    exact MonoidHom.mrangeRestrict_mker q
  calc
    RingHom.ker (mapDomainRingHom R q) =
        RingHom.ker ((mapDomainRingHom R i).comp
          (mapDomainRingHom R q')) := by
      rw [← mapDomainRingHom_comp]
      congr 2
    _ = RingHom.ker (mapDomainRingHom R q') :=
      RingHom.ker_comp_of_injective _
        (mapDomain_injective Subtype.val_injective)
    _ = Ideal.span (Set.range fun k : q.ker ↦
        single (k : G) (1 : R) - 1) := by
      have h := ker_mapDomainRingHom_eq_span_of_surjective R q'
        q.mrangeRestrict_surjective
      rw [hker] at h
      exact h

/-- An exact pair of monoid homomorphisms whose middle object is a group induces an exact ideal
sequence on monoid algebras: the extension of the first augmentation ideal is the kernel of the
second induced map. -/
theorem map_ker_augmentation_eq_ker_mapDomainRingHom {L : Type v} {G : Type w}
    {H : Type x} [Monoid L] [Group G] [Monoid H] (p : L →* G) (q : G →* H)
    (hexact : MonoidHom.mrange p = MonoidHom.mker q) :
    Ideal.map (mapDomainRingHom R p)
        (RingHom.ker (augmentation R L)) =
      RingHom.ker (mapDomainRingHom R q) := by
  rw [ker_augmentation_eq_span, Ideal.map_span, ker_mapDomainRingHom_eq_span R q]
  congr 1
  ext z
  constructor
  · rintro ⟨_, ⟨l, rfl⟩, rfl⟩
    have hl : p l ∈ q.ker := by
      apply MonoidHom.mem_ker.mpr
      have : p l ∈ MonoidHom.mker q := by
        rw [← hexact]
        exact MonoidHom.mem_mrange.mpr ⟨l, rfl⟩
      exact MonoidHom.mem_mker.mp this
    refine ⟨⟨p l, hl⟩, ?_⟩
    symm
    exact mapDomain_basisDifference R p l
  · rintro ⟨k, rfl⟩
    have hk : (k : G) ∈ MonoidHom.mrange p := by
      rw [hexact]
      exact MonoidHom.mem_mker.mpr (MonoidHom.mem_ker.mp k.property)
    obtain ⟨l, hl⟩ := MonoidHom.mem_mrange.mp hk
    refine ⟨single l (1 : R) - 1, ⟨l, rfl⟩, ?_⟩
    rw [mapDomain_basisDifference R p, hl]

end MonoidAlgebra

end TauCeti

/-! ### The augmentation as a linear map, and the trivial module `R[K] ⧸ I_K` -/

namespace MonoidAlgebra

open TauCeti.MonoidAlgebra

variable (R : Type u) [Ring R] (K : Type v) [Monoid K]

/-- The coefficient-sum augmentation as an `R`-linear map `R[K] → R`. -/
noncomputable def augmentationLinearMap :
    MonoidAlgebra R K →ₗ[R] R where
  toFun := augmentation R K
  map_add' := map_add _
  map_smul' r x := by
    induction x using induction_linear with
    | zero => simp
    | add x y hx hy => simp only [smul_add, map_add, hx, hy, RingHom.id_apply]
    | single k c => simp

@[simp]
theorem augmentationLinearMap_apply (x : MonoidAlgebra R K) :
    augmentationLinearMap R K x = augmentation R K x :=
  (rfl)

theorem augmentationLinearMap_surjective :
    Function.Surjective (augmentationLinearMap R K) :=
  fun r ↦ ⟨single 1 r, by simp⟩

/-- The kernel of the linear augmentation is the augmentation ideal, with scalars restricted. -/
theorem ker_augmentationLinearMap :
    LinearMap.ker (augmentationLinearMap R K) =
      (RingHom.ker (augmentation R K)).restrictScalars R := by
  ext; simp [RingHom.mem_ker]

/-- The quotient of `R[K]` by the augmentation ideal is `R`, the trivial module. -/
noncomputable def quotientKerAugmentationEquiv :
    (MonoidAlgebra R K ⧸ RingHom.ker (augmentation R K)) ≃ₗ[R] R :=
  (Submodule.Quotient.restrictScalarsEquiv R (RingHom.ker (augmentation R K))).symm ≪≫ₗ
    Submodule.quotEquivOfEq _ _ (ker_augmentationLinearMap R K).symm ≪≫ₗ
      LinearMap.quotKerEquivOfSurjective _
        (augmentationLinearMap_surjective R K)

@[simp]
theorem quotientKerAugmentationEquiv_mk (x : MonoidAlgebra R K) :
    quotientKerAugmentationEquiv R K
      (Ideal.Quotient.mk (RingHom.ker (augmentation R K)) x) = augmentation R K x :=
  (rfl)

/-- The quotient of `R[K]` by the augmentation ideal has rank one over `R`. -/
theorem finrank_quotient_ker_augmentation [StrongRankCondition R] :
    Module.finrank R (MonoidAlgebra R K ⧸ RingHom.ker (augmentation R K)) = 1 :=
  (quotientKerAugmentationEquiv R K).finrank_eq.trans (Module.finrank_self R)

/-- The model `R[K]^n × R[K] ⧸ I_K` of `n` copies of the regular representation and one trivial
one has rank `n · #K + 1` over `R`. -/
theorem finrank_pi_prod_quotient_ker_augmentation [StrongRankCondition R]
    [Finite K] (n : ℕ) :
    Module.finrank R ((Fin n → MonoidAlgebra R K) ×
      (MonoidAlgebra R K ⧸ RingHom.ker (augmentation R K))) = n * Nat.card K + 1 := by
  have := Module.Free.of_basis (basis K R)
  have := Module.Finite.of_basis (basis K R)
  rw [((LinearEquiv.refl R _).prodCongr
      (quotientKerAugmentationEquiv R K)).finrank_eq,
    Module.finrank_prod, Module.finrank_self, Module.finrank_pi_fintype,
    Module.finrank_eq_nat_card_basis (basis K R)]
  simp

end MonoidAlgebra
