/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.MeasureTheory.Constructions.Polish.Basic
public import Mathlib.MeasureTheory.Measure.AEMeasurable
public import Mathlib.MeasureTheory.Measure.Typeclasses.SFinite
import TauCeti.MeasureTheory.MeasurableSpace.Analytic
import TauCeti.Topology.MetricSpace.PiNat

/-!
# The Jankov–von Neumann uniformization theorem

A *uniformization* of a relation `R ⊆ X × Y` is a function `f : X → Y` whose graph lies in `R`
over the projection of `R`: `(x, f x) ∈ R` whenever `(x, y) ∈ R` for some `y`. Even a closed
relation between Polish spaces need not have a Borel measurable uniformization, but the
Jankov–von Neumann theorem shows that every analytic relation has a uniformization which is
measurable for the σ-algebra generated by the analytic subsets of `X`. By Lusin's theorem that
σ-algebra lies in the completion of every s-finite measure `μ` on `X`, so the uniformization agrees
`μ`-almost everywhere with a function measurable for the given σ-algebra on `X` (which contains the
open sets; when it is the Borel σ-algebra, this function is Borel measurable), and that function is
itself a uniformization of `R` at `μ`-almost every point of the projection.

This is the measurable selection theorem for a choice depending on a parameter, when the
admissible pairs of parameter and choice form an analytic set, for instance a closed or Borel one:
say a geodesic joining two points of a Polish geodesic space, chosen measurably in the pair of
endpoints relative to a fixed law of the endpoints.

## Proof

Write the analytic relation as the range of a continuous map `g : (ℕ → ℕ) → X × Y`, and let
`p : (ℕ → ℕ) → X` be its first component, so that the projection of `R` is the range of `p`. For
`x` in that range the fibre `p ⁻¹' {x}` is a nonempty closed subset of Baire space, and the
uniformization sends `x` to the second component of `g` at the lexicographically least point of
that fibre. Whether the least point has prescribed first `n + 1` coordinates is decided by whether
`x` lies in the images under `p` of finitely many cylinders: those images are analytic, and the
coordinates of the least point are therefore measurable for the σ-algebra generated by analytic
sets.

## Main results

* `MeasureTheory.AnalyticSet.exists_measurable_uniformization`: the **Jankov–von Neumann
  uniformization theorem**, for an analytic relation `R ⊆ X × Y` with `X` a T₁ space.
* `MeasureTheory.AnalyticSet.exists_measurable_ae_uniformization`: relative to an s-finite
  measure `μ` on a metrizable space `X`, an analytic relation has a uniformization at `μ`-almost
  every point of its projection that is measurable for the given σ-algebra on `X`.

## References

* A. S. Kechris, *Classical Descriptive Set Theory*, Springer-Verlag, 1995, Theorem 18.1.
* S. M. Srivastava, *A Course on Borel Sets*, Springer-Verlag, 1998, Theorem 5.5.2.
-/

public section

open Set PiNat

namespace MeasureTheory

variable {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]

section Uniformization

variable {p : (ℕ → ℕ) → X} {s : X → ℕ → ℕ}

omit [TopologicalSpace X] in
/-- Let `β` be the lexicographically least point of the fibre of `p` over `x`, lying in the
cylinder of `w` of length `n`. Then `β n = w n` exactly when `x` is the image of a point of that
cylinder whose `n`-th coordinate is `w n`, and of no point of it with a smaller `n`-th
coordinate. -/
private theorem apply_eq_iff_mem_image_cylinder {x : X} {β w : ℕ → ℕ} {n : ℕ} (hβx : p β = x)
    (hβ : IsLeast (toLex '' (p ⁻¹' {x})) (toLex β)) (hw : β ∈ cylinder w n) :
    β n = w n ↔ x ∈ p '' (cylinder w n ∩ (· n) ⁻¹' {w n}) ∧
      ∀ m < w n, x ∉ p '' (cylinder w n ∩ (· n) ⁻¹' {m}) := by
  have hleast := (TauCeti.isLeast_image_toLex_iff (F := p ⁻¹' {x}) hβx).1 hβ n
  rw [mem_cylinder_iff_eq.1 hw] at hleast
  -- the `n`-th coordinates of the points of the fibre in the cylinder of `w`
  have hmem : ∀ m, m ∈ (· n) '' (p ⁻¹' {x} ∩ cylinder w n) ↔
      x ∈ p '' (cylinder w n ∩ (· n) ⁻¹' {m}) := fun m =>
    ⟨fun ⟨γ, ⟨hγx, hγw⟩, hγm⟩ => ⟨γ, ⟨hγw, hγm⟩, hγx⟩,
      fun ⟨γ, ⟨hγw, hγm⟩, hγx⟩ => ⟨γ, ⟨hγx, hγw⟩, hγm⟩⟩
  simp only [← hmem]
  refine ⟨fun h => ⟨h ▸ hleast.1, fun m hm hm' => (hm.trans_le (h ▸ hleast.2 hm')).false⟩,
    fun ⟨h, h'⟩ => ?_⟩
  by_contra hne
  exact h' (β n) (lt_of_le_of_ne (hleast.2 h) hne) hleast.1

/-- If `s x` is the lexicographically least point of the fibre of the continuous map `p` over each
point `x` of its range, then the points `x` of the range for which `s x` lies in a given cylinder
form a measurable set for the σ-algebra generated by analytic sets. -/
private theorem measurableSet_range_inter_preimage_cylinder (hp : Continuous p)
    (hs : ∀ x ∈ range p, p (s x) = x ∧ IsLeast (toLex '' (p ⁻¹' {x})) (toLex (s x)))
    (w : ℕ → ℕ) (n : ℕ) :
    MeasurableSet[MeasurableSpace.generateFrom {T : Set X | AnalyticSet T}]
      (range p ∩ s ⁻¹' cylinder w n) := by
  induction n with
  | zero =>
    simpa only [cylinder_zero, preimage_univ, inter_univ] using
      MeasurableSpace.measurableSet_generateFrom (analyticSet_range_of_polishSpace hp)
  | succ n ih =>
    have han (m : ℕ) : MeasurableSet[MeasurableSpace.generateFrom {T : Set X | AnalyticSet T}]
        (p '' (cylinder w n ∩ (· n) ⁻¹' {m})) :=
      MeasurableSpace.measurableSet_generateFrom <|
        ((isOpen_cylinder (E := fun _ => ℕ) w n).inter
          ((isOpen_discrete {m}).preimage (continuous_apply n))).analyticSet_image hp
    have hsucc (β : ℕ → ℕ) : β ∈ cylinder w (n + 1) ↔ β ∈ cylinder w n ∧ β n = w n := by
      simp only [mem_cylinder_iff, Nat.forall_lt_succ_right]
    have heq : range p ∩ s ⁻¹' cylinder w (n + 1) = (range p ∩ s ⁻¹' cylinder w n) ∩
        (p '' (cylinder w n ∩ (· n) ⁻¹' {w n}) ∩
          ⋂ m, ⋂ (_ : m < w n), (p '' (cylinder w n ∩ (· n) ⁻¹' {m}))ᶜ) := by
      ext x
      simp only [mem_inter_iff, mem_preimage, mem_iInter, mem_compl_iff, hsucc]
      refine ⟨fun ⟨hx, hsx, hsxn⟩ => ⟨⟨hx, hsx⟩, ?_⟩, fun ⟨⟨hx, hsx⟩, h⟩ => ⟨hx, hsx, ?_⟩⟩
      · exact (apply_eq_iff_mem_image_cylinder (hs x hx).1 (hs x hx).2 hsx).1 hsxn
      · exact (apply_eq_iff_mem_image_cylinder (hs x hx).1 (hs x hx).2 hsx).2 h
    rw [heq]
    exact ih.inter ((han _).inter
      (MeasurableSet.iInter fun m => MeasurableSet.iInter fun _ => (han m).compl))

/-- **The Jankov–von Neumann uniformization theorem.** An analytic relation `R ⊆ X × Y`, with `X`
a T₁ space, has a uniformization `f : X → Y` which is measurable for the σ-algebra generated by the
analytic subsets of `X`: `(x, f x) ∈ R` for every `x` in the projection of `R`.

By `TauCeti.MeasureTheory.nullMeasurable_of_measurable_generateFrom_analyticSet`, such an `f` is
null-measurable for every s-finite measure on a metrizable `X`; see
`MeasureTheory.AnalyticSet.exists_measurable_ae_uniformization`. -/
theorem AnalyticSet.exists_measurable_uniformization [T1Space X] [MeasurableSpace Y]
    [BorelSpace Y] [Nonempty Y] {R : Set (X × Y)} (hR : AnalyticSet R) :
    ∃ f : X → Y, Measurable[MeasurableSpace.generateFrom {T : Set X | AnalyticSet T}] f ∧
      ∀ x ∈ Prod.fst '' R, (x, f x) ∈ R := by
  rw [AnalyticSet] at hR
  rcases hR with rfl | ⟨g, hg, rfl⟩
  · exact ⟨fun _ => Classical.arbitrary Y, measurable_const, by simp⟩
  classical
  -- the σ-algebra generated by analytic sets is the ambient one for the rest of the proof
  let : MeasurableSpace X := MeasurableSpace.generateFrom {T : Set X | AnalyticSet T}
  set p : (ℕ → ℕ) → X := fun β => (g β).1
  have hp : Continuous p := hg.fst
  -- over each point `x` of the range of `p`, the lexicographically least point of the fibre
  have hchoice (x : X) : ∃ β : ℕ → ℕ,
      (x ∈ range p → p β = x ∧ IsLeast (toLex '' (p ⁻¹' {x})) (toLex β)) ∧
        (x ∉ range p → β = 0) := by
    by_cases hx : x ∈ range p
    · obtain ⟨β, hβ, hleast⟩ := (isClosed_singleton.preimage hp).exists_isLeast_image_toLex
        (preimage_singleton_nonempty.2 hx)
      exact ⟨β, fun _ => ⟨hβ, hleast⟩, fun h => (h hx).elim⟩
    · exact ⟨0, fun h => (hx h).elim, fun _ => rfl⟩
  choose s hs hs0 using hchoice
  have hrange : MeasurableSet (range p) :=
    MeasurableSpace.measurableSet_generateFrom (analyticSet_range_of_polishSpace hp)
  have hcyl := measurableSet_range_inter_preimage_cylinder hp hs
  -- each coordinate of `s` is measurable: over the range of `p` its level sets are countable
  -- unions of cylinder events, and off the range `s` vanishes
  have hs_meas : Measurable s := by
    refine measurable_pi_iff.2 fun k => measurable_to_countable' fun m => ?_
    have heq : (fun x => s x k) ⁻¹' {m} =
        (⋃ v : Fin k → ℕ,
          range p ∩ s ⁻¹' cylinder (fun i => if h : i < k then v ⟨i, h⟩ else m) (k + 1)) ∪
        ((range p)ᶜ ∩ {_x | (0 : ℕ) = m}) := by
      ext x
      by_cases hx : x ∈ range p
      · simp only [mem_preimage, mem_singleton_iff, mem_union, mem_iUnion, mem_inter_iff, hx,
          true_and, mem_compl_iff, not_true_eq_false, false_and, or_false, mem_cylinder_iff]
        refine ⟨fun h => ⟨fun i => s x i, fun i hi => ?_⟩,
          fun ⟨v, hv⟩ => by simpa using hv k k.lt_succ_self⟩
        rcases Nat.lt_succ_iff_lt_or_eq.1 hi with hi | rfl
        · simp [hi]
        · simp [h]
      · simp [hx, hs0 x hx, eq_comm]
    rw [heq]
    exact (MeasurableSet.iUnion fun v => hcyl _ _).union
      (hrange.compl.inter (MeasurableSet.const _))
  refine ⟨fun x => if x ∈ range p then (g (s x)).2 else Classical.arbitrary Y,
    Measurable.ite hrange (hg.snd.measurable.comp hs_meas) measurable_const, ?_⟩
  rintro _ ⟨_, ⟨β, rfl⟩, rfl⟩
  have hx : (g β).1 ∈ range p := ⟨β, rfl⟩
  simp only [hx, ↓reduceIte]
  exact ⟨s (g β).1, Prod.ext (hs _ hx).1 rfl⟩

/-- **Measurable uniformization almost everywhere.** Relative to an s-finite measure `μ` on a
metrizable space `X`, an analytic relation `R ⊆ X × Y` has a measurable uniformization at almost
every point of its projection: a `g : X → Y`, measurable for the given σ-algebra on `X` (which
contains the open sets, and is the Borel σ-algebra under `[BorelSpace X]`), with `(x, g x) ∈ R` for
`μ`-almost every `x` in the projection of `R`.

The function `g` depends on `μ`; a uniformization that works for every `μ` at once is
`MeasureTheory.AnalyticSet.exists_measurable_uniformization`, which is measurable only for the
σ-algebra generated by analytic sets. -/
theorem AnalyticSet.exists_measurable_ae_uniformization [TopologicalSpace.MetrizableSpace X]
    [MeasurableSpace X] [OpensMeasurableSpace X] [MeasurableSpace Y] [BorelSpace Y]
    [MeasurableSpace.CountablyGenerated Y] [Nonempty Y] {R : Set (X × Y)} (hR : AnalyticSet R)
    (μ : Measure X) [SFinite μ] :
    ∃ g : X → Y, Measurable g ∧ ∀ᵐ x ∂μ, x ∈ Prod.fst '' R → (x, g x) ∈ R := by
  obtain ⟨f, hf, hfR⟩ := hR.exists_measurable_uniformization
  have hf' : AEMeasurable f μ :=
    (TauCeti.MeasureTheory.nullMeasurable_of_measurable_generateFrom_analyticSet μ hf).aemeasurable
  refine ⟨hf'.mk f, hf'.measurable_mk, ?_⟩
  filter_upwards [hf'.ae_eq_mk] with x hx hxR
  rw [← hx]
  exact hfR x hxR

end Uniformization

end MeasureTheory
