/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.AlgebraicGeometry.Artinian
public import Mathlib.AlgebraicGeometry.Morphisms.FlatRank
public import Mathlib.AlgebraicGeometry.ZariskisMainTheorem
public import TauCeti.AlgebraicGeometry.EffectiveCartierDivisor.FinitePresentation
public import TauCeti.AlgebraicGeometry.EffectiveCartierDivisor.Relative
public import TauCeti.AlgebraicGeometry.Morphisms.RelativeDimension

/-!
# Finiteness of relative effective Cartier divisors on relative curves

Let `f : X ⟶ S` be locally of finite type with fibres of dimension at most one, for instance a
smooth relative curve, and let `D` be a relative effective Cartier divisor on `X` over `S`. Then
`D ⟶ S` is locally quasi-finite. By Zariski's main theorem, `D` is therefore finite over `S`
exactly when it is proper over `S`; in particular every relative effective Cartier divisor on a
proper relative curve is finite over the base. Finiteness is thus a consequence of properness and
not part of the definition of a relative effective Cartier divisor.

A finite relative effective Cartier divisor is flat over `S` by definition, and locally of finite
presentation over `S` when `X` is, so it is finite locally free over `S`. Its degree is the locally
constant rank `Scheme.Hom.finrank` of `D ⟶ S`.

The fibrewise input is absolute: on a locally Noetherian scheme of dimension at most one, an
effective Cartier divisor is locally Artinian. Locally its ring is `R ⧸ (a)` for a Noetherian ring
`R` of dimension at most one and a nonzerodivisor `a`, and `dim R ⧸ (a) + 1 ≤ dim R`. The fibre
of `D` over a point `s` of `S` is the divisor on the fibre `X_s` obtained by base change, which is
again effective Cartier because `D` is flat over `S`, so it is discrete and `D ⟶ S` has discrete
fibres.

## Main results

* `AlgebraicGeometry.Scheme.IdealSheafData.IsEffectiveCartier.isLocallyArtinian_subscheme`: an
  effective Cartier divisor on a locally Noetherian scheme of dimension at most one is locally
  Artinian.
* `AlgebraicGeometry.Scheme.IdealSheafData.IsRelativeEffectiveCartier.locallyQuasiFinite`: a
  relative effective Cartier divisor on a morphism locally of finite type of relative dimension at
  most one is locally quasi-finite over the base.
* `AlgebraicGeometry.Scheme.IdealSheafData.IsRelativeEffectiveCartier.isFinite_iff_isProper`: such
  a divisor is finite over the base if and only if it is proper over the base.
* `AlgebraicGeometry.Scheme.IdealSheafData.IsRelativeEffectiveCartier.isFinite`: on a proper
  morphism of relative dimension at most one, every relative effective Cartier divisor is finite
  over the base.
* `AlgebraicGeometry.Scheme.IdealSheafData.IsRelativeEffectiveCartier.isLocallyConstant_finrank`:
  the degree of a proper relative effective Cartier divisor on a morphism locally of finite
  presentation of relative dimension at most one is locally constant on the base.

## References

* N. M. Katz and B. Mazur, *Arithmetic Moduli of Elliptic Curves*, §1.2.
* [Stacks Project, Tag 02LS](https://stacks.math.columbia.edu/tag/02LS): a morphism is finite if
  and only if it is proper and locally quasi-finite, Mathlib's
  `AlgebraicGeometry.IsFinite.iff_isProper_and_locallyQuasiFinite`.
-/

public section

open CategoryTheory Limits

universe u

namespace AlgebraicGeometry.Scheme.IdealSheafData

variable {X S : Scheme.{u}} {I : X.IdealSheafData}

/-- **An effective Cartier divisor on a curve is zero-dimensional.** On a locally Noetherian
scheme of dimension at most one, the closed subscheme of an effective Cartier divisor is locally
Artinian, so in particular it is a discrete topological space. -/
theorem IsEffectiveCartier.isLocallyArtinian_subscheme [IsLocallyNoetherian X]
    (hX : topologicalKrullDim X ≤ 1) (hI : I.IsEffectiveCartier) :
    IsLocallyArtinian I.subscheme := by
  -- The subscheme is covered by the preimages of the affine opens `U` of `X` on which `I` is
  -- generated by a nonzerodivisor `a`, with rings of sections `Γ(X, U) ⧸ (a)`.
  let ι := {U : X.affineOpens // ∃ a, IsSMulRegular Γ(X, U) a ∧ I.ideal U = Ideal.span {a}}
  refine (isLocallyArtinian_iff_of_isOpenCover (U := fun U : ι ↦ I.subschemeι ⁻¹ᵁ U.1.1) ?_
    fun U ↦ U.1.2.preimage _).mpr ?_
  · refine .mk <| eq_top_iff.mpr fun x _ ↦ TopologicalSpace.Opens.mem_iSup.mpr ?_
    obtain ⟨U, hxU, a, ha, hUa⟩ := (isEffectiveCartier_iff I).mp hI (I.subschemeι x)
    exact ⟨⟨U, a, ha, hUa⟩, hxU⟩
  rintro ⟨U, a, ha, hUa⟩
  have : IsNoetherianRing Γ(X, U) := IsLocallyNoetherian.component_noetherian U
  have hdim : ringKrullDim Γ(X, U) ≤ 1 := by
    refine le_trans ?_ hX
    rw [← PrimeSpectrum.topologicalKrullDim_eq_ringKrullDim Γ(X, U)]
    -- The underlying space of `Spec Γ(X, U)` is `PrimeSpectrum Γ(X, U)` by definition.
    change topologicalKrullDim (Spec Γ(X, U)) ≤ _
    rw [← IsHomeomorph.topologicalKrullDim_eq _ U.2.isoSpec.hom.homeomorph.isHomeomorph]
    exact topologicalKrullDim_subspace_le X U
  -- `Γ(X, U) ⧸ (a)` is Noetherian of dimension at most `dim Γ(X, U) - 1 ≤ 0`, hence Artinian.
  have hquot := ringKrullDim_quotient_succ_le_of_nonZeroDivisor
    (isLeftRegular_iff_isRegular.mp ha.isLeftRegular).mem_nonZeroDivisors
  have : IsArtinianRing (Γ(X, U) ⧸ I.ideal U) := by
    rw [hUa, isArtinianRing_iff_krullDimLE_zero, Ring.KrullDimLE, Order.krullDimLE_iff,
      ← ringKrullDim]
    exact ENat.WithBot.add_le_add_natCast_right_iff (c := 1).mp (mod_cast hquot.trans hdim)
  exact (I.subschemeObjIso U).commRingCatIsoToRingEquiv.symm.surjective.isArtinianRing

/-- **Relative effective Cartier divisors on relative curves are locally quasi-finite.** If
`f : X ⟶ S` is locally of finite type with fibres of dimension at most one, then the closed
subscheme of a relative effective Cartier divisor on `X` over `S` is locally quasi-finite over
`S`. -/
theorem IsRelativeEffectiveCartier.locallyQuasiFinite {f : X ⟶ S} [LocallyOfFiniteType f]
    [TauCeti.AlgebraicGeometry.RelativeDimensionLE 1 f] (hI : I.IsRelativeEffectiveCartier f) :
    LocallyQuasiFinite (I.subschemeι ≫ f) := by
  refine .of_fiberToSpecResidueField _ fun s ↦ ?_
  -- The fibre `X_s` of `f` over `s` is locally Noetherian of dimension at most one, and the base
  -- change of `I` to it is effective Cartier, so its closed subscheme is locally Artinian.
  -- The fibres are written as pullbacks, since instances do not unfold `Scheme.Hom.fiber`.
  have : IsLocallyNoetherian (pullback f (S.fromSpecResidueField s)) :=
    LocallyOfFiniteType.isLocallyNoetherian (pullback.snd f (S.fromSpecResidueField s))
  have hdim : topologicalKrullDim ↥(pullback f (S.fromSpecResidueField s)) ≤ 1 :=
    TauCeti.AlgebraicGeometry.RelativeDimensionLE.topologicalKrullDim_fiber_le s
  have := (hI.comap (S.fromSpecResidueField s)).isEffectiveCartier.isLocallyArtinian_subscheme
    hdim
  -- That subscheme is the fibre of `I.subschemeι ≫ f` over `s`.
  have : IsLocallyArtinian (pullback (I.subschemeι ≫ f) (S.fromSpecResidueField s)) :=
    .of_isImmersion (I.comapIso _ ≪≫ pullbackSymmetry _ _ ≪≫
      pullbackRightPullbackFstIso f (S.fromSpecResidueField s) I.subschemeι).inv
  have : DiscreteTopology ((I.subschemeι ≫ f).fiber s) :=
    inferInstanceAs (DiscreteTopology ↥(pullback (I.subschemeι ≫ f) (S.fromSpecResidueField s)))
  have : LocallyOfFiniteType ((I.subschemeι ≫ f).fiberToSpecResidueField s) :=
    inferInstanceAs (LocallyOfFiniteType (pullback.snd _ _))
  exact locallyQuasiFinite_iff_isDiscrete_preimage_singleton.mpr fun _ ↦
    IsDiscrete.univ.mono (Set.subset_univ _)

/-- **A relative effective Cartier divisor on a relative curve is finite exactly when it is
proper.** If `f : X ⟶ S` is locally of finite type with fibres of dimension at most one, then the
closed subscheme of a relative effective Cartier divisor on `X` over `S` is finite over `S` if and
only if it is proper over `S`. -/
theorem IsRelativeEffectiveCartier.isFinite_iff_isProper {f : X ⟶ S} [LocallyOfFiniteType f]
    [TauCeti.AlgebraicGeometry.RelativeDimensionLE 1 f] (hI : I.IsRelativeEffectiveCartier f) :
    IsFinite (I.subschemeι ≫ f) ↔ IsProper (I.subschemeι ≫ f) := by
  have := hI.locallyQuasiFinite
  rw [IsFinite.iff_isProper_and_locallyQuasiFinite, and_iff_left this]

/-- **Relative effective Cartier divisors on proper relative curves are finite.** If `f : X ⟶ S`
is proper with fibres of dimension at most one, then the closed subscheme of every relative
effective Cartier divisor on `X` over `S` is finite over `S`. -/
theorem IsRelativeEffectiveCartier.isFinite {f : X ⟶ S} [IsProper f]
    [TauCeti.AlgebraicGeometry.RelativeDimensionLE 1 f] (hI : I.IsRelativeEffectiveCartier f) :
    IsFinite (I.subschemeι ≫ f) :=
  hI.isFinite_iff_isProper.mpr inferInstance

/-- **The degree of a relative effective Cartier divisor is locally constant.** If
`f : X ⟶ S` is locally of finite presentation with fibres of dimension at most one, and the closed
subscheme of a relative effective Cartier divisor on `X` over `S` is proper over `S`, then that
subscheme is finite locally free over `S`, and its rank `Scheme.Hom.finrank`, the degree of the
divisor, is a locally constant function on `S`. -/
theorem IsRelativeEffectiveCartier.isLocallyConstant_finrank {f : X ⟶ S}
    [LocallyOfFinitePresentation f] [TauCeti.AlgebraicGeometry.RelativeDimensionLE 1 f]
    [IsProper (I.subschemeι ≫ f)] (hI : I.IsRelativeEffectiveCartier f) :
    IsLocallyConstant (I.subschemeι ≫ f).finrank := by
  have := hI.isFinite_iff_isProper.mpr inferInstance
  have := hI.flat
  have := TauCeti.locallyOfFinitePresentation_subschemeι_comp_of_isEffectiveCartier
    hI.isEffectiveCartier (f := f)
  exact Scheme.Hom.isLocallyConstant_finrank _

end AlgebraicGeometry.Scheme.IdealSheafData
