/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Lie.Sl2
public import TauCeti.Algebra.Lie.GeneralLinear.Basic

/-!
# Basic theory of `sl₂` triples

Mathlib defines an abstract `sl₂` triple (`IsSl2Triple h e f`: the relations `⁅e, f⁆ = h`,
`⁅h, e⁆ = 2e`, `⁅h, f⁆ = -2f`, with `h ≠ 0`) and the whole primitive-vector calculus that rests on
it. This file adds three things Mathlib does not have.

The first is a supply of triples, none being exhibited in the special linear Lie algebra. For every
pair `i ≠ j` of indices, the matrix units

`e = Eᵢⱼ`, `f = Eⱼᵢ`, `h = Eᵢᵢ - Eⱼⱼ`

form an `sl₂` triple inside `LieAlgebra.SpecialLinear.sl n R`, over an arbitrary nontrivial
commutative ring. These are the triples attached to the roots of `sl n`, and for `n = 2` the triple
is the whole Lie algebra: `sl (Fin 2) R` is free of rank `3` on `e`, `f`, `h`, so the Lie subalgebra
`IsSl2Triple.toLieSubalgebra` generated by the standard triple is everything.

That last fact is what makes `sl (Fin 2) R` usable as *the* model `sl₂`: statements about a triple
`t` which are false for a triple sitting inside a bigger Lie algebra become correct once
`t.toLieSubalgebra R = ⊤`, and this file provides the model in which that hypothesis holds. For an
arbitrary triple, `IsSl2Triple.isSl2Triple_restrict` regards it inside the subalgebra it generates,
where
`IsSl2Triple.restrict_toLieSubalgebra_eq_top` supplies that hypothesis.

The second is the presentation of `sl₂` by its relations, for an arbitrary Lie algebra: a triple is
linearly independent, so a triple generating a Lie algebra is a basis of it, and three elements of
any Lie algebra obeying the same relations determine a homomorphism out of it. That is what carries
a representation of the model `sl₂` over to an abstract one, in
`TauCeti/Algebra/Lie/Sl2/Standard.lean`.

The third is perfectness of a Lie algebra generated by a triple, in the form the module theory
uses it: each of `h`, `2e` and `-2f` is a bracket of triple elements, so an action of the algebra
that composes to zero is already zero.

## Main results

* `TauCeti.isSl2Triple_single`: for `i ≠ j`, the matrix units `Eᵢⱼ`, `Eⱼᵢ` and `Eᵢᵢ - Eⱼⱼ` form an
  `sl₂` triple in `sl n R`. The three bracket relations are available separately as
  `TauCeti.lie_single_single_eq_singleSubSingle`, `TauCeti.lie_singleSubSingle_single` and
  `TauCeti.lie_singleSubSingle_single_swap`.
* `TauCeti.slFinTwoBasis`: the standard basis `(e, f, h)` of `sl (Fin 2) R`, obtained from the
  coordinate isomorphism `TauCeti.slFinTwoEquivFun` and identified vector by vector in
  `TauCeti.slFinTwoBasis_zero`, `TauCeti.slFinTwoBasis_one` and `TauCeti.slFinTwoBasis_two`, with
  `TauCeti.finrank_sl_fin_two` reading off the rank `3`.
* `TauCeti.toLieSubalgebra_isSl2Triple_single_eq_top`: in `sl (Fin 2) R` the subalgebra generated
  by a standard triple is the whole of `sl (Fin 2) R`. The underlying expansion of an arbitrary
  element in the triple is `TauCeti.eq_smul_single_add_smul_single_add_smul_singleSubSingle`.
* `IsSl2Triple.isSl2Triple_restrict`: an arbitrary triple regarded inside the subalgebra that it
  generates.
* `IsSl2Triple.map`: the image of a triple under a Lie algebra homomorphism that does not kill its
  Cartan element is a triple.
* `IsSl2Triple.lieSubmoduleOfStable`: a submodule stable under the raising and lowering elements of
  a triple is a Lie submodule over the subalgebra they generate.
* `TauCeti.lieHomOfSl2Basis`: from a basis obeying the `sl₂` relations, three elements of another
  Lie algebra obeying the same relations determine a homomorphism, sending the basis to them
  (`TauCeti.lieHomOfSl2Basis_apply`).
* `TauCeti.linearIndependent_isSl2Triple`: the three elements of an `sl₂` triple are linearly
  independent, being eigenvectors of `ad h` for the eigenvalues `2`, `-2` and `0`, and
  `TauCeti.basisOfIsSl2Triple`: a generating `sl₂` triple, as a basis of the Lie algebra it
  generates.
* `TauCeti.lie_eq_zero_of_lie_lie_eq_zero`: a Lie algebra generated by an `sl₂` triple is perfect,
  so an action of it that composes to zero is zero.
* `IsSl2Triple.eq_two_of_lie_h_e_eq_smul`: the raising eigenvalue of an `sl₂` triple is
  forced to be two in a torsion-free module.
* `IsSl2Triple.rescale`: rescaling the raising element by a unit and the lowering element by its
  inverse preserves an `sl₂` triple.

## Implementation notes

The special linear results are stated over an arbitrary commutative ring `R`; nontriviality of `R`
is needed only where `h ≠ 0` is claimed, and `StrongRankCondition R` only for the rank computation.
Mathlib does not register `LieRing.ofAssociativeRing` as a global instance, so, as in
`Mathlib/Algebra/Lie/Classical.lean`, it is a local instance here.

Linear independence of a triple is the eigenvector argument of
`Module.End.eigenvectors_linearIndependent'`, so it asks what that theorem asks — a domain of
characteristic zero and a torsion-free Lie algebra — rather than a field: the eigenvalues `2`, `-2`
and `0` need only be distinct, not invertible. The presentation `TauCeti.lieHomOfSl2Basis` needs
neither, being a bilinearity argument over an arbitrary commutative ring.

The `sl (Fin 2) R` results are stated for an arbitrary pair `i ≠ j` of indices in `Fin 2`, not just
for `(0, 1)`: the opposite pair gives the opposite triple `(-h, f, e)`, and both are standard.

## References

This is the concrete input to Layer 0 of
`TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md`, whose worked `sl₂` is
*"`LieAlgebra.SpecialLinear.sl (Fin 2) K` with its standard triple"*, and whose classification
targets carry the hypothesis `htop : t.toLieSubalgebra K = ⊤` that
`TauCeti.toLieSubalgebra_isSl2Triple_single_eq_top` discharges for that model.
-/

public section

namespace TauCeti

open Matrix LieAlgebra Module

attribute [local instance 100] LieRing.ofAssociativeRing

/-- If the Cartan element of an `sl₂` triple acts on its raising element by a scalar, that scalar
is two, provided scalar multiplication on the ambient Lie algebra has no zero divisors. -/
theorem _root_.IsSl2Triple.eq_two_of_lie_h_e_eq_smul {S H : Type*} [CommRing S] [LieRing H]
    [LieAlgebra S H] [NoZeroSMulDivisors S H] {h e f : H} (t : _root_.IsSl2Triple h e f) {a : S}
    (ha : ⁅h, e⁆ = a • e) : a = 2 := by
  have hzero : (a - 2) • e = 0 := by
    rw [sub_smul, ← ha, ← t.lie_h_e_smul S, sub_self]
  exact sub_eq_zero.mp
    ((NoZeroSMulDivisors.eq_zero_or_eq_zero_of_smul_eq_zero hzero).resolve_right t.e_ne_zero)

/-- **Rescaling an `sl₂` triple by a unit of the base ring.** Scaling the raising element by `c`
and the lowering element by `c⁻¹` leaves their bracket, hence the Cartan element, unchanged. -/
theorem _root_.IsSl2Triple.rescale {S L : Type*} [CommRing S] [LieRing L] [LieAlgebra S L]
    {h e f : L} (t : IsSl2Triple h e f) (c : Sˣ) :
    IsSl2Triple h ((c : S) • e) (((c⁻¹ : Sˣ) : S) • f) where
  h_ne_zero := t.h_ne_zero
  lie_e_f := by
    rw [smul_lie, lie_smul, t.lie_e_f, smul_smul, Units.mul_inv, one_smul]
  lie_h_e_nsmul := by rw [lie_smul, t.lie_h_e_nsmul, smul_comm]
  lie_h_f_nsmul := by rw [lie_smul, t.lie_h_f_nsmul, smul_neg, smul_comm]

variable (R : Type*) [CommRing R] {n : Type*} [DecidableEq n] [Fintype n]

/-! ### The standard triples of `sl n R` -/

section Triple

variable {R} {i j : n}

/-- `⁅Eᵢⱼ, Eⱼᵢ⁆ = Eᵢᵢ - Eⱼⱼ` in `sl n R`: the defining relation `⁅e, f⁆ = h` of the standard
`sl₂` triple. -/
@[simp]
theorem lie_single_single_eq_singleSubSingle (hij : i ≠ j) (c : R) :
    ⁅SpecialLinear.single i j hij c, SpecialLinear.single j i hij.symm (1 : R)⁆
      = SpecialLinear.singleSubSingle i j c := by
  ext : 1
  rw [SpecialLinear.sl_bracket, SpecialLinear.val_single, SpecialLinear.val_single,
    SpecialLinear.val_singleSubSingle, ← LieRing.of_associative_ring_bracket,
    lie_single_single_eq_sub]

/-- `⁅Eᵢᵢ - Eⱼⱼ, Eᵢⱼ⁆ = 2 Eᵢⱼ` in `sl n R`: the relation `⁅h, e⁆ = 2e` of the standard `sl₂`
triple. -/
@[simp]
theorem lie_singleSubSingle_single (hij : i ≠ j) (c : R) :
    ⁅SpecialLinear.singleSubSingle i j (1 : R), SpecialLinear.single i j hij c⁆
      = (2 : R) • SpecialLinear.single i j hij c := by
  ext : 1
  rw [SpecialLinear.sl_bracket]
  simp [sub_mul, mul_sub, hij.symm, two_smul]

/-- Swapping the two indices of `Eᵢᵢ - Eⱼⱼ` negates it. -/
@[simp]
theorem neg_singleSubSingle (i j : n) (c : R) :
    -SpecialLinear.singleSubSingle i j c = SpecialLinear.singleSubSingle j i c := by
  ext : 1
  simp [neg_sub]

/-- `⁅Eᵢᵢ - Eⱼⱼ, Eⱼᵢ⁆ = -2 Eⱼᵢ` in `sl n R`: the relation `⁅h, f⁆ = -2f` of the standard `sl₂`
triple. It is the previous relation for the opposite pair of indices, since swapping them negates
`h`. -/
@[simp]
theorem lie_singleSubSingle_single_swap (hij : i ≠ j) (c : R) :
    ⁅SpecialLinear.singleSubSingle i j (1 : R), SpecialLinear.single j i hij.symm c⁆
      = -((2 : R) • SpecialLinear.single j i hij.symm c) := by
  rw [← neg_singleSubSingle j i, neg_lie, lie_singleSubSingle_single hij.symm]

/-- `Eᵢᵢ (c) - Eⱼⱼ (c)` is nonzero in `sl n R` when `i ≠ j` and `c ≠ 0`: its `(i, i)` entry is
`c`. -/
theorem singleSubSingle_ne_zero (hij : i ≠ j) {c : R} (hc : c ≠ 0) :
    SpecialLinear.singleSubSingle i j c ≠ 0 := fun h => hc <| by
  have := congr_fun (congr_fun (congr_arg Subtype.val h) i) i
  simpa [Matrix.single_apply, hij, hij.symm] using this

/-- **The standard `sl₂` triple of `sl n R`.** For `i ≠ j` the matrix units `e = Eᵢⱼ`, `f = Eⱼᵢ`
and `h = Eᵢᵢ - Eⱼⱼ` satisfy the `sl₂` relations. These are the concrete counterparts of the triples
that `LieAlgebra.IsKilling.exists_isSl2Triple_of_weight_isNonZero` attaches to a root of a
Killing-semisimple Lie algebra: `e` and `f` span the root spaces of `εᵢ - εⱼ` and of its negative,
and `h` is the corresponding coroot. -/
theorem isSl2Triple_single [Nontrivial R] (hij : i ≠ j) :
    IsSl2Triple (SpecialLinear.singleSubSingle i j (1 : R))
      (SpecialLinear.single i j hij 1) (SpecialLinear.single j i hij.symm 1) where
  h_ne_zero := singleSubSingle_ne_zero hij one_ne_zero
  lie_e_f := lie_single_single_eq_singleSubSingle hij 1
  lie_h_e_nsmul := by
    rw [lie_singleSubSingle_single hij, two_smul, two_smul]
  lie_h_f_nsmul := by
    rw [lie_singleSubSingle_single_swap hij, two_smul, two_smul]

end Triple

/-! ### `sl (Fin 2) R` as the model `sl₂` -/

section FinTwo

variable {R}

/-- The bottom-right entry of a trace-zero `2 × 2` matrix is minus its top-left entry. -/
@[simp]
theorem val_one_one_eq_neg_val_zero_zero (A : SpecialLinear.sl (Fin 2) R) :
    A.val 1 1 = -A.val 0 0 := by
  have h : A.val.trace = 0 := A.2
  rw [Matrix.trace_fin_two] at h
  linear_combination h

variable (R)

/-- The coordinates of a trace-zero `2 × 2` matrix in the standard basis `(e, f, h)`, namely
`A ↦ (A 0 1, A 1 0, A 0 0)`. The inverse rebuilds `A` from them, using that the trace-zero
condition forces `A 1 1 = -A 0 0`. -/
def slFinTwoEquivFun : SpecialLinear.sl (Fin 2) R ≃ₗ[R] (Fin 3 → R) where
  toFun A := ![A.val 0 1, A.val 1 0, A.val 0 0]
  map_add' A B := by ext k; fin_cases k <;> simp
  map_smul' c A := by ext k; fin_cases k <;> simp
  invFun v := ⟨!![v 2, v 0; v 1, -v 2], by
    have h : (!![v 2, v 0; v 1, -v 2] : Matrix (Fin 2) (Fin 2) R).trace = 0 := by simp
    exact h⟩
  left_inv A := by
    refine Subtype.ext ?_
    ext a b
    fin_cases a <;> fin_cases b <;> simp
  right_inv v := by ext k; fin_cases k <;> simp

variable {R}

@[simp]
theorem slFinTwoEquivFun_apply (A : SpecialLinear.sl (Fin 2) R) :
    slFinTwoEquivFun R A = ![A.val 0 1, A.val 1 0, A.val 0 0] := by rfl

@[simp]
theorem slFinTwoEquivFun_symm_apply (v : Fin 3 → R) :
    ((slFinTwoEquivFun R).symm v).val = !![v 2, v 0; v 1, -v 2] := by rfl

variable (R)

/-- **The standard basis of `sl₂`.** The matrix units `e = E₀₁`, `f = E₁₀` and `h = E₀₀ - E₁₁` are
a basis of `sl (Fin 2) R`; see `TauCeti.slFinTwoBasis_apply`. -/
noncomputable def slFinTwoBasis : Basis (Fin 3) R (SpecialLinear.sl (Fin 2) R) :=
  Basis.ofEquivFun (slFinTwoEquivFun R)

/-- The three vectors of the standard basis of `sl (Fin 2) R`, as matrices: index `0` is the
raising element `e = E₀₁`, index `1` the lowering element `f = E₁₀`, and index `2` the semisimple
element `h = E₀₀ - E₁₁`. The individual cases, phrased inside `sl (Fin 2) R` rather than in
matrices, are `TauCeti.slFinTwoBasis_zero`, `TauCeti.slFinTwoBasis_one` and
`TauCeti.slFinTwoBasis_two`. -/
theorem slFinTwoBasis_apply (k : Fin 3) :
    (slFinTwoBasis R k).val =
      ![Matrix.single 0 1 1, Matrix.single 1 0 1,
        Matrix.single 0 0 1 - Matrix.single 1 1 (1 : R)] k := by
  rw [slFinTwoBasis, Basis.coe_ofEquivFun]
  fin_cases k <;> · ext a b; fin_cases a <;> fin_cases b <;> simp

/-- The first standard basis vector of `sl₂` is the raising element `e = E₀₁`. -/
@[simp]
theorem slFinTwoBasis_zero : slFinTwoBasis R 0 = SpecialLinear.single 0 1 zero_ne_one 1 :=
  Subtype.ext <| by simpa using slFinTwoBasis_apply R 0

/-- The second standard basis vector of `sl₂` is the lowering element `f = E₁₀`. -/
@[simp]
theorem slFinTwoBasis_one : slFinTwoBasis R 1 = SpecialLinear.single 1 0 one_ne_zero 1 :=
  Subtype.ext <| by simpa using slFinTwoBasis_apply R 1

/-- The third standard basis vector of `sl₂` is the semisimple element `h = E₀₀ - E₁₁`. -/
@[simp]
theorem slFinTwoBasis_two : slFinTwoBasis R 2 = SpecialLinear.singleSubSingle 0 1 (1 : R) :=
  Subtype.ext <| by simpa using slFinTwoBasis_apply R 2

instance instModuleFreeSlFinTwo : Module.Free R (SpecialLinear.sl (Fin 2) R) :=
  Module.Free.of_basis (slFinTwoBasis R)

instance instModuleFiniteSlFinTwo : Module.Finite R (SpecialLinear.sl (Fin 2) R) :=
  Module.Finite.of_basis (slFinTwoBasis R)

/-- `sl₂` is three-dimensional. -/
theorem finrank_sl_fin_two [StrongRankCondition R] :
    finrank R (SpecialLinear.sl (Fin 2) R) = 3 := by
  simpa using finrank_eq_card_basis (slFinTwoBasis R)

variable {R}

/-- Every element of `sl (Fin 2) R` is a combination of a standard triple: the coefficients are
read off from the entries, using `A 1 1 = -A 0 0`. -/
theorem eq_smul_single_add_smul_single_add_smul_singleSubSingle
    (A : SpecialLinear.sl (Fin 2) R) {i j : Fin 2} (hij : i ≠ j) :
    A = A.val i j • SpecialLinear.single i j hij 1 + A.val j i • SpecialLinear.single j i hij.symm 1
      + A.val i i • SpecialLinear.singleSubSingle i j (1 : R) := by
  have key : ∀ p q : Fin 2, p ≠ q → (p = 0 ∧ q = 1) ∨ (p = 1 ∧ q = 0) := by decide
  refine Subtype.ext ?_
  ext a b
  obtain ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ := key i j hij <;>
    fin_cases a <;> fin_cases b <;> simp

/-- **The standard triple generates `sl₂`.** In `sl (Fin 2) R` the Lie subalgebra spanned by a
standard `sl₂` triple is everything, so `sl (Fin 2) R` is the model in which the classification
hypothesis `t.toLieSubalgebra R = ⊤` holds. -/
theorem toLieSubalgebra_isSl2Triple_single_eq_top [Nontrivial R] {i j : Fin 2} (hij : i ≠ j) :
    (isSl2Triple_single (R := R) hij).toLieSubalgebra R = ⊤ := by
  refine eq_top_iff.mpr fun A _ => ?_
  rw [IsSl2Triple.mem_toLieSubalgebra_iff, lie_single_single_eq_singleSubSingle hij]
  exact ⟨A.val i j, A.val j i, A.val i i,
    eq_smul_single_add_smul_single_add_smul_singleSubSingle A hij⟩

end FinTwo

/-! ### Homomorphisms determined by the `sl₂` relations -/

section Presentation

variable {K : Type*} [CommRing K] {L L' : Type*} [LieRing L] [LieAlgebra K L] [LieRing L']
  [LieAlgebra K L']

/-- **The `sl₂` relations determine a homomorphism.** If a basis `(b₀, b₁, b₂)` of a Lie algebra
`L` obeys the `sl₂` relations, then any three elements `E`, `F`, `H` of a Lie algebra `L'` obeying
the same relations determine a Lie algebra homomorphism `L →ₗ⁅K⁆ L'` carrying the basis to them
(`TauCeti.lieHomOfSl2Basis_apply`). Bracket preservation is bilinear, so it is enough to check it
on the basis, where it is the nine brackets of the relations. -/
noncomputable def lieHomOfSl2Basis (b : Basis (Fin 3) K L)
    (hb_ef : ⁅b 0, b 1⁆ = b 2) (hb_he : ⁅b 2, b 0⁆ = (2 : K) • b 0)
    (hb_hf : ⁅b 2, b 1⁆ = -((2 : K) • b 1)) (E F H : L') (hef : ⁅E, F⁆ = H)
    (hhe : ⁅H, E⁆ = (2 : K) • E) (hhf : ⁅H, F⁆ = -((2 : K) • F)) : L →ₗ⁅K⁆ L' :=
  { b.constr K ![E, F, H] with
    map_lie' := by
      set φ := b.constr K ![E, F, H] with hφ
      have h0 : φ (b 0) = E := by rw [hφ, Basis.constr_basis]; rfl
      have h1 : φ (b 1) = F := by rw [hφ, Basis.constr_basis]; rfl
      have h2 : φ (b 2) = H := by rw [hφ, Basis.constr_basis]; rfl
      -- The nine brackets of basis vectors, in the source and in the target; each triple of
      -- relations determines the three brackets taken in the opposite order.
      have hb_fe : ⁅b 1, b 0⁆ = -b 2 := by rw [← hb_ef, lie_skew]
      have hb_eh : ⁅b 0, b 2⁆ = -((2 : K) • b 0) := by rw [← hb_he, lie_skew]
      have hb_fh : ⁅b 1, b 2⁆ = (2 : K) • b 1 := by
        rw [← neg_neg ((2 : K) • b 1), ← hb_hf, lie_skew]
      have hfe : ⁅F, E⁆ = -H := by rw [← hef, lie_skew]
      have heh : ⁅E, H⁆ = -((2 : K) • E) := by rw [← hhe, lie_skew]
      have hfh : ⁅F, H⁆ = (2 : K) • F := by rw [← neg_neg ((2 : K) • F), ← hhf, lie_skew]
      have key : ∀ i j : Fin 3, φ ⁅b i, b j⁆ = ⁅φ (b i), φ (b j)⁆ := by
        have hcases : ∀ k : Fin 3, k = 0 ∨ k = 1 ∨ k = 2 := by decide
        intro i j
        rcases hcases i with rfl | rfl | rfl <;> rcases hcases j with rfl | rfl | rfl <;>
          simp only [hb_ef, hb_fe, hb_he, hb_hf, hb_eh, hb_fh, h0, h1, h2, lie_self, map_zero,
            map_neg, map_smul, hef, hfe, hhe, hhf, heh, hfh]
      -- Both sides of `map_lie'` are bilinear, so agreeing on the basis suffices.
      have hB : LinearMap.compr₂ (LieAlgebra.ad K L).toLinearMap φ
          = LinearMap.compl₂ ((LieAlgebra.ad K L').toLinearMap ∘ₗ φ) φ :=
        LinearMap.ext_basis b b (by simpa using key)
      intro x y
      simpa using DFunLike.congr_fun (DFunLike.congr_fun hB x) y }

/-- The homomorphism presented by the `sl₂` relations sends the basis to the three chosen
elements. -/
theorem lieHomOfSl2Basis_apply (b : Basis (Fin 3) K L)
    (hb_ef : ⁅b 0, b 1⁆ = b 2) (hb_he : ⁅b 2, b 0⁆ = (2 : K) • b 0)
    (hb_hf : ⁅b 2, b 1⁆ = -((2 : K) • b 1)) (E F H : L') (hef : ⁅E, F⁆ = H)
    (hhe : ⁅H, E⁆ = (2 : K) • E) (hhf : ⁅H, F⁆ = -((2 : K) • F)) (i : Fin 3) :
    lieHomOfSl2Basis b hb_ef hb_he hb_hf E F H hef hhe hhf (b i) = ![E, F, H] i :=
  Basis.constr_basis b K ![E, F, H] i

end Presentation

/-! ### A triple inside the subalgebra it generates -/

end TauCeti

variable {K : Type*} [CommRing K] {L : Type*} [LieRing L] [LieAlgebra K L] {h e f : L}

namespace IsSl2Triple

/-- An `sl₂` triple is carried to an `sl₂` triple by any Lie algebra homomorphism that does not
kill the Cartan element. The three bracket relations hold for any homomorphism, so `φ h ≠ 0` is
the only hypothesis needed; an injective `φ` supplies it from `t.h_ne_zero`. -/
theorem map {L' : Type*} [LieRing L'] [LieAlgebra K L'] (t : IsSl2Triple h e f)
    (φ : L →ₗ⁅K⁆ L') (hφ : φ h ≠ 0) : IsSl2Triple (φ h) (φ e) (φ f) where
  h_ne_zero := hφ
  lie_e_f := by rw [← LieHom.map_lie, t.lie_e_f]
  lie_h_e_nsmul := by rw [← LieHom.map_lie, t.lie_h_e_nsmul, map_nsmul]
  lie_h_f_nsmul := by rw [← LieHom.map_lie, t.lie_h_f_nsmul, map_neg, map_nsmul]

/-- The raising element of an `sl₂` triple belongs to the Lie subalgebra generated by the
triple. -/
theorem e_mem_toLieSubalgebra (t : IsSl2Triple h e f) : e ∈ t.toLieSubalgebra K :=
  IsSl2Triple.mem_toLieSubalgebra_iff.2 ⟨1, 0, 0, by simp⟩

/-- The lowering element of an `sl₂` triple belongs to the Lie subalgebra generated by the
triple. -/
theorem f_mem_toLieSubalgebra (t : IsSl2Triple h e f) : f ∈ t.toLieSubalgebra K :=
  IsSl2Triple.mem_toLieSubalgebra_iff.2 ⟨0, 1, 0, by simp⟩

/-- The Cartan element of an `sl₂` triple belongs to the Lie subalgebra generated by the
triple. -/
theorem h_mem_toLieSubalgebra (t : IsSl2Triple h e f) : h ∈ t.toLieSubalgebra K :=
  IsSl2Triple.mem_toLieSubalgebra_iff.2 ⟨0, 0, 1, by simp [t.lie_e_f]⟩

/-- An `sl₂` triple, regarded inside the Lie subalgebra that it generates. -/
theorem isSl2Triple_restrict (t : IsSl2Triple h e f) :
    IsSl2Triple (⟨h, t.h_mem_toLieSubalgebra⟩ : t.toLieSubalgebra K)
      ⟨e, t.e_mem_toLieSubalgebra⟩ ⟨f, t.f_mem_toLieSubalgebra⟩ where
  h_ne_zero hc := t.h_ne_zero (by simpa using congrArg Subtype.val hc)
  lie_e_f := Subtype.ext (by simpa using t.lie_e_f)
  lie_h_e_nsmul := Subtype.ext (by simpa using t.lie_h_e_nsmul)
  lie_h_f_nsmul := Subtype.ext (by simpa using t.lie_h_f_nsmul)

/-- A triple regarded inside the subalgebra that it generates still generates the whole
subalgebra. -/
@[simp]
theorem restrict_toLieSubalgebra_eq_top (t : IsSl2Triple h e f) :
    (t.isSl2Triple_restrict (K := K)).toLieSubalgebra K = ⊤ := by
  refine eq_top_iff.2 fun x _ ↦ ?_
  obtain ⟨c₁, c₂, c₃, hx⟩ := IsSl2Triple.mem_toLieSubalgebra_iff.1 x.2
  exact IsSl2Triple.mem_toLieSubalgebra_iff.2
    ⟨c₁, c₂, c₃, Subtype.ext (by simpa using hx)⟩

variable {M : Type*} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]

/-- **A submodule stable under the raising and lowering elements of an `sl₂` triple is a Lie
submodule over the subalgebra they generate.** Every element of `t.toLieSubalgebra K` is a
combination `c₁ • e + c₂ • f + c₃ • h`, and the Cartan element is `h = ⁅e, f⁆`, so stability under
`e` and `f` is all that has to be checked.

The underlying submodule is `S` itself, recorded in
`IsSl2Triple.lieSubmoduleOfStable_toSubmodule`, and membership in
`IsSl2Triple.mem_lieSubmoduleOfStable`. -/
def lieSubmoduleOfStable (t : IsSl2Triple h e f) (S : Submodule K M)
    (he : ∀ m ∈ S, ⁅e, m⁆ ∈ S) (hf : ∀ m ∈ S, ⁅f, m⁆ ∈ S) :
    LieSubmodule K (t.toLieSubalgebra K) M where
  __ := S
  lie_mem := by
    have hh : ∀ m ∈ S, ⁅h, m⁆ ∈ S := fun m hm ↦ by
      rw [← t.lie_e_f, lie_lie]
      exact S.sub_mem (he _ (hf m hm)) (hf _ (he m hm))
    rintro ⟨x, hx⟩ m hm
    obtain ⟨c₁, c₂, c₃, rfl⟩ := IsSl2Triple.mem_toLieSubalgebra_iff.1 hx
    rw [LieSubalgebra.coe_bracket_of_module, add_lie, add_lie, smul_lie, smul_lie, smul_lie,
      t.lie_e_f]
    exact S.add_mem (S.add_mem (S.smul_mem _ (he m hm)) (S.smul_mem _ (hf m hm)))
      (S.smul_mem _ (hh m hm))

@[simp]
theorem lieSubmoduleOfStable_toSubmodule (t : IsSl2Triple h e f) (S : Submodule K M)
    (he : ∀ m ∈ S, ⁅e, m⁆ ∈ S) (hf : ∀ m ∈ S, ⁅f, m⁆ ∈ S) :
    (t.lieSubmoduleOfStable S he hf).toSubmodule = S := by
  simp only [lieSubmoduleOfStable]

/-- Membership in `IsSl2Triple.lieSubmoduleOfStable` is membership in the submodule it is built
from. This is the abstraction boundary for membership: a consumer should rewrite with this lemma
rather than unfold the definition. -/
@[simp]
theorem mem_lieSubmoduleOfStable (t : IsSl2Triple h e f) (S : Submodule K M)
    (he : ∀ m ∈ S, ⁅e, m⁆ ∈ S) (hf : ∀ m ∈ S, ⁅f, m⁆ ∈ S) {m : M} :
    m ∈ t.lieSubmoduleOfStable S he hf ↔ m ∈ S :=
  Iff.rfl

end IsSl2Triple

namespace TauCeti

open Matrix LieAlgebra Module

/-! ### A generating triple as a basis -/

section GeneratingTriple

variable {K : Type*} [CommRing K] [IsDomain K] [CharZero K] {L : Type*} [LieRing L]
  [LieAlgebra K L] [Module.IsTorsionFree K L] {h e f : L}

/-- **An `sl₂` triple is linearly independent.** Its three elements are eigenvectors of `ad h` for
the eigenvalues `2`, `-2` and `0`, which are distinct in characteristic zero. -/
theorem linearIndependent_isSl2Triple (t : IsSl2Triple h e f) :
    LinearIndependent K ![e, f, h] := by
  refine (LieAlgebra.ad K L h).eigenvectors_linearIndependent' ![2, -2, 0] ?_ ![e, f, h]
    fun i => ?_
  · intro i j hij
    fin_cases i <;> fin_cases j <;> first | rfl | (exfalso; revert hij; norm_num)
  · have heig_e : (LieAlgebra.ad K L h).HasEigenvector 2 e :=
      ⟨Module.End.mem_eigenspace_iff.2 (t.lie_h_e_smul K), t.e_ne_zero⟩
    have heig_f : (LieAlgebra.ad K L h).HasEigenvector (-2) f :=
      ⟨Module.End.mem_eigenspace_iff.2
        (by rw [LieAlgebra.ad_apply, t.lie_lie_smul_f K, neg_smul]), t.f_ne_zero⟩
    have heig_h : (LieAlgebra.ad K L h).HasEigenvector 0 h :=
      ⟨Module.End.mem_eigenspace_iff.2 (by rw [LieAlgebra.ad_apply, lie_self, zero_smul]),
        t.h_ne_zero⟩
    fin_cases i <;> assumption

/-- **A generating `sl₂` triple is a basis.** A Lie algebra spanned by an `sl₂` triple is free of
rank `3` on it: the triple spans by hypothesis and is linearly independent by
`TauCeti.linearIndependent_isSl2Triple`. -/
noncomputable def basisOfIsSl2Triple (t : IsSl2Triple h e f) (htop : t.toLieSubalgebra K = ⊤) :
    Basis (Fin 3) K L :=
  Basis.mk (linearIndependent_isSl2Triple t) <| by
    rintro x -
    have hx_mem : x ∈ t.toLieSubalgebra K := by rw [htop]; trivial
    obtain ⟨c₁, c₂, c₃, hx⟩ := IsSl2Triple.mem_toLieSubalgebra_iff.1 hx_mem
    rw [t.lie_e_f] at hx
    subst hx
    exact Submodule.add_mem _ (Submodule.add_mem _
      (Submodule.smul_mem _ _ (Submodule.subset_span ⟨0, rfl⟩))
      (Submodule.smul_mem _ _ (Submodule.subset_span ⟨1, rfl⟩)))
      (Submodule.smul_mem _ _ (Submodule.subset_span ⟨2, rfl⟩))

variable (t : IsSl2Triple h e f) (htop : t.toLieSubalgebra K = ⊤)

/-- The first vector of the basis of a generating triple is the raising element `e`. -/
@[simp] theorem basisOfIsSl2Triple_zero : basisOfIsSl2Triple t htop 0 = e := Basis.mk_apply _ _ 0

/-- The second vector of the basis of a generating triple is the lowering element `f`. -/
@[simp] theorem basisOfIsSl2Triple_one : basisOfIsSl2Triple t htop 1 = f := Basis.mk_apply _ _ 1

/-- The third vector of the basis of a generating triple is the semisimple element `h`. -/
@[simp] theorem basisOfIsSl2Triple_two : basisOfIsSl2Triple t htop 2 = h := Basis.mk_apply _ _ 2

end GeneratingTriple

/-! ### Perfectness of a generating triple -/

section Perfect

variable {K : Type*} [Field K] [NeZero (2 : K)] {L : Type*} [LieRing L] [LieAlgebra K L]
  {M : Type*} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
  {h e f : L} {t : IsSl2Triple h e f}

/-- **A Lie algebra generated by an `sl₂` triple is perfect**, in the form in which the statement is
used: if the action of `L` on `M` composes to zero then it is already zero. Indeed each of
`h = ⁅e, f⁆`, `2e = ⁅h, e⁆` and `-2f = ⁅h, f⁆` is a bracket, so each acts as a composite. -/
theorem lie_eq_zero_of_lie_lie_eq_zero (htop : t.toLieSubalgebra K = ⊤)
    (hzero : ∀ (x y : L) (m : M), ⁅x, ⁅y, m⁆⁆ = 0) (x : L) (m : M) : ⁅x, m⁆ = 0 := by
  have hbr : ∀ (y z : L) (w : M), ⁅⁅y, z⁆, w⁆ = 0 := by
    intro y z w
    rw [lie_lie, hzero, hzero, sub_zero]
  have hh : ⁅h, m⁆ = 0 := by rw [← t.lie_e_f, hbr]
  have he : ⁅e, m⁆ = 0 := by
    have h2 : (2 : K) • ⁅e, m⁆ = 0 := by rw [← smul_lie, ← t.lie_h_e_smul K, hbr]
    exact (smul_eq_zero.1 h2).resolve_left two_ne_zero
  have hf : ⁅f, m⁆ = 0 := by
    have h2 : (2 : K) • ⁅f, m⁆ = 0 := by
      have hbrf := hbr h f m
      rwa [t.lie_lie_smul_f K, neg_lie, smul_lie, neg_eq_zero] at hbrf
    exact (smul_eq_zero.1 h2).resolve_left two_ne_zero
  obtain ⟨c₁, c₂, c₃, rfl⟩ :=
    IsSl2Triple.mem_toLieSubalgebra_iff.1 (htop ▸ LieSubalgebra.mem_top x)
  rw [t.lie_e_f]
  simp [he, hf, hh]

end Perfect

end TauCeti
