/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.Induction.Artin.Spanning

set_option warningAsError false

/-!
# Lookahead stubs for the mixed-characteristic Euler characteristic

These are lookahead stubs for the supplier
`modular-artin-exists-nsmul-mem-ind-cyclic-coprime`. They are to be replaced by the declarations
landed from that supplier.
-/

public section

open scoped MonoidAlgebra

namespace TauCeti

universe u

variable {k G : Type u} [Field k] [Group G] [Finite G]
  (p : ℕ) [Fact p.Prime] [CharP k p]

/-- The group-order multiple of every modular representation class is generated by induction from
cyclic subgroups whose orders are prime to the characteristic. -/
theorem modularArtin_natCard_nsmul_mem_indCyclicCoprime
    (x : ExactK0 (finiteModulesExactStructure k[G])) :
    Nat.card G • x ∈
      ⨆ (D : Subgroup G) (_ : IsCyclic D ∧ ¬ p ∣ Nat.card D), (indK0 k D).range := by
  sorry

/-- Every modular representation class has a positive multiple generated by induction from cyclic
subgroups whose orders are prime to the characteristic. -/
theorem modularArtin_exists_nsmul_mem_indCyclicCoprime
    (x : ExactK0 (finiteModulesExactStructure k[G])) :
    ∃ N : ℕ, 0 < N ∧ N • x ∈
      ⨆ (D : Subgroup G) (_ : IsCyclic D ∧ ¬ p ∣ Nat.card D), (indK0 k D).range := by
  sorry

end TauCeti
