/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Lookahead.TateModuleLinearEquiv.Stubs
public import TauCeti.NumberTheory.Padics.MultiplicativeCompletion.Decomposition

/-!
# The integral decomposition of the Tate module of a layer

Let `L/K` be a finite Galois layer of `p`-adic fields with group `G = Gal(L/K)` and
`N = [K : ℚ_p]`, and let `Y` be a Tate module of the layer (`TauCeti.LayerTateModule`): a finitely
generated `ℤ_p[G]`-module of projective dimension at most one which is an extension
`0 → A(L) → Y → I_G → 0` of the augmentation ideal by the `p`-adic completion `A(L)` of `Lˣ`. For
a generating pair `σ, τ` of `G` with sharp exponents `a, b`, this file records the isomorphism
`(∗∗)` in the proof of NSW (7.4.1),

`Y ≃ M₀ ⊕ ℤ_p[G]^N`

as `ℤ_p[G]`-modules, where `M₀ = ℤ_p[G]² / ℤ_p[G]·(σ - a, τ - b)` is the tame-frame module.

The decomposition is `TauCeti.nonempty_linearEquiv_tameFrameModule_prod`, stated for any extension
of `I_G` by `A(L)` with a resolution of length one by finitely generated projectives. A Tate module
supplies such a resolution: the kernel of a surjection `ℤ_p[G]^n → Y` with projective kernel,
which is finitely generated because `ℤ_p[G]^n` is noetherian over `ℤ_p`.

## Main results

* `TauCeti.LayerTateModule.nonempty_linearEquiv_tameFrameModule_prod`: a Tate module of the layer
  is isomorphic to `M₀ ⊕ ℤ_p[G]^N`.

## References

* J. Neukirch, A. Schmidt, K. Wingberg, *Cohomology of Number Fields*, 2nd ed., (5.6.5) and the
  proof of (7.4.1).
-/

public section

universe u

namespace TauCeti.LayerTateModule

variable {p : ℕ} [Fact p.Prime] {L : Type u} [Field L] {K : Type u} [Field K] [Algebra K L]

/-- **The integral decomposition of the Tate module of a layer** (the isomorphism `(∗∗)` in the
proof of NSW (7.4.1)). Let `L/K` be a finite Galois layer of `p`-adic fields with group
`G = Gal(L/K)` and `N = [K : ℚ_p]`, let `σ, τ` generate `G`, and let `a, b` be exponents through
which `σ, τ` act on `μ_{p^∞}(L)` such that `ℤ_p[G] ⧸ (σ - a, τ - b)` has the sharp order `q(L)`.
Then every Tate module `Y` of the layer is isomorphic to `M₀ ⊕ ℤ_p[G]^N` as a `ℤ_p[G]`-module,
where `M₀ = ℤ_p[G]² / ℤ_p[G]·(σ - a, τ - b)` is the tame-frame module. The statement is integral:
`Y` is generated by `N + 2` elements, which is not visible rationally. -/
theorem nonempty_linearEquiv_tameFrameModule_prod [Algebra ℚ_[p] L] [Module.Finite ℚ_[p] L]
    [Algebra ℚ_[p] K] [IsScalarTower ℚ_[p] K L] [IsGalois K L] (Y : LayerTateModule p L K)
    (h : Finite (pPowerRootsOfUnity p L)) (σ τ : L ≃ₐ[K] L)
    (hgen : Subgroup.closure {σ, τ} = ⊤) (a b : ℕ)
    (ha : ∀ ζ ∈ pPowerRootsOfUnity p L, Units.map (σ : L →* L) ζ = ζ ^ a)
    (hb : ∀ ζ ∈ pPowerRootsOfUnity p L, Units.map (τ : L →* L) ζ = ζ ^ b)
    (hcard : Nat.card (MonoidAlgebra ℤ_[p] (L ≃ₐ[K] L) ⧸ Ideal.span
      {MonoidAlgebra.single σ (1 : ℤ_[p]) - a, MonoidAlgebra.single τ (1 : ℤ_[p]) - b}) =
        localRootOfUnityOrder p L h) :
    Nonempty (Y.carrier ≃ₗ[MonoidAlgebra ℤ_[p] (L ≃ₐ[K] L)]
      (TameFrameModule ℤ_[p] (L ≃ₐ[K] L) σ τ (a : ℤ_[p]) (b : ℤ_[p]) ×
        (Fin (Module.finrank ℚ_[p] K) → MonoidAlgebra ℤ_[p] (L ≃ₐ[K] L)))) := by
  have := Module.Finite.right ℚ_[p] K L
  obtain ⟨n, f, hf, _⟩ := Y.projdim
  -- The projective kernel of `ℤ_p[G]^n → Y` is finitely generated, as `ℤ_p[G]^n` is noetherian
  -- over `ℤ_p`.
  have : Module.Finite ℤ_[p] (LinearMap.ker f) :=
    Module.IsNoetherian.finite ℤ_[p] ((LinearMap.ker f).restrictScalars ℤ_[p])
  have : Module.Finite (MonoidAlgebra ℤ_[p] (L ≃ₐ[K] L)) (LinearMap.ker f) :=
    .of_restrictScalars_finite ℤ_[p] _ _
  exact TauCeti.nonempty_linearEquiv_tameFrameModule_prod (LinearMap.exact_subtype_ker_map f)
    (LinearMap.ker f).injective_subtype hf (LinearMap.exact_iff.mpr Y.exact) Y.ι_injective
    Y.π_surjective h σ τ hgen a b ha hb hcard

end TauCeti.LayerTateModule
