/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.LinearAlgebra.Unimodular
public import Mathlib.RingTheory.LocalRing.Basic

/-!
# Unimodular elements: scalar extension, unit rescaling, and local coordinates

Complements to `Mathlib.LinearAlgebra.Unimodular`. Unimodularity of an element `v` of an
`R`-module (some linear functional takes the value `1` at `v`) is invariant under multiplication by
units, so each unit multiple of a unimodular vector can be used as a generator when constructing
projective orbit morphisms. Extending scalars preserves unimodularity, including along maps to
noncommutative algebras. A coordinate vector `v : ι → R` with a unit coordinate is unimodular.
Over a directly finite local semiring the converse holds for finitely many coordinates: `v` is
unimodular exactly when one of its coordinates is a unit. In particular this applies to local
commutative rings, where it normalizes homogeneous coordinates of points of projective schemes.

## Main results

* `Units.isUnimodular_smul_iff`: unit rescaling leaves unimodularity unchanged.
* `Module.IsUnimodular.one_tmul`: scalar extension preserves a unimodular vector.
* `Module.IsUnimodular.span_singleton_eq_iff`: cyclic submodules generated by a unimodular
  vector agree precisely up to unit rescaling, even over rings with zero divisors.
* `IsUnit.isUnimodular_pi`: a coordinate vector with a unit coordinate is unimodular.
* `TauCeti.Module.isUnimodular_iff_exists_isUnit`: over a directly finite local semiring, a vector
  with finitely many coordinates is unimodular if and only if one of its coordinates is a unit.
* `TauCeti.forall_mul_eq_mul_iff_exists_units`: two coordinate families generating the unit ideal
  are unit multiples of one another exactly when their `2 × 2` minors vanish.
-/

public section

open scoped TensorProduct

namespace Module.IsUnimodular

/-- Extending scalars preserves a unimodular vector. No flatness or commutativity of the target
algebra is needed. -/
theorem one_tmul {R S M : Type*} [CommSemiring R] [Semiring S]
    [Algebra R S] [AddCommMonoid M] [Module R M] {m : M}
    (hm : Module.IsUnimodular R m) : Module.IsUnimodular S (1 ⊗ₜ[R] m : S ⊗[R] M) := by
  obtain ⟨φ, hφ⟩ := Module.isUnimodular_iff.mp hm
  exact Module.isUnimodular_of_apply_eq_one
    (f := (TensorProduct.AlgebraTensorModule.rid R S S).toLinearMap.comp (φ.baseChange S))
    (by simp [hφ])

end Module.IsUnimodular

section Semiring

variable {R M : Type*} [Semiring R] [AddCommMonoid M] [Module R M]

/-- Unit rescaling leaves unimodularity unchanged. -/
@[simp]
theorem Units.isUnimodular_smul_iff (c : Rˣ) {m : M} :
    Module.IsUnimodular R (c • m) ↔ Module.IsUnimodular R m := by
  have forward (c : Rˣ) {m : M} (hm : Module.IsUnimodular R m) :
      Module.IsUnimodular R (c • m) := by
    obtain ⟨f, hf⟩ := Module.isUnimodular_iff.mp hm
    exact Module.isUnimodular_of_apply_eq_one
      (f := (LinearMap.mulRight R (↑c⁻¹ : R)).comp f) (by
        simp [LinearMap.mulRight_apply, Units.smul_def, hf])
  exact ⟨fun h ↦ by simpa using forward c⁻¹ h, forward c⟩

/-- A coordinate vector with a unit coordinate is unimodular. -/
theorem IsUnit.isUnimodular_pi {ι : Type*} {v : ι → R} {i : ι} (hi : IsUnit (v i)) :
    Module.IsUnimodular R v :=
  Module.isUnimodular_of_apply_eq_one
    (f := (LinearMap.mulRight R (↑hi.unit⁻¹ : R)).comp (LinearMap.proj i)) (by simp)

end Semiring

namespace TauCeti.Module

/-- Over a directly finite local semiring, a vector with finitely many coordinates is unimodular
if and only if one of its coordinates is a unit. -/
theorem isUnimodular_iff_exists_isUnit {R ι : Type*} [Semiring R] [IsLocalRing R]
    [IsDedekindFiniteMonoid R] [Finite ι]
    {v : ι → R} : Module.IsUnimodular R v ↔ ∃ i, IsUnit (v i) := by
  refine ⟨fun h ↦ ?_, fun ⟨i, hi⟩ ↦ hi.isUnimodular_pi⟩
  obtain ⟨f, hf⟩ := Module.isUnimodular_iff.mp h
  classical
  have := Fintype.ofFinite ι
  -- `f v = ∑ᵢ vᵢ f(eᵢ)` is a unit, so one of its summands is.
  rw [LinearMap.pi_apply_eq_sum_univ] at hf
  obtain ⟨i, -, hi⟩ := IsLocalRing.exists_of_isUnit_sum (hf ▸ isUnit_one)
  exact ⟨i, isUnit_of_mul_isUnit_left hi⟩

end TauCeti.Module

namespace TauCeti

variable {R ι : Type*} [CommSemiring R]

/-- If a coordinate family generates the unit ideal and a second family has vanishing `2 × 2`
minors against it, then the second family is a multiple of the first. -/
theorem exists_forall_eq_mul_of_mul_eq_mul {a b : ι → R}
    (ha : Ideal.span (Set.range a) = ⊤) (hab : ∀ i j, b i * a j = b j * a i) :
    ∃ u : R, ∀ j, b j = u * a j := by
  obtain ⟨s, hs⟩ := Finsupp.mem_span_range_iff_exists_finsupp.mp
    (ha ▸ Submodule.mem_top : (1 : R) ∈ Ideal.span (Set.range a))
  refine ⟨s.sum fun i r ↦ r * b i, fun j ↦ ?_⟩
  -- Multiply `b j` by `1 = ∑ sᵢ aᵢ` and swap each `aᵢ` with `b j` using the minors.
  calc b j = (s.sum fun i r ↦ r • a i) * b j := by rw [hs, one_mul]
    _ = (s.sum fun i r ↦ r * b i) * a j := by
      simp only [Finsupp.sum_mul, smul_eq_mul, mul_assoc, hab, mul_comm (a _)]

/-- Two coordinate families, each generating the unit ideal, are unit multiples of one another
exactly when all their `2 × 2` minors vanish. -/
theorem forall_mul_eq_mul_iff_exists_units {a b : ι → R}
    (ha : Ideal.span (Set.range a) = ⊤) (hb : Ideal.span (Set.range b) = ⊤) :
    (∀ i j, b i * a j = b j * a i) ↔ ∃ c : Rˣ, ∀ i, b i = c * a i := by
  constructor
  · intro hab
    obtain ⟨u, hu⟩ := exists_forall_eq_mul_of_mul_eq_mul ha hab
    obtain ⟨v, hv⟩ := exists_forall_eq_mul_of_mul_eq_mul hb fun i j ↦ by
      rw [mul_comm, hab j i, mul_comm]
    obtain ⟨t, ht⟩ := Finsupp.mem_span_range_iff_exists_finsupp.mp
      (hb ▸ Submodule.mem_top : (1 : R) ∈ Ideal.span (Set.range b))
    -- `u * v` fixes every `b j`, and the `b j` generate the unit ideal.
    have huv : u * v = 1 := by
      calc u * v = u * v * (t.sum fun i r ↦ r • b i) := by rw [ht, mul_one]
        _ = t.sum fun i r ↦ r • b i := by
          simp only [Finsupp.mul_sum, smul_eq_mul]
          refine Finsupp.sum_congr fun i _ ↦ ?_
          rw [mul_left_comm, mul_assoc, ← hv, ← hu]
        _ = 1 := ht
    exact ⟨⟨u, v, huv, by rw [mul_comm, huv]⟩, hu⟩
  · rintro ⟨c, hc⟩ i j
    rw [hc i, hc j, mul_right_comm, mul_assoc]

end TauCeti

namespace Module.IsUnimodular

variable {R M : Type*} [CommSemiring R] [AddCommMonoid M] [Module R M]

/-- A unimodular vector and another vector generate the same cyclic submodule exactly when
one is a unit multiple of the other. This also holds over rings with zero divisors. -/
theorem span_singleton_eq_iff {v : M} (hv : Module.IsUnimodular R v) (w : M) :
    R ∙ v = R ∙ w ↔ ∃ c : Rˣ, c • v = w := by
  constructor
  · intro h
    obtain ⟨a, ha⟩ := Submodule.mem_span_singleton.mp
      (h.symm ▸ Submodule.mem_span_singleton_self w)
    obtain ⟨b, hb⟩ := Submodule.mem_span_singleton.mp
      (h ▸ Submodule.mem_span_singleton_self v)
    obtain ⟨f, hf⟩ := Module.isUnimodular_iff.mp hv
    have hab : b * a = 1 := by
      have heq := congrArg f hb
      rw [← ha, map_smul, map_smul] at heq
      simpa [hf] using heq
    exact ⟨⟨a, b, by simpa [mul_comm] using hab, hab⟩, ha⟩
  · rintro ⟨c, rfl⟩
    exact (Submodule.span_singleton_group_smul_eq R c v).symm

end Module.IsUnimodular
