/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.Perm.Sign
public import Mathlib.RingTheory.MvPolynomial.Symmetric.Defs
public import TauCeti.Combinatorics.Young.BenderKnuth
public import TauCeti.RingTheory.MvPolynomial.Symmetric.Schur.Basic

/-!
# Schur polynomials are symmetric

A Schur polynomial is the generating function of the semistandard tableaux of its shape, one
monomial per tableau, the exponent of `xᵢ` being how often the letter `i` occurs.  Nothing in that
description is symmetric in the letters: the tableaux are ordered objects, and the alphabet
`{0, …, N - 1}` enters `TauCeti.diagramSchurPoly` through the row-weak and column-strict conditions.
Symmetry is a theorem, and this file proves it.

The mechanism is the **Bender-Knuth involution** of
`TauCeti.Combinatorics.Young.BenderKnuth`: for each letter `v` it is a bijection of the tableaux of
a fixed shape which exchanges how often `v` and `v + 1` occur and fixes every other multiplicity
(`SemistandardYoungTableau.content_benderKnuth`).  Reindexing the defining sum along it therefore
exchanges the variables `x_v` and `x_{v+1}`, which is
`TauCeti.rename_swap_diagramSchurPoly`.  Adjacent transpositions generate the symmetric group
(`Equiv.Perm.mclosure_swap_castSucc_succ`), so this one exchange gives the whole symmetry,
`TauCeti.isSymmetric_diagramSchurPoly`.

The involution moves only the letters `v` and `v + 1`, so it preserves the alphabet only when both
of them belong to it; that is why the exchanged variables are given as a pair `a, b : Fin N` with
`(b : ℕ) = a + 1` rather than as an arbitrary pair of letters.  Exchanging two letters that are not
adjacent is not a Bender-Knuth move, and is obtained here only through the group generated by the
adjacent ones.

Symmetry is what makes `TauCeti.schurPoly` independent of the ordering of its alphabet, so it also
retro-justifies the definition of `TauCeti.schurPoly` on an arbitrary finite alphabet by an
arbitrary choice of ordering, and it places the Schur polynomials in
`MvPolynomial.symmetricSubalgebra`, where the elementary and complete homogeneous symmetric
polynomials they generalize already live.

## Main results

* `TauCeti.rename_swap_diagramSchurPoly`: a Schur polynomial is unchanged by exchanging two
  adjacent variables.
* `TauCeti.isSymmetric_diagramSchurPoly` and `TauCeti.schurPoly_isSymmetric`: **Schur polynomials
  are symmetric**.
* `TauCeti.schurPoly_mem_symmetricSubalgebra`: the same, read in
  `MvPolynomial.symmetricSubalgebra`.

## References

* R. P. Stanley, *Enumerative Combinatorics*, Volume 2, §7.10, Theorem 7.10.2: the skew Schur
  function is symmetric, proved by the same reduction to interchanging `xᵢ` and `x_{i+1}`. The
  involution is that of E. A. Bender and D. E. Knuth, *Enumeration of plane partitions*,
  J. Combinatorial Theory **13** (1972), 40--54.
* [W. Fulton, *Young Tableaux*][fulton1997], Section 2.2.
* [Schur--Weyl roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/SchurWeyl/README.md),
  Layer 7.
-/

public section

namespace TauCeti

open MvPolynomial

namespace BoundedSSYT

variable {N : ℕ} {μ : YoungDiagram}

/-- **The Bender-Knuth involution on bounded tableaux**, exchanging two adjacent letters `a` and
`b` of the alphabet.  Adjacency is what keeps the alphabet: the involution writes no letter other
than the ones already present and the two it exchanges. -/
def benderKnuth (T : BoundedSSYT N μ) {a b : Fin N} (hab : (b : ℕ) = (a : ℕ) + 1) :
    BoundedSSYT N μ :=
  ⟨T.1.benderKnuth (a : ℕ), fun i j hij => by
    rcases SemistandardYoungTableau.benderKnuth_apply_eq_or T.1 (a : ℕ) i j with h | h | h
    · rw [h]; exact T.2 i j hij
    · rw [h]; exact a.isLt
    · rw [h, ← hab]; exact b.isLt⟩

@[simp]
theorem benderKnuth_benderKnuth (T : BoundedSSYT N μ) {a b : Fin N}
    (hab : (b : ℕ) = (a : ℕ) + 1) : (T.benderKnuth hab).benderKnuth hab = T :=
  Subtype.ext (SemistandardYoungTableau.benderKnuth_benderKnuth T.1 (a : ℕ))

theorem benderKnuth_involutive (N : ℕ) (μ : YoungDiagram) {a b : Fin N}
    (hab : (b : ℕ) = (a : ℕ) + 1) :
    Function.Involutive fun T : BoundedSSYT N μ => T.benderKnuth hab :=
  fun T => benderKnuth_benderKnuth T hab

/-- Transposing two letters of the alphabet is transposing their values. -/
private theorem val_swap {a b i : Fin N} :
    ((Equiv.swap a b i : Fin N) : ℕ) = Equiv.swap (a : ℕ) (b : ℕ) (i : ℕ) := by
  rcases eq_or_ne i a with rfl | hia
  · rw [Equiv.swap_apply_left, Equiv.swap_apply_left]
  rcases eq_or_ne i b with rfl | hib
  · rw [Equiv.swap_apply_right, Equiv.swap_apply_right]
  · rw [Equiv.swap_apply_of_ne_of_ne hia hib,
      Equiv.swap_apply_of_ne_of_ne (fun h => hia (Fin.ext h)) (fun h => hib (Fin.ext h))]

/-- **The Bender-Knuth involution exchanges two adjacent letters**, read on the weight of a bounded
tableau. -/
theorem weight_benderKnuth (T : BoundedSSYT N μ) {a b : Fin N} (hab : (b : ℕ) = (a : ℕ) + 1)
    (i : Fin N) : weight (T.benderKnuth hab) i = weight T (Equiv.swap a b i) := by
  rw [weight_apply, weight_apply, val_swap, hab]
  exact SemistandardYoungTableau.content_benderKnuth T.1 (a : ℕ) (i : ℕ)

/-- The weight of the Bender-Knuth image of a tableau, as the transported weight. -/
theorem mapDomain_weight_swap (T : BoundedSSYT N μ) {a b : Fin N}
    (hab : (b : ℕ) = (a : ℕ) + 1) :
    Finsupp.mapDomain (Equiv.swap a b) (weight T) = weight (T.benderKnuth hab) := by
  ext i
  rw [← Finsupp.equivMapDomain_eq_mapDomain, Finsupp.equivMapDomain_apply, Equiv.symm_swap,
    weight_benderKnuth]

end BoundedSSYT

variable {R : Type*} [CommSemiring R]

/-- **A Schur polynomial is unchanged by exchanging two adjacent variables**: the Bender-Knuth
involution at the corresponding letter reindexes the sum of monomials defining it. -/
theorem rename_swap_diagramSchurPoly {N : ℕ} (R : Type*) [CommSemiring R] (μ : YoungDiagram)
    {a b : Fin N} (hab : (b : ℕ) = (a : ℕ) + 1) :
    rename (Equiv.swap a b) (diagramSchurPoly N R μ) = diagramSchurPoly N R μ := by
  calc rename (Equiv.swap a b) (diagramSchurPoly N R μ)
      = ∑ T : BoundedSSYT N μ, monomial (BoundedSSYT.weight (T.benderKnuth hab)) (1 : R) := by
        rw [diagramSchurPoly_eq_sum, map_sum]
        exact Finset.sum_congr rfl fun T _ => by
          rw [rename_monomial, BoundedSSYT.mapDomain_weight_swap T hab]
    _ = ∑ T : BoundedSSYT N μ, monomial (BoundedSSYT.weight T) (1 : R) :=
        Fintype.sum_bijective _ (BoundedSSYT.benderKnuth_involutive N μ hab).bijective _ _
          fun _ => rfl
    _ = diagramSchurPoly N R μ := (diagramSchurPoly_eq_sum N R μ).symm

/-- **Schur polynomials are symmetric.**  Adjacent transpositions generate the symmetric group, so
the single exchange `TauCeti.rename_swap_diagramSchurPoly` supplied by the Bender-Knuth involution
gives the whole symmetry. -/
theorem isSymmetric_diagramSchurPoly (N : ℕ) (R : Type*) [CommSemiring R] (μ : YoungDiagram) :
    (diagramSchurPoly N R μ).IsSymmetric := by
  intro e
  match N with
  | 0 =>
    rw [Subsingleton.elim e 1]
    simp
  | M + 1 =>
    have hmem : e ∈ Submonoid.closure
        (Set.range fun i : Fin M => Equiv.swap i.castSucc i.succ) := by
      rw [Equiv.Perm.mclosure_swap_castSucc_succ]
      trivial
    induction hmem using Submonoid.closure_induction with
    | mem x hx =>
      obtain ⟨i, rfl⟩ := hx
      exact rename_swap_diagramSchurPoly R μ (by simp)
    | one => simp
    | mul x y _ _ hx hy =>
      rw [Equiv.Perm.coe_mul, ← rename_rename, hy, hx]

/-- Renaming a diagram Schur polynomial along a bijection of finite alphabets preserves it. -/
@[simp]
theorem rename_diagramSchurPoly {M N : ℕ} (μ : YoungDiagram) (e : Fin M ≃ Fin N) :
    rename e (diagramSchurPoly M R μ) = diagramSchurPoly N R μ := by
  have h : M = N := by simpa only [Fintype.card_fin] using Fintype.card_congr e
  subst M
  exact isSymmetric_diagramSchurPoly N R μ e

/-- The partition-indexed Schur polynomial of a Young diagram in `Fin N` is its
diagram-indexed Schur polynomial. -/
@[simp]
theorem schurPoly_fin_shapePartition (N : ℕ) (μ : YoungDiagram) :
    schurPoly (Fin N) R (shapePartition μ) = diagramSchurPoly N R μ := by
  rw [schurPoly_eq_rename, diagramOf_shapePartition, rename_diagramSchurPoly]

/-- Renaming a symmetric polynomial along a bijection of alphabets keeps it symmetric. -/
private theorem isSymmetric_rename {σ τ : Type*} {p : MvPolynomial τ R} (hp : p.IsSymmetric)
    (e : τ ≃ σ) : (rename e p).IsSymmetric := by
  intro f
  have hcomp : (⇑f ∘ ⇑e) = ⇑e ∘ ⇑(e.trans (f.trans e.symm)) := funext fun t => by simp
  rw [rename_rename, hcomp, ← rename_rename, hp]

/-- **Schur polynomials are symmetric**, on an arbitrary finite alphabet.  This is what makes
`TauCeti.schurPoly` independent of the ordering of the alphabet chosen to define it. -/
theorem schurPoly_isSymmetric {σ : Type*} [Fintype σ] {n : ℕ} (μ : n.Partition) :
    (schurPoly σ R μ).IsSymmetric := by
  rw [schurPoly_eq_rename]
  exact isSymmetric_rename (isSymmetric_diagramSchurPoly _ _ _) _

/-- **Schur polynomials are symmetric**, read as membership in
`MvPolynomial.symmetricSubalgebra`, where the elementary and complete homogeneous symmetric
polynomials they generalize already live. -/
theorem schurPoly_mem_symmetricSubalgebra {σ : Type*} [Fintype σ] {n : ℕ} (μ : n.Partition) :
    schurPoly σ R μ ∈ symmetricSubalgebra σ R :=
  (mem_symmetricSubalgebra _).mpr (schurPoly_isSymmetric μ)

end TauCeti
