/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.LocalField.Unramified.Inertia.Basic
public import TauCeti.NumberTheory.LocalField.Uniformizer
public import TauCeti.Topology.Algebra.Group.Profinite.Sylow.Basic
import TauCeti.Algebra.CharP.LocalRing
import TauCeti.NumberTheory.LocalField.TamelyRamified.Basic
import TauCeti.NumberTheory.LocalField.UnitFiltration.Pow
import TauCeti.NumberTheory.LocalField.UnitFiltration.RamificationGroup
import TauCeti.NumberTheory.LocalField.UnitsDecomposition
import TauCeti.NumberTheory.LocalField.Unramified.Inertia.Finite
import TauCeti.Topology.Algebra.Group.Profinite.ProP.Burnside
import TauCeti.Topology.Algebra.Group.Profinite.ProP.Subgroup
import TauCeti.Topology.Algebra.Group.Profinite.Sylow.Conjugacy
import TauCeti.Topology.Algebra.Group.Profinite.Sylow.Functoriality

/-!
# The maximal tamely ramified extension and wild inertia

Let `K` be a nonarchimedean local field with residue field `𝓀[K]` of characteristic `p` and
cardinality `q`, and let `Ω` be an extension of `K`. This file defines the **maximal tamely
ramified extension**

`TauCeti.maximalTameExtension K Ω`,

the intermediate field `K^{t}` of `Ω / K` generated by the `m`-th roots of the nonzero elements of
`K`, for all `m` prime to `p`. It contains the maximal unramified extension `K^{ur}`, whose
generators are roots of unity of order prime to `p`, and it is Galois over `K` when `Ω` is
separably closed. For any uniformizer `π` of `K` it is the familiar

`K^{t} = K^{ur}(π^{1/m} : p ∤ m) = ⋃_{p ∤ m} K^{ur}(π^{1/m})`,

since for a unit `u` of `K` and `p ∤ m` the roots of `X^m − u` are unramified: `u` is a root of
unity of order prime to `p` times a principal unit, and principal units are `m`-th powers in `K`.

The **wild inertia subgroup** `P_K = TauCeti.wildInertiaSubgroup K` of the absolute Galois group
`G_K = Field.absoluteGaloisGroup K` is the fixing subgroup of `K^{t}` inside `K^{alg}`, which
`IntermediateField.fixingSubgroupEquiv` identifies with `Gal(K^{alg}/K^{t})`. It is a closed normal
subgroup of `G_K`, contained in the inertia subgroup `I_K = TauCeti.inertiaSubgroup K`.

At finite level, `P_K` is the inverse limit of the wild inertia groups `G_1` of the finite normal
subextensions `L` of `K^{alg}/K`: an automorphism lies in `P_K` exactly when each of its
restrictions lies in the first lower ramification group `G_1` of `L/K`. As each `G_1` is a
`p`-group, `P_K` is pro-`p`; conversely every pro-`p` subgroup of `I_K` fixes the tame radicals,
since `I_K` acts on them through roots of unity of order prime to `p`. So `P_K` is the largest
pro-`p` subgroup of `I_K`: it is the unique Sylow pro-`p` subgroup of `I_K`.

Restriction to a finite Galois subextension `L` maps `I_K` onto the inertia group `G_0` of `L/K`,
and a continuous surjection carries a Sylow pro-`p` subgroup onto a Sylow subgroup; since `G_1` is
the unique Sylow `p`-subgroup of `G_0`, the image of `P_K` is all of `G_1`. Consequently `L` lies
in `K^{t}` exactly when `G_1` of `L/K` is trivial, that is, exactly when `L/K` is tamely ramified.

Being a normal pro-`p` subgroup, `P_K` can be discarded when counting topological generators of
`G_K`, up to its commutator subgroup: by the Frattini argument along `P_K`, a set generating `G_K`
modulo `⁅P_K, P_K⁆` already generates `G_K`.

## Main definitions

* `TauCeti.maximalTameExtension K Ω`: the maximal tamely ramified extension `K^{t}` of `K` in `Ω`.
* `TauCeti.wildInertiaSubgroup K`: the wild inertia subgroup `P_K` of `G_K`.

## Main results

* `TauCeti.maximalUnramifiedExtension_le_maximalTameExtension`: `K^{ur} ≤ K^{t}`.
* `TauCeti.isGalois_maximalTameExtension`: for `Ω` separably closed, `K^{t}` is Galois over `K`.
* `TauCeti.maximalTameExtension_eq_sup_adjoin`: for `Ω` separably closed and any uniformizer `π`,
  `K^{t} = K^{ur}(π^{1/m} : p ∤ m)`.
* `TauCeti.isClosed_wildInertiaSubgroup`, `TauCeti.wildInertiaSubgroup_normal`: `P_K` is closed and
  normal in `G_K`.
* `TauCeti.wildInertiaSubgroup_le_inertiaSubgroup`: `P_K ≤ I_K`.
* `TauCeti.restrictNormal_mem_lowerRamificationGroup_one`: the restriction of an element of `P_K`
  to a finite normal subextension `L` lies in `G_1` of `L/K`.
* `TauCeti.mem_wildInertiaSubgroup_iff_forall_restrictNormal_mem`: `P_K` is the inverse limit of
  the finite-level groups `G_1`.
* `TauCeti.isProP_wildInertiaSubgroup`: `P_K` is pro-`p`.
* `TauCeti.le_wildInertiaSubgroup_of_isProP`: every pro-`p` subgroup of `I_K` lies in `P_K`.
* `TauCeti.isProPSylow_wildInertiaSubgroup` and
  `TauCeti.eq_subgroupOf_wildInertiaSubgroup_of_isProPSylow`: `P_K` is the unique Sylow pro-`p`
  subgroup of `I_K`.
* `TauCeti.topologicalClosure_eq_top_of_sup_wildInertiaCommutator`: a set topologically generating
  `G_K` together with `⁅P_K, P_K⁆` topologically generates `G_K`.
* `TauCeti.map_wildInertiaSubgroup_restrictNormalHom`: the image of `P_K` in the Galois group of a
  finite Galois subextension `L` is the first lower ramification group `G_1` of `L/K`.
* `TauCeti.le_maximalTameExtension_iff`: a finite Galois subextension `L` lies in `K^{t}` exactly
  when `L/K` is tamely ramified.
* `TauCeti.isTamelyRamified_sup_iff`: a finite Galois compositum is tamely ramified exactly when
  both factors are tamely ramified, by the maximal-tame-extension criterion.
* `TauCeti.mem_wildInertiaSubgroup_iff_of_isUniformizer`: `σ ∈ P_K` exactly when `σ ∈ I_K` and `σ`
  fixes every `m`-th root of a given uniformizer, for `p ∤ m`.

## References

* [J.-P. Serre, *Corps Locaux*][serre1968], Chapter IV, §2.
* J. Neukirch, *Algebraic Number Theory*, Chapter II, §7.
* J. Neukirch, A. Schmidt, K. Wingberg, *Cohomology of Number Fields*, (3.9.1) and Chapter VII,
  §5.
-/

public section

noncomputable section

open ValuativeRel Polynomial IntermediateField

namespace TauCeti

variable {K : Type*} [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]

/-! ### The maximal tamely ramified extension -/

variable (K) (Ω : Type*) [Field Ω] [Algebra K Ω]

/-- **The maximal tamely ramified extension** `K^{t}` of a nonarchimedean local field `K` inside an
extension `Ω`: the intermediate field generated by the `m`-th roots of the nonzero elements of `K`,
for all `m` not divisible by the residue characteristic `p`. It contains the maximal unramified
extension, and for a uniformizer `π` of `K` and `Ω` separably closed it is `K^{ur}(π^{1/m} : p ∤ m)`
by `TauCeti.maximalTameExtension_eq_sup_adjoin`. -/
def maximalTameExtension : IntermediateField K Ω :=
  adjoin K {x : Ω | ∃ m : ℕ, ¬ ringChar 𝓀[K] ∣ m ∧ ∃ a : Kˣ, x ^ m = algebraMap K Ω a}

/-- The maximal tamely ramified extension is generated by the `m`-th roots of the nonzero elements
of `K`, for `m` prime to the residue characteristic. -/
theorem maximalTameExtension_def :
    maximalTameExtension K Ω =
      adjoin K {x : Ω | ∃ m : ℕ, ¬ ringChar 𝓀[K] ∣ m ∧ ∃ a : Kˣ, x ^ m = algebraMap K Ω a} :=
  -- `(rfl)`, not `rfl`: keep the body opaque while exporting this equation across modules.
  (rfl)

variable {K Ω} in
/-- An `m`-th root of a nonzero element of `K` lies in the maximal tamely ramified extension, when
the residue characteristic does not divide `m`. -/
theorem mem_maximalTameExtension_of_pow_eq {m : ℕ} (hm : ¬ ringChar 𝓀[K] ∣ m) (a : Kˣ) {x : Ω}
    (hx : x ^ m = algebraMap K Ω a) : x ∈ maximalTameExtension K Ω :=
  subset_adjoin _ _ ⟨m, hm, a, hx⟩

/-- **The maximal unramified extension is tamely ramified**: `K^{ur} ≤ K^{t}`, since `K^{ur}` is
generated by roots of unity of order `q ^ f − 1`, which is prime to the residue characteristic. -/
theorem maximalUnramifiedExtension_le_maximalTameExtension :
    maximalUnramifiedExtension K Ω ≤ maximalTameExtension K Ω := by
  rw [maximalUnramifiedExtension_eq_adjoin, adjoin_le_iff]
  rintro x ⟨f, hf, hx⟩
  rcases eq_or_ne x 0 with rfl | hx0
  · exact zero_mem _
  have hq := IsLocalRing.isUnit_natCast_iff_not_dvd.1 (isUnit_natCast_natCard_pow_sub_one K hf)
  refine mem_maximalTameExtension_of_pow_eq hq 1 ?_
  -- `x ^ (q ^ f - 1) = x ^ q ^ f / x = 1`.
  calc x ^ (Nat.card 𝓀[K] ^ f - 1) = x ^ Nat.card 𝓀[K] ^ f * (x ^ 1)⁻¹ :=
        pow_sub₀ x hx0 (Nat.one_le_iff_ne_zero.2 (pow_ne_zero _ Nat.card_pos.ne'))
    _ = algebraMap K Ω (1 : Kˣ) := by simp [hx, hx0]

/-- The maximal tamely ramified extension is the compositum of the fields generated by the roots of
the polynomials `X^m − a`, for `a ∈ Kˣ` and `m` prime to the residue characteristic. -/
private theorem maximalTameExtension_eq_iSup :
    maximalTameExtension K Ω =
      ⨆ i : {m : ℕ // ¬ ringChar 𝓀[K] ∣ m} × Kˣ,
        adjoin K ((X ^ (i.1 : ℕ) - C (i.2 : K)).rootSet Ω) := by
  rw [maximalTameExtension_def, ← adjoin_iUnion]
  congr 1
  ext x
  simp only [Set.mem_ofPred_eq, Set.mem_iUnion, Prod.exists, Subtype.exists, mem_rootSet, map_sub,
    map_pow, aeval_X, aeval_C, sub_eq_zero, exists_prop]
  refine ⟨fun ⟨m, hm, a, hx⟩ ↦ ⟨m, hm, a, X_pow_sub_C_ne_zero ?_ _, hx⟩,
    fun ⟨m, hm, a, _, hx⟩ ↦ ⟨m, hm, a, hx⟩⟩
  exact Nat.pos_of_ne_zero fun h ↦ hm (h ▸ dvd_zero _)

/-- **The maximal tamely ramified extension is Galois** over `K`, when `Ω` is separably closed: it
is the compositum of the splitting fields of the separable polynomials `X^m − a`, `a ∈ Kˣ`,
`p ∤ m`. -/
instance isGalois_maximalTameExtension [IsSepClosed Ω] :
    IsGalois K (maximalTameExtension K Ω) := by
  rw [maximalTameExtension_eq_iSup]
  have (i : {m : ℕ // ¬ ringChar 𝓀[K] ∣ m} × Kˣ) :
      IsGalois K (adjoin K ((X ^ (i.1 : ℕ) - C (i.2 : K)).rootSet Ω)) := by
    have hsep : (X ^ (i.1 : ℕ) - C (i.2 : K)).Separable := separable_X_pow_sub_C _
      (natCast_ne_zero_of_isUnit (IsLocalRing.isUnit_natCast_iff_not_dvd.2 i.1.2)) i.2.ne_zero
    have := adjoin_rootSet_isSplittingField
      (IsSepClosed.splits_codomain (f := algebraMap K Ω) _ hsep)
    exact IsGalois.of_separable_splitting_field hsep
  exact ⟨⟩

variable {K Ω} in
/-- **The maximal tamely ramified extension, through a uniformizer.** For `Ω` separably closed and
any uniformizer `π` of `K`, `K^{t}` is generated over the maximal unramified extension by the
`m`-th roots of `π`, for `m` prime to the residue characteristic:
`K^{t} = K^{ur}(π^{1/m} : p ∤ m)`. -/
theorem maximalTameExtension_eq_sup_adjoin [IsSepClosed Ω] {π : Kˣ} (hπ : IsUniformizer K π) :
    maximalTameExtension K Ω = maximalUnramifiedExtension K Ω ⊔
      adjoin K {x : Ω | ∃ m : ℕ, ¬ ringChar 𝓀[K] ∣ m ∧ x ^ m = algebraMap K Ω π} := by
  set E := maximalUnramifiedExtension K Ω ⊔
    adjoin K {x : Ω | ∃ m : ℕ, ¬ ringChar 𝓀[K] ∣ m ∧ x ^ m = algebraMap K Ω π}
  refine le_antisymm ?_ (sup_le (maximalUnramifiedExtension_le_maximalTameExtension K Ω)
    (adjoin_le_iff.2 fun x ⟨m, hm, hx⟩ ↦ mem_maximalTameExtension_of_pow_eq hm π hx))
  rw [maximalTameExtension_def, adjoin_le_iff]
  rintro x ⟨m, hm, a, hx⟩
  set A := algebraMap K Ω
  -- An `m`-th root `y` of `π` lies in `E`.
  have : NeZero (m : Ω) := ⟨by
    rw [← map_natCast A]
    exact (_root_.map_ne_zero _).2
      (natCast_ne_zero_of_isUnit (IsLocalRing.isUnit_natCast_iff_not_dvd.2 hm))⟩
  obtain ⟨y, hy⟩ := IsSepClosed.exists_pow_nat_eq (k := Ω) (A π) m
  have hyE : y ∈ E := (le_sup_right : _ ≤ E) (subset_adjoin _ _ ⟨m, hm, hy⟩)
  have hy0 : y ≠ 0 := by
    rintro rfl
    rw [zero_pow (fun h ↦ NeZero.ne (m : Ω) (by rw [h, Nat.cast_zero]))] at hy
    exact (_root_.map_ne_zero A).2 π.ne_zero hy.symm
  -- Write `a = π ^ k u` with `u` a unit of `𝒪[K]`; then `z = x / y ^ k` is an `m`-th root of `u`,
  -- hence unramified.
  obtain ⟨⟨k, u⟩, hau, -⟩ := existsUnique_eq_zpow_mul ((isUniformizer_def π).1 hπ) a
  set z := x * (y ^ k)⁻¹
  have hyk : (y ^ k) ^ m = A (π : K) ^ k := by
    rw [← hy]
    exact_mod_cast zpow_comm y k m
  have hzm : z ^ m = A ((u : Kˣ) : K) := calc
    z ^ m = A (a : K) / A (π : K) ^ k := by rw [mul_pow, inv_pow, hx, hyk, div_eq_mul_inv]
    _ = A ((π : K) ^ k) * A ((u : Kˣ) : K) / A (π : K) ^ k := by simp [hau]
    _ = A ((u : Kˣ) : K) := by
      rw [map_zpow₀]
      field_simp
  have hzE : z ∈ E := (le_sup_left : _ ≤ E) (mem_maximalUnramifiedExtension_of_pow_eq hm u.2 hzm)
  have hxz : x = z * y ^ k := by
    simp only [z]
    field_simp
  rw [hxz]
  exact mul_mem hzE (zpow_mem hyE k)

/-! ### The wild inertia subgroup -/

/-- **The wild inertia subgroup** `P_K` of the absolute Galois group of a nonarchimedean local
field `K`: the automorphisms of the algebraic closure fixing the maximal tamely ramified extension
`K^{t}`. Through `IntermediateField.fixingSubgroupEquiv` it is `Gal(K^{alg}/K^{t})`. -/
def wildInertiaSubgroup : Subgroup (Field.absoluteGaloisGroup K) :=
  (maximalTameExtension K (AlgebraicClosure K)).fixingSubgroup

/-- The wild inertia subgroup is the fixing subgroup of the maximal tamely ramified extension. -/
theorem wildInertiaSubgroup_def :
    wildInertiaSubgroup K = (maximalTameExtension K (AlgebraicClosure K)).fixingSubgroup :=
  -- `(rfl)`, not `rfl`: keep the body opaque while exporting this equation across modules.
  (rfl)

variable {K} in
/-- An automorphism lies in the wild inertia subgroup exactly when it fixes every element of the
maximal tamely ramified extension. -/
@[simp]
theorem mem_wildInertiaSubgroup_iff {σ : Field.absoluteGaloisGroup K} :
    σ ∈ wildInertiaSubgroup K ↔
      ∀ x ∈ maximalTameExtension K (AlgebraicClosure K),
        DFunLike.coe (F := Gal(AlgebraicClosure K/K)) σ x = x :=
  mem_fixingSubgroup_iff _ _

variable {K} in
/-- **Wild inertia, through radicals.** An automorphism of `K^{alg}` lies in the wild inertia
subgroup exactly when it fixes every `m`-th root of every nonzero element of `K`, for `m` prime to
the residue characteristic. -/
theorem mem_wildInertiaSubgroup_iff_pow_eq {σ : Field.absoluteGaloisGroup K} :
    σ ∈ wildInertiaSubgroup K ↔
      ∀ (m : ℕ), ¬ ringChar 𝓀[K] ∣ m → ∀ (a : Kˣ) (x : AlgebraicClosure K),
        x ^ m = algebraMap K (AlgebraicClosure K) a →
          DFunLike.coe (F := Gal(AlgebraicClosure K/K)) σ x = x := by
  rw [wildInertiaSubgroup_def, maximalTameExtension_def]
  refine ((mem_fixingSubgroup_iff _ σ).trans
    (forall_mem_adjoin_smul_eq_self_iff K (M := Gal(AlgebraicClosure K/K)) σ)).trans ?_
  exact ⟨fun h m hm a x hx ↦ h x ⟨m, hm, a, hx⟩, fun h x ⟨m, hm, a, hx⟩ ↦ h m hm a x hx⟩

/-- **The wild inertia subgroup is closed** in the Krull topology. -/
theorem isClosed_wildInertiaSubgroup :
    IsClosed (wildInertiaSubgroup K : Set (Field.absoluteGaloisGroup K)) :=
  fixingSubgroup_isClosed_of_isAlgebraic _

/-- **The wild inertia subgroup is normal**, since `K^{t}/K` is normal. -/
instance wildInertiaSubgroup_normal : (wildInertiaSubgroup K).Normal :=
  (maximalTameExtension K (AlgebraicClosure K)).fixingSubgroup_normal

/-- **Wild inertia lies in inertia**: `P_K ≤ I_K`, since `K^{ur} ≤ K^{t}`. -/
theorem wildInertiaSubgroup_le_inertiaSubgroup : wildInertiaSubgroup K ≤ inertiaSubgroup K := by
  rw [wildInertiaSubgroup_def, inertiaSubgroup_def]
  exact fixingSubgroup_le (maximalUnramifiedExtension_le_maximalTameExtension K _)

variable {K} in
/-- **Wild inertia, through a uniformizer.** For a uniformizer `π` of `K`, an automorphism of
`K^{alg}` lies in the wild inertia subgroup exactly when it lies in the inertia subgroup and fixes
every `m`-th root of `π`, for `m` prime to the residue characteristic. -/
theorem mem_wildInertiaSubgroup_iff_of_isUniformizer {π : Kˣ} (hπ : IsUniformizer K π)
    {σ : Field.absoluteGaloisGroup K} :
    σ ∈ wildInertiaSubgroup K ↔ σ ∈ inertiaSubgroup K ∧
      ∀ (m : ℕ), ¬ ringChar 𝓀[K] ∣ m → ∀ x : AlgebraicClosure K,
        x ^ m = algebraMap K (AlgebraicClosure K) π →
          DFunLike.coe (F := Gal(AlgebraicClosure K/K)) σ x = x := by
  set M := maximalUnramifiedExtension K (AlgebraicClosure K)
  set N := adjoin K {x : AlgebraicClosure K | ∃ m : ℕ, ¬ ringChar 𝓀[K] ∣ m ∧
    x ^ m = algebraMap K (AlgebraicClosure K) π}
  -- State the splitting of the fixing subgroup of `M ⊔ N` on `Gal(K^{alg}/K)`, whose group
  -- structure is not reducibly that of `Field.absoluteGaloisGroup K`.
  have hsup (τ : Gal(AlgebraicClosure K/K)) :
      τ ∈ (M ⊔ N).fixingSubgroup ↔ τ ∈ M.fixingSubgroup ∧ τ ∈ N.fixingSubgroup := by
    rw [fixingSubgroup_sup, Subgroup.mem_inf]
  rw [wildInertiaSubgroup_def, inertiaSubgroup_def, maximalTameExtension_eq_sup_adjoin hπ]
  refine (hsup σ).trans (and_congr_right fun _ ↦ ((mem_fixingSubgroup_iff _ σ).trans
    (forall_mem_adjoin_smul_eq_self_iff K (M := Gal(AlgebraicClosure K/K)) σ)).trans ?_)
  exact ⟨fun h m hm x hx ↦ h x ⟨m, hm, hx⟩, fun h x ⟨m, hm, hx⟩ ↦ h m hm x hx⟩

/-! ### Wild inertia at finite level -/

open LocalFieldsRamification

variable {K} in
/-- **Wild inertia restricts into `G_1`.** The restriction of an element of the wild inertia
subgroup `P_K` to a finite normal subextension `L` of `K^{alg}/K` lies in the first ramification
group `G_1` of `L/K`. -/
theorem restrictNormal_mem_lowerRamificationGroup_one
    (L : IntermediateField K (AlgebraicClosure K)) [ValuativeRel L] [TopologicalSpace L]
    [IsNonarchimedeanLocalField L] [ValuativeExtension K L] [FiniteDimensional K L] [Normal K L]
    {σ : Gal(AlgebraicClosure K/K)} (hσ : σ ∈ wildInertiaSubgroup K) :
    AlgEquiv.restrictNormal σ L ∈ lowerRamificationGroup K L 1 := by
  set p := ringChar 𝓀[K]
  have hp : p.Prime := CharP.char_is_prime 𝓀[K] p
  have : CharP 𝓀[L] p := charP_of_injective_algebraMap (algebraMap 𝓀[K] 𝓀[L]).injective _
  have hσI := wildInertiaSubgroup_le_inertiaSubgroup K hσ
  set τ := AlgEquiv.restrictNormal σ L with hτ_def
  have hτ0 := restrictNormal_mem_lowerRamificationGroup_zero L hσI
  rw [lowerRamificationGroup_def] at hτ0 ⊢
  -- Write `v_L(π₀) = v_L(ϖ) ^ (p ^ k * m)` with `p ∤ m`, and let `β` be an `m`-th root of `π₀`,
  -- fixed by `σ`. In a finite normal extension `M` containing `L` and `β`, the restriction of `σ`
  -- lies in `G_0`, and `v(β) = v(ϖ) ^ (p ^ k)`, so `(σ ϖ / ϖ) ^ (p ^ k) ≡ 1`; this places the
  -- restriction to `L` in `G_1`.
  -- Uniformizers `π₀` of `K` and `ϖ` of `L`, with `π₀ = u ϖ ^ (p ^ k * m)` in `L`, `p ∤ m`.
  obtain ⟨ϖ, hϖ⟩ := IsDiscreteValuationRing.exists_irreducible 𝒪[L]
  obtain ⟨π₀, hπ₀⟩ := IsDiscreteValuationRing.exists_irreducible 𝒪[K]
  have hπne : algebraMap 𝒪[K] 𝒪[L] π₀ ≠ 0 := by
    rw [Ne, map_eq_zero_iff _ (FaithfulSMul.algebraMap_injective 𝒪[K] 𝒪[L])]
    exact hπ₀.ne_zero
  obtain ⟨E, u, hE⟩ := IsDiscreteValuationRing.eq_unit_mul_pow_irreducible hπne hϖ
  have hE0 : E ≠ 0 := by
    rintro rfl
    rw [pow_zero, mul_one] at hE
    exact hπ₀.not_isUnit (IsUnit.of_map (algebraMap 𝒪[K] 𝒪[L]) _ (hE ▸ u.isUnit))
  obtain ⟨k, m, hm, rfl⟩ := Nat.exists_eq_pow_mul_and_not_dvd hE0 p hp.ne_one
  have hm0 : m ≠ 0 := right_ne_zero_of_mul hE0
  -- An `m`-th root `β` of `π₀` in `K^{alg}`, fixed by `σ`.
  have hπ₀K : (π₀ : K) ≠ 0 := fun h ↦ hπ₀.ne_zero (Subtype.ext h)
  obtain ⟨β, hβ⟩ := IsAlgClosed.exists_pow_nat_eq
    (algebraMap K (AlgebraicClosure K) (π₀ : K)) (Nat.pos_of_ne_zero hm0)
  have hσβ : σ β = β := (mem_wildInertiaSubgroup_iff_pow_eq.1 hσ) m hm (Units.mk0 _ hπ₀K) β hβ
  -- A finite normal extension `M` of `K` containing `L` and `β`, with its local-field structure.
  set F : IntermediateField K (AlgebraicClosure K) := L ⊔ K⟮β⟯
  have : FiniteDimensional K K⟮β⟯ := adjoin.finiteDimensional (Algebra.IsIntegral.isIntegral β)
  have : FiniteDimensional K F := IntermediateField.finiteDimensional_sup _ _
  set M : IntermediateField K (AlgebraicClosure K) := normalClosure K F (AlgebraicClosure K)
  have : FiniteDimensional K M := normalClosure.is_finiteDimensional K F _
  have : Normal K M := normalClosure.normal K F _
  have hLM : L ≤ M := le_sup_left.trans F.le_normalClosure
  have hβM : β ∈ M := F.le_normalClosure ((le_sup_right : K⟮β⟯ ≤ F) (mem_adjoin_simple_self K β))
  let _ := finiteIntermediateFieldValuativeRel K (AlgebraicClosure K) M
  let _ := finiteIntermediateFieldTopology K (AlgebraicClosure K) M
  have := finiteIntermediateField_isNonarchimedeanLocalField K (AlgebraicClosure K) M
  have := finiteIntermediateField_valuativeExtension K (AlgebraicClosure K) M
  let ι : L →ₐ[K] M := inclusion hLM
  let _ := ι.toAlgebra
  have : IsScalarTower K L M := .of_algebraMap_eq fun x ↦ (ι.commutes x).symm
  have : ValuativeExtension L M := ι.valuativeExtension
  have hτM := restrictNormal_mem_lowerRamificationGroup_zero M hσI
  rw [lowerRamificationGroup_def] at hτM
  -- Valuations of elements of `L` are read in `M` through the map of value groups `f`.
  set f := ValuativeExtension.mapValueGroupWithZero L M
  have hf (y : L) : valuation M (algebraMap L M y) = f (valuation L y) :=
    (ValuativeExtension.mapValueGroupWithZero_valuation y).symm
  set a : M := algebraMap L M (ϖ : L)
  set b : M := ⟨β, hβM⟩
  have hϖ0 : (ϖ : L) ≠ 0 := fun h ↦ hϖ.ne_zero (Subtype.ext h)
  have hπL : valuation L (algebraMap K L (π₀ : K)) = valuation L (ϖ : L) ^ (p ^ k * m) := by
    have hu : valuation L ((u : 𝒪[L]) : L) = 1 :=
      (Valuation.integer.integers (valuation L)).valuation_unit u
    rw [← coe_algebraMap_integerRing, hE]
    simp [hu]
  have hbm : b ^ m = algebraMap L M (algebraMap K L (π₀ : K)) := by
    rw [← IsScalarTower.algebraMap_apply]
    exact Subtype.ext hβ
  -- `v(β) = v(ϖ) ^ (p ^ k)` in `M`, since the value group is torsion-free.
  have hab : valuation M b = valuation M a ^ p ^ k := by
    refine (pow_left_inj hm0).mp ?_
    rw [← map_pow, hbm, hf, hπL, map_pow, ← hf, ← pow_mul]
  have hσb : AlgEquiv.restrictNormal σ M • b = b :=
    Subtype.ext (by rw [AlgEquiv.smul_def, AlgEquiv.restrictNormal_apply, hσβ])
  have hratio : AlgEquiv.restrictNormal σ M • a / a = algebraMap L M (τ • (ϖ : L) / ϖ) := by
    rw [map_div₀]
    congr 1
    exact Subtype.ext (by
      rw [AlgEquiv.smul_def, AlgEquiv.restrictNormal_apply, AlgEquiv.smul_def, hτ_def]
      exact (AlgEquiv.restrictNormal_apply L σ ϖ).symm)
  have hlt := valuation_smul_div_pow_sub_one_lt_one hτM ((_root_.map_ne_zero _).2 hϖ0) hab hσb
  rw [hratio, ← map_pow, ← map_one (algebraMap L M), ← map_sub, hf, ← map_one f] at hlt
  exact mem_ramificationGroup_one_of_valuation_pow_sub_one_lt_one hϖ hτ0 p k
    ((ValuativeExtension.mapValueGroupWithZero_strictMono (A := L) (B := M)).lt_iff_lt.1 hlt)

variable {K} in
/-- **Wild inertia is the inverse limit of the finite-level `G_1`.** An automorphism `σ` of
`K^{alg}` lies in the wild inertia subgroup `P_K` exactly when, for every finite normal
subextension `L` of `K^{alg}/K`, its restriction to `L` lies in the first ramification group
`G_1` of `L/K`. -/
theorem mem_wildInertiaSubgroup_iff_forall_restrictNormal_mem {σ : Gal(AlgebraicClosure K/K)} :
    σ ∈ wildInertiaSubgroup K ↔ ∀ (L : IntermediateField K (AlgebraicClosure K))
      [ValuativeRel L] [TopologicalSpace L] [IsNonarchimedeanLocalField L] [ValuativeExtension K L]
      [FiniteDimensional K L] [Normal K L],
      AlgEquiv.restrictNormal σ L ∈ lowerRamificationGroup K L 1 := by
  refine ⟨fun hσ L _ _ _ _ _ _ ↦ restrictNormal_mem_lowerRamificationGroup_one L hσ, fun h ↦ ?_⟩
  refine mem_wildInertiaSubgroup_iff_pow_eq.2 fun m hm a x hx ↦ ?_
  have hm0 : m ≠ 0 := by
    rintro rfl
    exact hm (dvd_zero _)
  have hx0 : x ≠ 0 := by
    rintro rfl
    rw [zero_pow hm0] at hx
    exact (_root_.map_ne_zero _).2 a.ne_zero hx.symm
  -- A finite normal extension `L` of `K` containing `x`, with its local-field structure.
  have : FiniteDimensional K K⟮x⟯ := adjoin.finiteDimensional (Algebra.IsIntegral.isIntegral x)
  set L : IntermediateField K (AlgebraicClosure K) := normalClosure K K⟮x⟯ (AlgebraicClosure K)
  have : FiniteDimensional K L := normalClosure.is_finiteDimensional K K⟮x⟯ _
  have : Normal K L := normalClosure.normal K K⟮x⟯ _
  have hxL : x ∈ L := K⟮x⟯.le_normalClosure (mem_adjoin_simple_self K x)
  let _ := finiteIntermediateFieldValuativeRel K (AlgebraicClosure K) L
  let _ := finiteIntermediateFieldTopology K (AlgebraicClosure K) L
  have := finiteIntermediateField_isNonarchimedeanLocalField K (AlgebraicClosure K) L
  have := finiteIntermediateField_valuativeExtension K (AlgebraicClosure K) L
  have hchar : ringChar 𝓀[L] = ringChar 𝓀[K] :=
    have : CharP 𝓀[L] (ringChar 𝓀[K]) :=
      charP_of_injective_algebraMap (algebraMap 𝓀[K] 𝓀[L]).injective _
    ringChar.eq 𝓀[L] _
  have hG1 := h L
  rw [lowerRamificationGroup_def] at hG1
  set τ := AlgEquiv.restrictNormal σ L with hτ_def
  -- The ratio `z = τ x / x` is a principal unit of `L` and an `m`-th root of unity, so `z = 1`.
  set y : L := ⟨x, hxL⟩
  have hy0 : y ≠ 0 := fun h ↦ hx0 (congrArg Subtype.val h)
  set z : Lˣ := Units.mk0 (τ • y / y) (div_ne_zero ((smul_ne_zero_iff_ne _).2 hy0) hy0)
  have hz1 : z ∈ unitFiltration L 1 := smul_div_mem_unitFiltration (y := Units.mk0 y hy0) hG1 rfl
  have hym : y ^ m = algebraMap K L a := Subtype.ext hx
  have hzm : z ∈ rootsOfUnity m L := by
    rw [mem_rootsOfUnity]
    refine Units.ext ?_
    rw [Units.val_pow_eq_pow_val, Units.val_mk0, div_pow, ← smul_pow', hym, AlgEquiv.smul_def,
      AlgEquiv.commutes, div_self ((_root_.map_ne_zero _).2 a.ne_zero), Units.val_one]
  have hmL : ¬ ringChar 𝓀[L] ∣ m := hchar ▸ hm
  have hmL0 : (m : L) ≠ 0 :=
    natCast_ne_zero_of_isUnit (IsLocalRing.isUnit_natCast_iff_not_dvd.2 hmL)
  have hz : z = 1 := Subgroup.disjoint_def.1 (disjoint_rootsOfUnity_unitFiltration (i := 1) hmL0
    fun q hq hqL hqm ↦ natCastValuation_lt_sub_one_mul_of_lt_of_dvd hmL0
      (by rw [(natCastValuation_eq_zero_iff_not_dvd L m hmL0).2 hmL]; exact one_pos) hq hqL hqm)
    hzm hz1
  have hτy : τ • y = y := by
    have := congrArg Units.val hz
    rwa [Units.val_mk0, Units.val_one, div_eq_one_iff_eq hy0] at this
  have := congrArg Subtype.val hτy
  rwa [AlgEquiv.smul_def, hτ_def, AlgEquiv.restrictNormal_apply] at this

/-! ### Wild inertia is the pro-`p` Sylow subgroup of inertia -/

variable (p : ℕ) [CharP 𝓀[K] p]

/-- **Wild inertia is pro-`p`**, for `p` the residue characteristic. -/
theorem isProP_wildInertiaSubgroup : IsProP p (wildInertiaSubgroup K) := by
  rw [Subgroup.isProP_iff_isPGroup_map_mk']
  intro U
  -- `U` contains the fixing subgroup of a finite normal subextension `E`.
  obtain ⟨E, hEfin, hEnorm, hEU⟩ := (krullTopology_mem_nhds_one_iff_of_normal K
    (AlgebraicClosure K) (U : Set (Field.absoluteGaloisGroup K))).1 (U.isOpen.mem_nhds U.one_mem)
  rintro ⟨_, σ, hσ, rfl⟩
  let _ := finiteIntermediateFieldValuativeRel K (AlgebraicClosure K) E
  let _ := finiteIntermediateFieldTopology K (AlgebraicClosure K) E
  have := finiteIntermediateField_isNonarchimedeanLocalField K (AlgebraicClosure K) E
  have := finiteIntermediateField_valuativeExtension K (AlgebraicClosure K) E
  have : CharP 𝓀[E] p := charP_of_injective_algebraMap (algebraMap 𝓀[K] 𝓀[E]).injective _
  -- The restriction of `σ` to `E` lies in the `p`-group `G_1` of `E/K`.
  have hG1 := restrictNormal_mem_lowerRamificationGroup_one E hσ
  rw [lowerRamificationGroup_def] at hG1
  obtain ⟨n, hn⟩ := isPGroup_ramificationGroup (L := E) (E ≃ₐ[K] E) p (i := 1) one_pos ⟨_, hG1⟩
  -- State the kernel computation on `Gal(K^{alg}/K)`, whose group structure is not reducibly that
  -- of `Field.absoluteGaloisGroup K`.
  have hker (τ : Gal(AlgebraicClosure K/K)) (hτ : AlgEquiv.restrictNormal τ E ^ p ^ n = 1) :
      τ ^ p ^ n ∈ E.fixingSubgroup := by
    rw [← E.restrictNormalHom_ker, MonoidHom.mem_ker, map_pow]
    exact hτ
  refine ⟨n, Subtype.ext ?_⟩
  rw [SubgroupClass.coe_pow, ← map_pow, QuotientGroup.mk'_apply, OneMemClass.coe_one,
    QuotientGroup.eq_one_iff]
  exact hEU (hker σ (congrArg Subtype.val hn))

variable {K} in
/-- An element of inertia lies in wild inertia as soon as some `p`-power of it lies in every open
normal subgroup of `G_K`. -/
private theorem mem_wildInertiaSubgroup_of_forall_exists_pow_mem {σ : Gal(AlgebraicClosure K/K)}
    (hσ : σ ∈ inertiaSubgroup K)
    (h : ∀ U : OpenNormalSubgroup (Field.absoluteGaloisGroup K), ∃ n : ℕ, σ ^ p ^ n ∈ U) :
    σ ∈ wildInertiaSubgroup K := by
  obtain rfl : ringChar 𝓀[K] = p := ringChar.eq 𝓀[K] p
  have hp : (ringChar 𝓀[K]).Prime := CharP.char_is_prime 𝓀[K] _
  refine mem_wildInertiaSubgroup_iff_pow_eq.2 fun m hm a x hx ↦ ?_
  have hm0 : m ≠ 0 := by
    rintro rfl
    exact hm (dvd_zero _)
  have hx0 : x ≠ 0 := by
    rintro rfl
    rw [zero_pow hm0] at hx
    exact (_root_.map_ne_zero _).2 a.ne_zero hx.symm
  -- `σ` moves `x` by an `m`-th root of unity `ζ`, which is unramified and hence fixed by `σ`.
  set ζ := σ x / x
  have hζ : ζ ^ m = 1 := by
    rw [div_pow, ← map_pow, hx, AlgEquiv.commutes, div_self ((_root_.map_ne_zero _).2 a.ne_zero)]
  have hσζ : σ ζ = ζ :=
    (mem_inertiaSubgroup_iff.1 hσ) ζ (mem_maximalUnramifiedExtension_of_pow_eq_one hm hζ)
  have hσx : σ x = ζ * x := by rw [div_mul_cancel₀ _ hx0]
  have hpow (j : ℕ) : (σ ^ j) x = ζ ^ j * x := by
    induction j with
    | zero => simp
    | succ j ih =>
      rw [pow_succ', AlgEquiv.mul_apply, ih, map_mul, map_pow, hσζ, hσx]
      ring
  -- Some `p`-power of `σ` fixes `x`, so the order of `ζ` divides both `m` and a power of `p`.
  set S : Set (Field.absoluteGaloisGroup K) :=
    (MulAction.stabilizer Gal(AlgebraicClosure K/K) x : Set Gal(AlgebraicClosure K/K))
  obtain ⟨H, hH⟩ := ProfiniteGrp.exist_openNormalSubgroup_sub_open_nhds_of_one
    (stabilizer_isOpen_of_isIntegral x : IsOpen S)
    (one_mem (MulAction.stabilizer Gal(AlgebraicClosure K/K) x))
  obtain ⟨n, hn⟩ := h H
  -- `S` is the stabilizer of `x`, read as a subset of `Field.absoluteGaloisGroup K`.
  have hfix : (σ ^ ringChar 𝓀[K] ^ n) x = x := MulAction.mem_stabilizer_iff.1
    (show σ ^ ringChar 𝓀[K] ^ n ∈ MulAction.stabilizer Gal(AlgebraicClosure K/K) x from hH hn)
  rw [hpow, mul_eq_right₀ hx0] at hfix
  have hcop : Nat.Coprime (ringChar 𝓀[K] ^ n) m :=
    Nat.Coprime.pow_left n (hp.coprime_iff_not_dvd.2 hm)
  have hζ1 : ζ = 1 := by
    have := pow_gcd_eq_one.2 ⟨hfix, hζ⟩
    rwa [hcop.gcd_eq_one, pow_one] at this
  rw [hσx, hζ1, one_mul]

variable {K} in
/-- **Wild inertia is the largest pro-`p` subgroup of inertia**: every pro-`p` subgroup of `G_K`
contained in the inertia subgroup `I_K` is contained in `P_K`. -/
theorem le_wildInertiaSubgroup_of_isProP {R : Subgroup (Field.absoluteGaloisGroup K)}
    (hR : IsProP p R) (hRI : R ≤ inertiaSubgroup K) : R ≤ wildInertiaSubgroup K := by
  intro σ hσ
  refine mem_wildInertiaSubgroup_of_forall_exists_pow_mem p (hRI hσ) fun U ↦ ?_
  obtain ⟨n, hn⟩ := hR.isPGroup_map_mk' U ⟨_, σ, hσ, rfl⟩
  have hmem : σ ^ p ^ n ∈ U.toSubgroup := by
    rw [← QuotientGroup.eq_one_iff, QuotientGroup.mk_pow]
    exact congrArg Subtype.val hn
  exact ⟨n, hmem⟩

/-- **Wild inertia is the pro-`p` Sylow subgroup of inertia**: `P_K`, viewed as a subgroup of the
inertia subgroup `I_K`, is a Sylow pro-`p` subgroup of `I_K`, for `p` the residue
characteristic. -/
theorem isProPSylow_wildInertiaSubgroup :
    IsProPSylow p ((wildInertiaSubgroup K).subgroupOf (inertiaSubgroup K)) := by
  have : Fact p.Prime := ⟨CharP.char_is_prime 𝓀[K] p⟩
  have : CompactSpace (inertiaSubgroup K) :=
    isCompact_iff_compactSpace.1 (isClosed_inertiaSubgroup K).isCompact
  refine isProPSylow_of_maximal ((Subgroup.isProP_subgroupOf_iff
    (wildInertiaSubgroup_le_inertiaSubgroup K)).2 (isProP_wildInertiaSubgroup K p))
    fun R hR _ σ hσ ↦ Subgroup.mem_subgroupOf.2
      (mem_wildInertiaSubgroup_of_forall_exists_pow_mem p σ.2 fun U ↦ ?_)
  -- A `p`-power of `σ` lies in the trace of `U` on `I_K`, since `R` is pro-`p`.
  set V := U.comap (inertiaSubgroup K).subtype continuous_subtype_val
  obtain ⟨n, hn⟩ := hR.isPGroup_map_mk' V ⟨_, σ, hσ, rfl⟩
  have hmem : σ ^ p ^ n ∈ V.toSubgroup := by
    rw [← QuotientGroup.eq_one_iff, QuotientGroup.mk_pow]
    exact congrArg Subtype.val hn
  exact ⟨n, OpenNormalSubgroup.mem_comap.1 hmem⟩

/-- **Uniqueness of the Sylow subgroup**: `P_K` is the only Sylow pro-`p` subgroup of the inertia
subgroup `I_K`, for `p` the residue characteristic, since it is normal. -/
theorem eq_subgroupOf_wildInertiaSubgroup_of_isProPSylow {Q : Subgroup (inertiaSubgroup K)}
    (hQ : IsProPSylow p Q) : Q = (wildInertiaSubgroup K).subgroupOf (inertiaSubgroup K) := by
  have : Fact p.Prime := ⟨CharP.char_is_prime 𝓀[K] p⟩
  have : CompactSpace (inertiaSubgroup K) :=
    isCompact_iff_compactSpace.1 (isClosed_inertiaSubgroup K).isCompact
  exact (IsProPSylow.eq_of_normal p _ _ _ (isProPSylow_wildInertiaSubgroup K p) hQ
    Subgroup.normal_subgroupOf).symm

/-! ### The Frattini argument along wild inertia -/

variable {K} in
/-- **Relative Frattini reduction along wild inertia** (NSW (3.9.1)). A set which topologically
generates `G_K` together with the commutator subgroup `⁅P_K, P_K⁆` of wild inertia already
topologically generates `G_K`. -/
theorem topologicalClosure_eq_top_of_sup_wildInertiaCommutator
    {s : Set (Field.absoluteGaloisGroup K)}
    (hs : (Subgroup.closure s ⊔
      ⁅wildInertiaSubgroup K, wildInertiaSubgroup K⁆).topologicalClosure = ⊤) :
    (Subgroup.closure s).topologicalClosure = ⊤ := by
  have : Fact (ringChar 𝓀[K]).Prime := ⟨CharP.char_is_prime 𝓀[K] _⟩
  exact (isProP_wildInertiaSubgroup K _).topologicalClosure_eq_top_of_sup_commutator hs

/-! ### The image of wild inertia at finite level -/

variable {K}
variable (L : IntermediateField K (AlgebraicClosure K)) [Module.Finite K L] [IsGalois K L]
  [ValuativeRel L] [TopologicalSpace L] [IsNonarchimedeanLocalField L] [ValuativeExtension K L]

/-- **Wild inertia maps onto finite wild inertia.** For every compatible local-field structure on
a finite Galois subextension `L/K`, the image of `P_K` under restriction is `G_1(L/K)`. -/
@[simp]
theorem map_wildInertiaSubgroup_restrictNormalHom :
    (wildInertiaSubgroup K).map (AlgEquiv.restrictNormalHom L) =
      lowerRamificationGroup K L 1 := by
  set p := ringChar 𝓀[K]
  have : Fact p.Prime := ⟨CharP.char_is_prime 𝓀[K] p⟩
  have : CharP 𝓀[L] p := charP_of_injective_algebraMap (algebraMap 𝓀[K] 𝓀[L]).injective _
  have : CompactSpace (inertiaSubgroup K) :=
    isCompact_iff_compactSpace.1 (isClosed_inertiaSubgroup K).isCompact
  set f := AlgEquiv.restrictNormalHom (F := K) (K₁ := AlgebraicClosure K) L
  set I := inertiaSubgroup K
  -- Restriction maps `I_K` onto `A = G_0(L/K)`, a finite discrete group containing `G_1(L/K)`.
  set A := I.map f
  have h1A : lowerRamificationGroup K L 1 ≤ A :=
    (lowerRamificationGroup_antitone K L zero_le_one).trans
      (map_inertiaSubgroup_restrictNormalHom L).ge
  have hf : Continuous (f.subgroupMap I) :=
    continuous_induced_rng.2 ((InfiniteGalois.restrictNormalHom_continuous L).comp
      continuous_subtype_val)
  -- The image of the Sylow pro-`p` subgroup `P_K` of `I_K` is Sylow in `A`, and it lies in the
  -- `p`-group `G_1(L/K)`, so the two agree.
  have hS := (isProPSylow_wildInertiaSubgroup K p).map_of_surjective _ hf
    (f.subgroupMap_surjective I)
  have hG1 : IsProP p ((lowerRamificationGroup K L 1).subgroupOf A) := by
    rw [isProP_iff_isPGroup]
    have := isPGroup_ramificationGroup (L := L) (L ≃ₐ[K] L) p (i := 1) one_pos
    rw [← lowerRamificationGroup_def] at this
    exact this.of_equiv (Subgroup.subgroupOfEquivOfLe h1A).symm
  have hle : ((wildInertiaSubgroup K).subgroupOf I).map (f.subgroupMap I) ≤
      (lowerRamificationGroup K L 1).subgroupOf A := by
    rintro _ ⟨σ, hσ, rfl⟩
    exact restrictNormal_mem_lowerRamificationGroup_one L hσ
  refine le_antisymm (Subgroup.map_le_iff_le_comap.2 fun σ hσ ↦
    restrictNormal_mem_lowerRamificationGroup_one L hσ) fun τ hτ ↦ ?_
  have hτA : (⟨τ, h1A hτ⟩ : A) ∈ (lowerRamificationGroup K L 1).subgroupOf A :=
    Subgroup.mem_subgroupOf.2 hτ
  obtain ⟨σ, hσ, hστ⟩ := (hS.eq_of_le hG1 hle).ge hτA
  exact ⟨σ.1, Subgroup.mem_subgroupOf.1 hσ, congrArg Subtype.val hστ⟩

/-- Every element of finite wild inertia lifts to an element of absolute wild inertia. -/
theorem exists_mem_wildInertiaSubgroup_restrictNormal_eq {τ : Gal(L/K)}
    (hτ : τ ∈ lowerRamificationGroup K L 1) :
    ∃ σ ∈ wildInertiaSubgroup K, AlgEquiv.restrictNormal σ L = τ := by
  rw [← map_wildInertiaSubgroup_restrictNormalHom L] at hτ
  exact hτ

/-- **The tame criterion at finite level.** A finite Galois subextension `L` of `K^{alg}/K` lies
in the maximal tamely ramified extension `K^{t}` exactly when `L/K` is tamely ramified. -/
theorem le_maximalTameExtension_iff :
    L ≤ maximalTameExtension K (AlgebraicClosure K) ↔ IsTamelyRamified K L := by
  set T := maximalTameExtension K (AlgebraicClosure K)
  -- `P_K` fixes `L` exactly when its image `G_1(L/K)` in `Gal(L/K)` is trivial.
  have hfix : T.fixingSubgroup ≤ L.fixingSubgroup ↔ IsTamelyRamified K L := by
    rw [← lowerRamificationGroup_one_eq_bot_iff_isTamelyRamified,
      ← map_wildInertiaSubgroup_restrictNormalHom, wildInertiaSubgroup_def,
      ← IntermediateField.restrictNormalHom_ker L]
    -- `Field.absoluteGaloisGroup K` is `Gal(K^{alg}/K)` by definition, but its group structure is
    -- not reducibly that of `Gal(K^{alg}/K)`, so `rw [Subgroup.map_eq_bot_iff]` cannot fire.
    exact (Subgroup.map_eq_bot_iff _).symm
  rw [← hfix]
  refine ⟨fun h ↦ fixingSubgroup_antitone h, fun h ↦ ?_⟩
  -- Both fields are separable, and the Galois correspondence on the separable closure is
  -- inclusion-reversing.
  have hT : T ≤ separableClosure K (AlgebraicClosure K) := le_separableClosure _ _ T
  rw [← lift_restrict hT, ← fixedField_fixingSubgroup_lift_inf_separableClosure, lift_restrict]
  exact le_inf ((le_iff_le _ _).2 h) (le_separableClosure _ _ L)

section Compositum

variable {L}
variable {M : IntermediateField K (AlgebraicClosure K)} [Module.Finite K M] [IsGalois K M]
  [ValuativeRel M] [TopologicalSpace M] [IsNonarchimedeanLocalField M]
  [ValuativeExtension K M]
  [ValuativeRel ↥(L ⊔ M)] [TopologicalSpace ↥(L ⊔ M)]
  [IsNonarchimedeanLocalField ↥(L ⊔ M)] [ValuativeExtension K ↥(L ⊔ M)]

/-- The compositum of two finite Galois subextensions of the algebraic closure of a
nonarchimedean local field is tamely ramified exactly when both factors are tamely ramified.
The valuation and topology on each finite field may be any compatible local-field structures. -/
@[simp]
theorem isTamelyRamified_sup_iff :
    IsTamelyRamified K ↥(L ⊔ M) ↔ IsTamelyRamified K L ∧ IsTamelyRamified K M := by
  rw [← le_maximalTameExtension_iff (L ⊔ M), sup_le_iff,
    le_maximalTameExtension_iff L, le_maximalTameExtension_iff M]

end Compositum

end TauCeti
