/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.GrothendieckGroup.GroupAlgebra.Artin
public import TauCeti.RepresentationTheory.Induction.Artin.Modular

/-!
# Modular Artin induction with uniform coefficients

For a finite group `G` and a field of prime characteristic `p`, multiplication by `|G|` on
`G₀(k[G])` is a finite integral linear combination of induction after restriction from cyclic
subgroups of order prime to `p`. One coefficient family works for every virtual class.

This combines Artin's identity over every field with the removal of the prime part of cyclic
subgroups. In particular, it applies when `p` divides `|G|`, without semisimplicity or a
splitting-field hypothesis, and expresses every group-order multiple in the subgroup generated
by such induced classes.

## Main results

* `TauCeti.exists_linearCombination_indK0_resK0_eq_natCard_nsmul`: the uniform integral
  coefficient family.
* `TauCeti.modularArtin_natCard_nsmul_mem_indCyclicCoprime`: `|G| • x` lies in the subgroup
  generated by induction from cyclic subgroups of order prime to the characteristic.
* `TauCeti.modularArtin_exists_nsmul_mem_indCyclicCoprime`: every class has a positive multiple in
  that subgroup.

## References

* J. Neukirch, A. Schmidt, K. Wingberg, *Cohomology of Number Fields*, second edition,
  §VII.3, (7.3.4).
* J.-P. Serre, *Linear Representations of Finite Groups*, Part II, §9.2.
* J. S. Milne, *Arithmetic Duality Theorems*, second edition, Chapter I, Lemma 2.10.
-/

public section

open scoped MonoidAlgebra

namespace TauCeti

universe u

/-- **Modular Artin induction.** A single finitely supported integral coefficient family over
cyclic subgroups of order prime to `p` expresses `|G|` times every virtual class as a sum of its
induced restrictions. -/
theorem exists_linearCombination_indK0_resK0_eq_natCard_nsmul
    {k G : Type u} [Field k] [Group G] [Finite G]
    (p : ℕ) [Fact p.Prime] [CharP k p] :
    ∃ a : {D : Subgroup G // IsCyclic D ∧ ¬ p ∣ Nat.card D} →₀ ℤ,
      ∀ x : ExactK0 (finiteModulesExactStructure k[G]),
        Finsupp.linearCombination ℤ
            (fun D : {D : Subgroup G // IsCyclic D ∧ ¬ p ∣ Nat.card D} ↦
              indK0 k D.val (resK0 k D.val.subtype x)) a = Nat.card G • x := by
  obtain ⟨a, ha⟩ := exists_linearCombination_indK0_resK0_eq_sum_artinCoeff (k := k) (G := G) p
  exact ⟨a, fun x ↦ (ha x).trans (natCard_nsmul_eq_sum_artinCoeff_indK0_resK0 k G x).symm⟩

section Membership

variable {k G : Type u} [Field k] [Group G] [Finite G]
  (p : ℕ) [Fact p.Prime] [CharP k p]

/-- **The modular Artin theorem with multiplier `|G|`.** In characteristic `p`, the group-order
multiple of every class in `G₀(k[G])` lies in the subgroup generated by the classes induced from
cyclic subgroups of order prime to `p`. -/
theorem modularArtin_natCard_nsmul_mem_indCyclicCoprime
    (x : ExactK0 (finiteModulesExactStructure k[G])) :
    Nat.card G • x ∈
      ⨆ (D : Subgroup G) (_ : IsCyclic D ∧ ¬ p ∣ Nat.card D), (indK0 k D).range := by
  obtain ⟨a, ha⟩ := exists_linearCombination_indK0_resK0_eq_natCard_nsmul (k := k) (G := G) p
  rw [← ha x, Finsupp.linearCombination_apply]
  refine AddSubgroup.sum_mem _ fun D _ ↦ AddSubgroup.zsmul_mem _ ?_ _
  exact AddSubgroup.mem_iSup_of_mem D.val <|
    AddSubgroup.mem_iSup_of_mem D.property ⟨resK0 k D.val.subtype x, rfl⟩

/-- **The modular Artin induction theorem** (NSW (7.3.4), Milne ADT I Lemma 2.10). In
characteristic `p`, every class in `G₀(k[G])` has a positive multiple in the subgroup generated by
the classes induced from cyclic subgroups of order prime to `p`; the multiplier `|G|` works for
every class. -/
theorem modularArtin_exists_nsmul_mem_indCyclicCoprime
    (x : ExactK0 (finiteModulesExactStructure k[G])) :
    ∃ N : ℕ, 0 < N ∧ N • x ∈
      ⨆ (D : Subgroup G) (_ : IsCyclic D ∧ ¬ p ∣ Nat.card D), (indK0 k D).range :=
  ⟨Nat.card G, Nat.card_pos, modularArtin_natCard_nsmul_mem_indCyclicCoprime p x⟩

end Membership

end TauCeti
