/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Lookahead.EulerCharacteristicMixed.Stubs
public import TauCeti.NumberTheory.ClassFieldTheory.Local.EulerCharacteristic.GrothendieckGroup

/-!
# Modular induction for the local Euler characteristic

This file reduces equality of additive invariants on the Grothendieck group of modular
representations to equality after induction from cyclic subgroups of order prime to the
characteristic. Applied to the local Euler characteristic and the normalized absolute value of the
coefficient order, it isolates the cyclic prime-to-characteristic calculation in Tate's local
Euler-characteristic formula.

The argument uses modular Artin induction to put a positive multiple of every class in the subgroup
generated by these induced classes. The target of the invariants is torsion-free, so equality on
that multiple implies equality on the original class.

## Main results

* `TauCeti.eq_of_comp_indK0_eq_of_cyclic_coprime`: equality of additive invariants
  from equality on the relevant induction maps.
* `TauCeti.ClassFieldTheory.localEulerCharacteristicK0_eq_localCardNormK0_of_indCyclicCoprime`:
  the modular-Artin reduction for a fixed finite Galois quotient.
* `TauCeti.ClassFieldTheory.forall_localEulerCharacteristic_eq_localCardNorm_of_indCyclicCoprime`:
  the same reduction for every finite smooth discrete Galois representation.

## References

* J. Neukirch, A. Schmidt and K. Wingberg, *Cohomology of Number Fields*, 2nd ed., (7.3.4).
* J. S. Milne, *Arithmetic Duality Theorems*, 2nd ed., I, Lemma 2.10 and Theorem 2.8.
-/

public noncomputable section

open scoped MonoidAlgebra

namespace TauCeti

universe u

/-- **Equality from modular Artin induction.** Two additive invariants of modular representation
classes with values in a torsion-free group agree if they agree after induction from every cyclic
subgroup whose order is prime to the characteristic. -/
theorem eq_of_comp_indK0_eq_of_cyclic_coprime
    {k G M : Type u} [Field k] [Group G] [Finite G] [AddCommGroup M] [IsAddTorsionFree M]
    (p : ℕ) [Fact p.Prime] [CharP k p]
    (f g : ExactK0 (finiteModulesExactStructure k[G]) →+ M)
    (h : ∀ (D : Subgroup G), IsCyclic D ∧ ¬ p ∣ Nat.card D →
      f.comp (indK0 k D) = g.comp (indK0 k D)) :
    f = g := by
  apply DFunLike.ext f g
  intro x
  obtain ⟨N, hN, hx⟩ := modularArtin_exists_nsmul_mem_indCyclicCoprime p x
  apply nsmul_right_injective hN.ne'
  -- Expose the pointwise scalar multiples after applying injectivity in the target group.
  change N • f x = N • g x
  rw [← map_nsmul, ← map_nsmul]
  apply AddSubgroup.iSup_induction (C := fun y ↦ f y = g y)
    (fun D : Subgroup G ↦
      ⨆ (_ : IsCyclic D ∧ ¬ p ∣ Nat.card D), (indK0 k D).range) hx
  · intro D y hy
    apply AddSubgroup.iSup_induction (C := fun y ↦ f y = g y)
      (fun _ : IsCyclic D ∧ ¬ p ∣ Nat.card D ↦ (indK0 k D).range) hy
    · rintro hD _ ⟨z, rfl⟩
      exact DFunLike.congr_fun (h D hD) z
    · simp
    · intro a b ha hb
      simpa only [map_add] using congrArg₂ (· + ·) ha hb
  · simp
  · intro a b ha hb
    simpa only [map_add] using congrArg₂ (· + ·) ha hb

namespace ClassFieldTheory

variable (p : ℕ) [Fact p.Prime] (F : Type) [Field F] [CharZero F] [ValuativeRel F]
  [TopologicalSpace F] [IsNonarchimedeanLocalField F] [FinitePadicExtension F p]
  (V : OpenNormalSubgroup (Field.absoluteGaloisGroup F))

/-- **Modular-Artin reduction for a finite Galois quotient.** The local Euler characteristic and
the normalized absolute value agree on the Grothendieck group of `ZMod ℓ`-representations of a
finite Galois quotient if they agree after induction from every cyclic subgroup of order prime to
`ℓ`. -/
theorem localEulerCharacteristicK0_eq_localCardNormK0_of_indCyclicCoprime
    (ℓ : ℕ) [Fact ℓ.Prime]
    (h : ∀ (C : Subgroup (Field.absoluteGaloisGroup F ⧸ V.toSubgroup)),
      IsCyclic C ∧ ¬ ℓ ∣ Nat.card C →
        (localEulerCharacteristicK0 V (Nat.cast_ne_zero.2 (NeZero.ne ℓ)).isUnit).comp
            (indK0 (G := Field.absoluteGaloisGroup F ⧸ V.toSubgroup) (ZMod ℓ) C) =
          (localCardNormK0 ℓ V p).comp
            (indK0 (G := Field.absoluteGaloisGroup F ⧸ V.toSubgroup) (ZMod ℓ) C)) :
    localEulerCharacteristicK0 V (Nat.cast_ne_zero.2 (NeZero.ne ℓ)).isUnit =
      localCardNormK0 ℓ V p := by
  apply eq_of_comp_indK0_eq_of_cyclic_coprime ℓ
  exact h

/-- **Modular-Artin reduction for the local Euler-characteristic formula.** If, for every finite
Galois quotient and every prime `ℓ`, the Euler characteristic and coefficient-order invariants
agree after induction from cyclic subgroups of order prime to `ℓ`, then they agree for every
finite smooth discrete `ZMod ℓ`-representation. -/
theorem forall_localEulerCharacteristic_eq_localCardNorm_of_indCyclicCoprime
    (ℓ : ℕ) [Fact ℓ.Prime]
    (h : ∀ (V : OpenNormalSubgroup (Field.absoluteGaloisGroup F))
      (C : Subgroup (Field.absoluteGaloisGroup F ⧸ V.toSubgroup)),
      IsCyclic C ∧ ¬ ℓ ∣ Nat.card C →
        (localEulerCharacteristicK0 V (Nat.cast_ne_zero.2 (NeZero.ne ℓ)).isUnit).comp
            (indK0 (G := Field.absoluteGaloisGroup F ⧸ V.toSubgroup) (ZMod ℓ) C) =
          (localCardNormK0 ℓ V p).comp
            (indK0 (G := Field.absoluteGaloisGroup F ⧸ V.toSubgroup) (ZMod ℓ) C)) :
    ∀ (A : GalRep ℓ F) [Finite A.V] [DiscreteTopology A.V]
      [Fact (IsSmoothDiscrete (ZMod ℓ) A)],
        localEulerCharacteristic (Nat.cast_ne_zero.2 (NeZero.ne ℓ)) A = localCardNorm p A := by
  apply (forall_localEulerCharacteristic_eq_localCardNorm_iff p
    (Nat.cast_ne_zero.2 (NeZero.ne ℓ)).isUnit).2
  intro V
  exact localEulerCharacteristicK0_eq_localCardNormK0_of_indCyclicCoprime p F V ℓ (h V)

end ClassFieldTheory

end TauCeti
